// This file is autogenerated by the hyperdispatch compiler
/* eslint-disable camelcase */

const { c, b4a, assert, DispatchError, ERRORS } = require('hyperdispatch/runtime')
const { version, getEncoding, setVersion } = require('./messages.js')

const defaultVersion = version

class Router {
  constructor () {
    this._handler0 = null
    this._handler1 = null
    this._handler2 = null
    this._handler3 = null
    this._handler4 = null
    this._handler5 = null
    this._handler6 = null
    this._handler7 = null
    this._handler8 = null
    this._handler9 = null
    this._handler10 = null
    this._handler11 = null
    this._handler12 = null
    this._handler13 = null
    this._handler14 = null
    this._handler15 = null
    this._handler16 = null
    this._handler17 = null
    this._handler18 = null
    this._handler19 = null
    this._handler20 = null
    this._handler21 = null
    this._handler22 = null
    this._handler23 = null
    this._handler24 = null
    this._handler25 = null
    this._handler26 = null
    this._handler27 = null
    this._handler25 = null
    this._handler26 = null

    this._missing = 30
  }

  add (name, handler) {
    switch (name) {
      case '@goji/add-writer':
        this._handler0 = handler
        break
      case '@goji/add-invite':
        this._handler1 = handler
        break
      case '@goji/add-board':
        this._handler2 = handler
        break
      case '@goji/rename-board':
        this._handler3 = handler
        break
      case '@goji/delete-board':
        this._handler4 = handler
        break
      case '@goji/add-card':
        this._handler5 = handler
        break
      case '@goji/update-card':
        this._handler6 = handler
        break
      case '@goji/remove-card':
        this._handler7 = handler
        break
      case '@goji/add-connection':
        this._handler8 = handler
        break
      case '@goji/remove-connection':
        this._handler9 = handler
        break
      case '@goji/update-connection':
        this._handler10 = handler
        break
      case '@goji/add-chat':
        this._handler11 = handler
        break
      case '@goji/remove-chats':
        this._handler12 = handler
        break
      case '@goji/update-identity':
        this._handler13 = handler
        break
      case '@goji/assign-role':
        this._handler14 = handler
        break
      case '@goji/set-flow-status':
        this._handler15 = handler
        break
      case '@goji/remove-flow-statuses':
        this._handler16 = handler
        break
      case '@goji/add-wallet':
        this._handler17 = handler
        break
      case '@goji/remove-wallet':
        this._handler18 = handler
        break
      case '@goji/add-template':
        this._handler19 = handler
        break
      case '@goji/update-template':
        this._handler20 = handler
        break
      case '@goji/remove-template':
        this._handler21 = handler
        break
      case '@goji/add-receivable':
        this._handler22 = handler
        break
      case '@goji/update-receivable':
        this._handler23 = handler
        break
      case '@goji/remove-receivable':
        this._handler24 = handler
        break
      case '@goji/add-knowledge-document':
        this._handler25 = handler
        break
      case '@goji/rag-search':
        this._handler26 = handler
        break
      case '@goji/rag-search-result':
        this._handler27 = handler
        break
      case '@goji/set-company-profile':
        this._handler28 = handler
        break
      case '@goji/remove-company-profile':
        this._handler29 = handler
        break
      default:
        throw DispatchError.NONEXISTENT_ROUTE(name)
    }
    this._missing--
  }

  _checkAll () {
    assert(this._handler0 !== null, 'Missing handler for "@goji/add-writer"')
    assert(this._handler1 !== null, 'Missing handler for "@goji/add-invite"')
    assert(this._handler2 !== null, 'Missing handler for "@goji/add-board"')
    assert(this._handler3 !== null, 'Missing handler for "@goji/rename-board"')
    assert(this._handler4 !== null, 'Missing handler for "@goji/delete-board"')
    assert(this._handler5 !== null, 'Missing handler for "@goji/add-card"')
    assert(this._handler6 !== null, 'Missing handler for "@goji/update-card"')
    assert(this._handler7 !== null, 'Missing handler for "@goji/remove-card"')
    assert(this._handler8 !== null, 'Missing handler for "@goji/add-connection"')
    assert(this._handler9 !== null, 'Missing handler for "@goji/remove-connection"')
    assert(this._handler10 !== null, 'Missing handler for "@goji/update-connection"')
    assert(this._handler11 !== null, 'Missing handler for "@goji/add-chat"')
    assert(this._handler12 !== null, 'Missing handler for "@goji/remove-chats"')
    assert(this._handler13 !== null, 'Missing handler for "@goji/update-identity"')
    assert(this._handler14 !== null, 'Missing handler for "@goji/assign-role"')
    assert(this._handler15 !== null, 'Missing handler for "@goji/set-flow-status"')
    assert(this._handler16 !== null, 'Missing handler for "@goji/remove-flow-statuses"')
    assert(this._handler17 !== null, 'Missing handler for "@goji/add-wallet"')
    assert(this._handler18 !== null, 'Missing handler for "@goji/remove-wallet"')
    assert(this._handler19 !== null, 'Missing handler for "@goji/add-template"')
    assert(this._handler20 !== null, 'Missing handler for "@goji/update-template"')
    assert(this._handler21 !== null, 'Missing handler for "@goji/remove-template"')
    assert(this._handler22 !== null, 'Missing handler for "@goji/add-receivable"')
    assert(this._handler23 !== null, 'Missing handler for "@goji/update-receivable"')
    assert(this._handler24 !== null, 'Missing handler for "@goji/remove-receivable"')
    assert(this._handler25 !== null, 'Missing handler for "@goji/add-knowledge-document"')
    assert(this._handler26 !== null, 'Missing handler for "@goji/rag-search"')
    assert(this._handler27 !== null, 'Missing handler for "@goji/rag-search-result"')
    assert(this._handler28 !== null, 'Missing handler for "@goji/set-company-profile"')
    assert(this._handler29 !== null, 'Missing handler for "@goji/remove-company-profile"')
  }

  async dispatch (message, context) {
    if (this._missing > 0) {
      this._checkAll()
    }

    setVersion(defaultVersion)

    const op = b4a.isBuffer(message) ? decode(message) : message

    switch (op.id) {
      case 0:
        return this._handler0(op.value, context)
      case 1:
        return this._handler1(op.value, context)
      case 2:
        return this._handler2(op.value, context)
      case 3:
        return this._handler3(op.value, context)
      case 4:
        return this._handler4(op.value, context)
      case 5:
        return this._handler5(op.value, context)
      case 6:
        return this._handler6(op.value, context)
      case 7:
        return this._handler7(op.value, context)
      case 8:
        return this._handler8(op.value, context)
      case 9:
        return this._handler9(op.value, context)
      case 10:
        return this._handler10(op.value, context)
      case 11:
        return this._handler11(op.value, context)
      case 12:
        return this._handler12(op.value, context)
      case 13:
        return this._handler13(op.value, context)
      case 14:
        return this._handler14(op.value, context)
      case 15:
        return this._handler15(op.value, context)
      case 16:
        return this._handler16(op.value, context)
      case 17:
        return this._handler17(op.value, context)
      case 18:
        return this._handler18(op.value, context)
      case 19:
        return this._handler19(op.value, context)
      case 20:
        return this._handler20(op.value, context)
      case 21:
        return this._handler21(op.value, context)
      case 22:
        return this._handler22(op.value, context)
      case 23:
        return this._handler23(op.value, context)
      case 24:
        return this._handler24(op.value, context)
      case 25:
        return this._handler25(op.value, context)
      case 26:
        return this._handler26(op.value, context)
      case 27:
        return this._handler27(op.value, context)
      case 28:
        return this._handler28(op.value, context)
      case 29:
        return this._handler29(op.value, context)
      default:
        throw DispatchError.HANDLER_NOT_FOUND_BY_ID(op.id)
    }
  }
}

function encode (name, message, { version = defaultVersion } = {}) {
  const state = { buffer: null, start: 0, end: 0 }

  const route = getRouteByName(name)
  setVersion(version)

  c.uint.preencode(state, route.id)
  route.enc.preencode(state, message)

  state.buffer = b4a.allocUnsafe(state.end)
  c.uint.encode(state, route.id)
  route.enc.encode(state, message)

  return state.buffer
}

function decode (buffer, { version = defaultVersion } = {}) {
  const state = { buffer, start: 0, end: buffer.length }

  const id = c.uint.decode(state)
  const route = getRouteById(id)
  setVersion(version)

  const value = route.enc.decode(state)
  return { id, name: route.name, value }
}

const route0 = {
  name: '@goji/add-writer',
  id: 0,
  enc: getEncoding('@goji/writer')
}

const route1 = {
  name: '@goji/add-invite',
  id: 1,
  enc: getEncoding('@goji/invite')
}

const route2 = {
  name: '@goji/add-board',
  id: 2,
  enc: getEncoding('@goji/board')
}

const route3 = {
  name: '@goji/rename-board',
  id: 3,
  enc: getEncoding('@goji/board-rename')
}

const route4 = {
  name: '@goji/delete-board',
  id: 4,
  enc: getEncoding('@goji/board-delete')
}

const route5 = {
  name: '@goji/add-card',
  id: 5,
  enc: getEncoding('@goji/card')
}

const route6 = {
  name: '@goji/update-card',
  id: 6,
  enc: getEncoding('@goji/card-update')
}

const route7 = {
  name: '@goji/remove-card',
  id: 7,
  enc: getEncoding('@goji/card-remove')
}

const route8 = {
  name: '@goji/add-connection',
  id: 8,
  enc: getEncoding('@goji/connection-add')
}

const route9 = {
  name: '@goji/remove-connection',
  id: 9,
  enc: getEncoding('@goji/connection-remove')
}

const route10 = {
  name: '@goji/update-connection',
  id: 10,
  enc: getEncoding('@goji/connection-update')
}

const route11 = {
  name: '@goji/add-chat',
  id: 11,
  enc: getEncoding('@goji/chat-msg')
}

const route12 = {
  name: '@goji/remove-chats',
  id: 12,
  enc: getEncoding('@goji/chats-remove')
}

const route13 = {
  name: '@goji/update-identity',
  id: 13,
  enc: getEncoding('@goji/identity')
}

const route14 = {
  name: '@goji/assign-role',
  id: 14,
  enc: getEncoding('@goji/identity')
}

const route15 = {
  name: '@goji/set-flow-status',
  id: 15,
  enc: getEncoding('@goji/flow-status')
}

const route16 = {
  name: '@goji/remove-flow-statuses',
  id: 16,
  enc: getEncoding('@goji/flow-status-remove')
}

const route17 = {
  name: '@goji/add-wallet',
  id: 17,
  enc: getEncoding('@goji/wallet')
}

const route18 = {
  name: '@goji/remove-wallet',
  id: 18,
  enc: getEncoding('@goji/wallet-remove')
}

const route19 = {
  name: '@goji/add-template',
  id: 19,
  enc: getEncoding('@goji/template')
}

const route20 = {
  name: '@goji/update-template',
  id: 20,
  enc: getEncoding('@goji/template')
}

const route21 = {
  name: '@goji/remove-template',
  id: 21,
  enc: getEncoding('@goji/template-remove')
}

const route22 = {
  name: '@goji/add-receivable',
  id: 22,
  enc: getEncoding('@goji/receivable')
}

const route23 = {
  name: '@goji/update-receivable',
  id: 23,
  enc: getEncoding('@goji/receivable')
}

const route24 = {
  name: '@goji/remove-receivable',
  id: 24,
  enc: getEncoding('@goji/receivable-remove')
}

const route25 = {
  name: '@goji/add-knowledge-document',
  id: 25,
  enc: getEncoding('@goji/knowledge-document')
}

const route26 = {
  name: '@goji/rag-search',
  id: 26,
  enc: getEncoding('@goji/rag-search')
}

const route27 = {
  name: '@goji/rag-search-result',
  id: 27,
  enc: getEncoding('@goji/rag-search-result')
}

const route28 = {
  name: '@goji/set-company-profile',
  id: 28,
  enc: getEncoding('@goji/company-profile')
}

const route29 = {
  name: '@goji/remove-company-profile',
  id: 26,
  enc: getEncoding('@goji/company-profile-remove')
}

function getRouteByName (name) {
  switch (name) {
    case '@goji/add-writer':
      return route0
    case '@goji/add-invite':
      return route1
    case '@goji/add-board':
      return route2
    case '@goji/rename-board':
      return route3
    case '@goji/delete-board':
      return route4
    case '@goji/add-card':
      return route5
    case '@goji/update-card':
      return route6
    case '@goji/remove-card':
      return route7
    case '@goji/add-connection':
      return route8
    case '@goji/remove-connection':
      return route9
    case '@goji/update-connection':
      return route10
    case '@goji/add-chat':
      return route11
    case '@goji/remove-chats':
      return route12
    case '@goji/update-identity':
      return route13
    case '@goji/assign-role':
      return route14
    case '@goji/set-flow-status':
      return route15
    case '@goji/remove-flow-statuses':
      return route16
    case '@goji/add-wallet':
      return route17
    case '@goji/remove-wallet':
      return route18
    case '@goji/add-template':
      return route19
    case '@goji/update-template':
      return route20
    case '@goji/remove-template':
      return route21
    case '@goji/add-receivable':
      return route22
    case '@goji/update-receivable':
      return route23
    case '@goji/remove-receivable':
      return route24
    case '@goji/add-knowledge-document':
      return route25
    case '@goji/rag-search':
      return route26
    case '@goji/rag-search-result':
      return route27
    case '@goji/set-company-profile':
      return route28
    case '@goji/remove-company-profile':
      return route29
    default:
      throw DispatchError.ROUTE_NOT_FOUND_BY_NAME(name)
  }
}

function getRouteById (id) {
  switch (id) {
    case 0:
      return route0
    case 1:
      return route1
    case 2:
      return route2
    case 3:
      return route3
    case 4:
      return route4
    case 5:
      return route5
    case 6:
      return route6
    case 7:
      return route7
    case 8:
      return route8
    case 9:
      return route9
    case 10:
      return route10
    case 11:
      return route11
    case 12:
      return route12
    case 13:
      return route13
    case 14:
      return route14
    case 15:
      return route15
    case 16:
      return route16
    case 17:
      return route17
    case 18:
      return route18
    case 19:
      return route19
    case 20:
      return route20
    case 21:
      return route21
    case 22:
      return route22
    case 23:
      return route23
    case 24:
      return route24
    case 25:
      return route25
    case 26:
      return route26
    case 27:
      return route27
    case 28:
      return route28
    case 29:
      return route29
    default:
      throw DispatchError.HANDLER_NOT_FOUND_BY_ID(id)
  }
}

module.exports = {
  version,
  encode,
  decode,
  Router,
  DispatchError,
  ERRORS
}
