'use client'

import { useState } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { Plus, Trash2, GripVertical } from 'lucide-react'

interface TemplateField {
  key: string
  label: string
  type: 'text' | 'number' | 'date' | 'textarea'
  autoFill: boolean
  position: 'header' | 'body' | 'footer'
}

interface Template {
  id: string
  name: string
  companyName: string | null
  fields: TemplateField[]
  html: string
  isDefault: boolean
  createdAt?: number
  updatedAt?: number
}

interface TemplateEditorProps {
  template: Template | null
  onSave: (template: Template) => void
  onClose: () => void
  apiUrl: string
}

const FIELD_TYPES = [
  { value: 'text', label: 'Text' },
  { value: 'number', label: 'Number' },
  { value: 'date', label: 'Date' },
  { value: 'textarea', label: 'Long Text' }
]

const AUTO_FILL_OPTIONS = [
  { value: 'recipient', label: 'Recipient Name' },
  { value: 'sender', label: 'Sender Name' },
  { value: 'amount', label: 'Amount' },
  { value: 'date', label: 'Current Date' },
  { value: 'txHash', label: 'Transaction Hash' },
  { value: 'chain', label: 'Chain' }
]

const DEFAULT_FIELDS: TemplateField[] = [
  { key: 'recipient', label: 'To', type: 'text', autoFill: true, position: 'body' },
  { key: 'amount', label: 'Amount', type: 'number', autoFill: true, position: 'body' },
  { key: 'date', label: 'Date', type: 'date', autoFill: true, position: 'body' },
  { key: 'txHash', label: 'Transaction', type: 'text', autoFill: true, position: 'footer' }
]

function generateHtml(companyName: string, fields: TemplateField[]): string {
  const headerFields = fields.filter((f) => f.position === 'header')
  const bodyFields = fields.filter((f) => f.position === 'body')
  const footerFields = fields.filter((f) => f.position === 'footer')

  const renderField = (field: TemplateField) => {
    const value = field.autoFill ? `{{${field.key}}}` : `[${field.label}]`
    return `
      <div class="field">
        <div class="label">${field.label}</div>
        <div class="value">${field.type === 'textarea' ? `<div class="textarea">${value}</div>` : value}${field.type === 'number' ? ' USDC' : ''}</div>
      </div>`
  }

  return `<!DOCTYPE html>
<html>
<head>
<style>
  body { font-family: Arial, sans-serif; padding: 40px; max-width: 600px; margin: 0 auto; color: #333; }
  h1 { border-bottom: 2px solid #7FD9B0; padding-bottom: 10px; margin-bottom: 5px; }
  .subtitle { color: #666; margin-bottom: 30px; }
  .section { margin: 20px 0; }
  .section-title { font-size: 12px; color: #999; text-transform: uppercase; letter-spacing: 1px; margin-bottom: 10px; border-bottom: 1px solid #eee; padding-bottom: 5px; }
  .field { margin: 12px 0; }
  .label { color: #666; font-size: 12px; }
  .value { font-size: 16px; color: #333; }
  .textarea { background: #f9f9f9; padding: 12px; border-radius: 6px; min-height: 60px; }
  .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #eee; color: #999; font-size: 11px; }
  .header-section { margin-bottom: 30px; }
  .company { font-size: 24px; font-weight: bold; }
</style>
</head>
<body>
  <div class="header-section">
    <div class="company">${companyName || '{{company}}'}</div>
    <div class="subtitle">Document</div>
    ${headerFields.map(renderField).join('')}
  </div>
  
  <div class="section">
    <div class="section-title">Details</div>
    ${bodyFields.map(renderField).join('')}
  </div>
  
  <div class="footer">
    ${footerFields.map(renderField).join('')}
    <div style="margin-top: 10px">Generated by Goji</div>
  </div>
</body>
</html>`
}

function renderPreviewHtml(html: string, companyName: string, fields: TemplateField[]): string {
  let preview = html
  preview = preview.replace(/\{\{company\}\}/g, companyName || 'Company Name')
  
  for (const field of fields) {
    const regex = new RegExp(`\\{\\{${field.key}\\}\\}`, 'g')
    let sampleValue = ''
    if (field.autoFill) {
      switch (field.key) {
        case 'recipient': sampleValue = 'John Doe'; break
        case 'sender': sampleValue = 'Acme Corp'; break
        case 'amount': sampleValue = '1,000'; break
        case 'date': sampleValue = new Date().toLocaleDateString(); break
        case 'txHash': sampleValue = '0x1234...abcd'; break
        case 'chain': sampleValue = 'Arc Testnet'; break
        default: sampleValue = `[${field.label}]`
      }
    } else {
      sampleValue = `[${field.label}]`
    }
    preview = preview.replace(regex, sampleValue)
  }
  
  return preview
}

export default function TemplateEditor({ template, onSave, onClose, apiUrl }: TemplateEditorProps) {
  const [name, setName] = useState(template?.name || '')
  const [companyName, setCompanyName] = useState(template?.companyName || '')
  const [fields, setFields] = useState<TemplateField[]>(template?.fields || DEFAULT_FIELDS)
  const [saving, setSaving] = useState(false)
  const [previewTab, setPreviewTab] = useState<'preview' | 'fields'>('preview')

  const addField = () => {
    const newKey = `field${Date.now()}`
    setFields((prev) => [
      ...prev,
      { key: newKey, label: 'New Field', type: 'text', autoFill: false, position: 'body' }
    ])
  }

  const updateField = (index: number, updates: Partial<TemplateField>) => {
    setFields((prev) => prev.map((f, i) => (i === index ? { ...f, ...updates } : f)))
  }

  const removeField = (index: number) => {
    setFields((prev) => prev.filter((_, i) => i !== index))
  }

  const moveField = (index: number, direction: 'up' | 'down') => {
    const newFields = [...fields]
    const newIndex = direction === 'up' ? index - 1 : index + 1
    if (newIndex < 0 || newIndex >= newFields.length) return
    ;[newFields[index], newFields[newIndex]] = [newFields[newIndex], newFields[index]]
    setFields(newFields)
  }

  const generatedHtml = generateHtml(companyName, fields)
  const previewHtml = renderPreviewHtml(generatedHtml, companyName, fields)

  const handleSave = async () => {
    if (!name) return
    setSaving(true)
    try {
      const method = template ? 'PUT' : 'POST'
      const url = template ? `${apiUrl}/api/templates/${template.id}` : `${apiUrl}/api/templates`
      const res = await fetch(url, {
        method,
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ name, companyName, fields, html: generatedHtml })
      })
      if (res.ok) {
        const data = await res.json()
        onSave({
          id: data.id || template?.id || '',
          name,
          companyName,
          fields,
          html: generatedHtml,
          isDefault: template?.isDefault || false,
          createdAt: template?.createdAt || Date.now(),
          updatedAt: Date.now()
        })
      }
    } catch {}
    setSaving(false)
  }

  return (
    <AnimatePresence>
      <motion.div
        key='backdrop'
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        exit={{ opacity: 0 }}
        className='fixed inset-0 bg-black/30 z-50'
        onClick={onClose}
      />
      <motion.div
        key='editor'
        initial={{ opacity: 0, scale: 0.95, y: 10 }}
        animate={{ opacity: 1, scale: 1, y: 0 }}
        exit={{ opacity: 0, scale: 0.95, y: 10 }}
        transition={{ duration: 0.2 }}
        className='fixed top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 z-50 bg-card rounded-2xl shadow-[0_20px_60px_rgba(43,36,64,0.2)] w-[90vw] max-w-[1100px] h-[85vh] overflow-hidden flex flex-col'
      >
        {/* Header */}
        <div className='flex items-center justify-between px-6 py-4 border-b border-ink/8'>
          <h3 className='font-display text-lg font-semibold'>
            {template ? 'Edit Template' : 'New Template'}
          </h3>
          <button
            onClick={onClose}
            className='w-7 h-7 rounded-lg hover:bg-ink/5 flex items-center justify-center text-ink/30 hover:text-ink/60 transition-colors'
          >
            &times;
          </button>
        </div>

        {/* Content */}
        <div className='flex-1 flex overflow-hidden'>
          {/* Left: Configuration */}
          <div className='w-1/2 p-6 overflow-y-auto border-r border-ink/8'>
            <div className='space-y-5'>
              {/* Basic Info */}
              <div className='space-y-3'>
                <div>
                  <label className='text-xs text-ink/40 mb-1.5 block'>Template Name</label>
                  <input
                    value={name}
                    onChange={(e) => setName(e.target.value)}
                    className='w-full text-sm text-ink bg-ink/5 border border-ink/10 rounded-xl px-4 py-2.5 focus:outline-none focus:border-ink/20'
                    placeholder='e.g., Payment Receipt'
                  />
                </div>

                <div>
                  <label className='text-xs text-ink/40 mb-1.5 block'>Company Name</label>
                  <input
                    value={companyName}
                    onChange={(e) => setCompanyName(e.target.value)}
                    className='w-full text-sm text-ink bg-ink/5 border border-ink/10 rounded-xl px-4 py-2.5 focus:outline-none focus:border-ink/20'
                    placeholder='e.g., Acme Corp'
                  />
                </div>
              </div>

              {/* Fields */}
              <div>
                <div className='flex items-center justify-between mb-3'>
                  <label className='text-sm font-medium text-ink'>Document Fields</label>
                  <button
                    onClick={addField}
                    className='flex items-center gap-1 text-xs text-mint hover:text-[#1B7A50] font-medium transition-colors'
                  >
                    <Plus className='w-3.5 h-3.5' />
                    Add Field
                  </button>
                </div>

                <div className='space-y-2'>
                  {fields.map((field, i) => (
                    <div
                      key={field.key}
                      className='bg-ink/3 rounded-xl p-3 space-y-2'
                    >
                      <div className='flex items-center gap-2'>
                        <GripVertical className='w-4 h-4 text-ink/20 cursor-move' />
                        <input
                          value={field.label}
                          onChange={(e) => updateField(i, { label: e.target.value })}
                          className='flex-1 text-sm text-ink bg-transparent border-b border-ink/10 focus:outline-none focus:border-ink/20 px-1 py-0.5'
                          placeholder='Field label'
                        />
                        <button
                          onClick={() => moveField(i, 'up')}
                          disabled={i === 0}
                          className='text-ink/30 hover:text-ink/60 disabled:opacity-20 transition-colors text-xs'
                        >
                          ↑
                        </button>
                        <button
                          onClick={() => moveField(i, 'down')}
                          disabled={i === fields.length - 1}
                          className='text-ink/30 hover:text-ink/60 disabled:opacity-20 transition-colors text-xs'
                        >
                          ↓
                        </button>
                        <button
                          onClick={() => removeField(i)}
                          className='text-ink/30 hover:text-coral transition-colors'
                        >
                          <Trash2 className='w-4 h-4' />
                        </button>
                      </div>

                      <div className='flex items-center gap-2 pl-6'>
                        <select
                          value={field.type}
                          onChange={(e) => updateField(i, { type: e.target.value as TemplateField['type'] })}
                          className='text-xs text-ink bg-white border border-ink/10 rounded-lg px-2 py-1 focus:outline-none'
                        >
                          {FIELD_TYPES.map((t) => (
                            <option key={t.value} value={t.value}>{t.label}</option>
                          ))}
                        </select>

                        <select
                          value={field.position}
                          onChange={(e) => updateField(i, { position: e.target.value as TemplateField['position'] })}
                          className='text-xs text-ink bg-white border border-ink/10 rounded-lg px-2 py-1 focus:outline-none'
                        >
                          <option value='header'>Header</option>
                          <option value='body'>Body</option>
                          <option value='footer'>Footer</option>
                        </select>

                        <select
                          value={field.autoFill ? field.key : ''}
                          onChange={(e) => {
                            if (e.target.value) {
                              const autoOption = AUTO_FILL_OPTIONS.find((o) => o.value === e.target.value)
                              updateField(i, { autoFill: true, key: e.target.value, label: autoOption?.label || field.label })
                            } else {
                              updateField(i, { autoFill: false })
                            }
                          }}
                          className='text-xs text-ink bg-white border border-ink/10 rounded-lg px-2 py-1 focus:outline-none'
                        >
                          <option value=''>MANUAL</option>
                          {AUTO_FILL_OPTIONS.map((o) => (
                            <option key={o.value} value={o.value}>{o.label}</option>
                          ))}
                        </select>
                      </div>
                    </div>
                  ))}
                </div>

                {fields.length === 0 && (
                  <div className='text-center py-6 text-ink/30 text-sm'>
                    No fields yet. Click &quot;Add Field&quot; to start.
                  </div>
                )}
              </div>
            </div>
          </div>

          {/* Right: Preview */}
          <div className='w-1/2 flex flex-col min-w-0'>
            {/* Tabs */}
            <div className='flex border-b border-ink/8'>
              <button
                onClick={() => setPreviewTab('preview')}
                className={`flex-1 py-3 text-sm font-medium transition-colors ${
                  previewTab === 'preview' ? 'text-ink border-b-2 border-ink' : 'text-ink/40 hover:text-ink/60'
                }`}
              >
                Preview
              </button>
              <button
                onClick={() => setPreviewTab('fields')}
                className={`flex-1 py-3 text-sm font-medium transition-colors ${
                  previewTab === 'fields' ? 'text-ink border-b-2 border-ink' : 'text-ink/40 hover:text-ink/60'
                }`}
              >
                Fields Summary
              </button>
            </div>

            <div className='flex-1 overflow-y-auto p-6'>
              {previewTab === 'preview' ? (
                <div className='bg-white rounded-xl border border-ink/10 overflow-hidden'>
                  <iframe
                    srcDoc={previewHtml}
                    className='w-full'
                    style={{ minHeight: 400 }}
                    title='Template Preview'
                  />
                </div>
              ) : (
                <div className='space-y-3'>
                  <div className='bg-ink/3 rounded-xl p-4'>
                    <div className='text-xs text-ink/40 mb-2'>Company Name</div>
                    <div className='text-sm text-ink font-medium'>{companyName || 'Not set'}</div>
                  </div>
                  
                  {fields.length > 0 ? (
                    <div className='bg-ink/3 rounded-xl p-4'>
                      <div className='text-xs text-ink/40 mb-3'>Fields ({fields.length})</div>
                      <div className='space-y-2'>
                      {fields.map((field) => (
                        <div key={field.key} className='flex items-center justify-between text-sm'>
                            <span className='text-ink'>{field.label}</span>
                            <span className='text-ink/40 text-xs'>
                              {field.autoFill ? `Auto: ${AUTO_FILL_OPTIONS.find((o) => o.value === field.key)?.label || field.key}` : 'User input'}
                              {' • '}
                              {field.position}
                            </span>
                          </div>
                        ))}
                      </div>
                    </div>
                  ) : (
                    <div className='text-center py-6 text-ink/30 text-sm'>
                      No fields defined
                    </div>
                  )}
                </div>
              )}
            </div>
          </div>
        </div>

        {/* Footer */}
        <div className='flex items-center justify-end gap-2 px-6 py-4 border-t border-ink/8'>
          <button
            onClick={onClose}
            className='px-4 py-2 text-xs text-ink/50 hover:text-ink/70 transition-colors'
          >
            Cancel
          </button>
          <button
            onClick={handleSave}
            disabled={!name || saving}
            className='px-4 py-2 bg-ink text-lavender text-xs font-medium rounded-xl hover:opacity-90 transition-opacity disabled:opacity-30'
          >
            {saving ? 'Saving...' : 'Save Template'}
          </button>
        </div>
      </motion.div>
    </AnimatePresence>
  )
}
