// This file is autogenerated by the hyperschema compiler
// Schema Version: 2
/* eslint-disable camelcase */
/* eslint-disable quotes */
/* eslint-disable space-before-function-paren */

const { c } = require('hyperschema/runtime')

const VERSION = 2

// eslint-disable-next-line no-unused-vars
let version = VERSION

// @goji/writer
const encoding0 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.key)
  },
  encode(state, m) {
    c.buffer.encode(state, m.key)
  },
  decode(state) {
    const r0 = c.buffer.decode(state)

    return {
      key: r0
    }
  }
}

// @goji/invite
const encoding1 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.id)
    c.buffer.preencode(state, m.invite)
    c.buffer.preencode(state, m.publicKey)
    c.int.preencode(state, m.expires)
  },
  encode(state, m) {
    c.buffer.encode(state, m.id)
    c.buffer.encode(state, m.invite)
    c.buffer.encode(state, m.publicKey)
    c.int.encode(state, m.expires)
  },
  decode(state) {
    const r0 = c.buffer.decode(state)
    const r1 = c.buffer.decode(state)
    const r2 = c.buffer.decode(state)
    const r3 = c.int.decode(state)

    return {
      id: r0,
      invite: r1,
      publicKey: r2,
      expires: r3
    }
  }
}

// @goji/board
const encoding2 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.id)
    c.string.preencode(state, m.name)
    c.int.preencode(state, m.createdAt)
    c.int.preencode(state, m.updatedAt)
  },
  encode(state, m) {
    c.buffer.encode(state, m.id)
    c.string.encode(state, m.name)
    c.int.encode(state, m.createdAt)
    c.int.encode(state, m.updatedAt)
  },
  decode(state) {
    const r0 = c.buffer.decode(state)
    const r1 = c.string.decode(state)
    const r2 = c.int.decode(state)
    const r3 = c.int.decode(state)

    return {
      id: r0,
      name: r1,
      createdAt: r2,
      updatedAt: r3
    }
  }
}

// @goji/card
const encoding3 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.id)
    c.buffer.preencode(state, m.boardId)
    c.string.preencode(state, m.category)
    c.string.preencode(state, m.title)
    c.float64.preencode(state, m.x)
    c.float64.preencode(state, m.y)
    state.end++ // max flag is 1 so always one byte

    if (m.fields) c.json.preencode(state, m.fields)
    c.int.preencode(state, m.updatedAt)
  },
  encode(state, m) {
    const flags = m.fields ? 1 : 0

    c.buffer.encode(state, m.id)
    c.buffer.encode(state, m.boardId)
    c.string.encode(state, m.category)
    c.string.encode(state, m.title)
    c.float64.encode(state, m.x)
    c.float64.encode(state, m.y)
    c.uint.encode(state, flags)

    if (m.fields) c.json.encode(state, m.fields)
    c.int.encode(state, m.updatedAt)
  },
  decode(state) {
    const r0 = c.buffer.decode(state)
    const r1 = c.buffer.decode(state)
    const r2 = c.string.decode(state)
    const r3 = c.string.decode(state)
    const r4 = c.float64.decode(state)
    const r5 = c.float64.decode(state)
    const flags = c.uint.decode(state)

    return {
      id: r0,
      boardId: r1,
      category: r2,
      title: r3,
      x: r4,
      y: r5,
      fields: (flags & 1) !== 0 ? c.json.decode(state) : null,
      updatedAt: c.int.decode(state)
    }
  }
}

// @goji/connection
const encoding4 = {
  preencode(state, m) {
    const flags =
      (m.label ? 1 : 0) |
      (m.amount ? 2 : 0) |
      (m.payment ? 4 : 0) |
      (m.document ? 8 : 0) |
      (m.template ? 16 : 0) |
      (m.customDoc ? 32 : 0) |
      (m.docName ? 64 : 0) |
      (m.txHash ? 128 : 0) |
      (m.delegationEnabled ? 256 : 0)

    c.buffer.preencode(state, m.id)
    c.buffer.preencode(state, m.boardId)
    c.string.preencode(state, m.from)
    c.string.preencode(state, m.to)
    c.uint.preencode(state, flags)

    if (m.label) c.string.preencode(state, m.label)
    c.int.preencode(state, m.updatedAt)
    if (m.amount) c.string.preencode(state, m.amount)
    if (m.payment) c.int.preencode(state, m.payment)
    if (m.document) c.int.preencode(state, m.document)
    if (m.template) c.string.preencode(state, m.template)
    if (m.customDoc) c.string.preencode(state, m.customDoc)
    if (m.docName) c.string.preencode(state, m.docName)
    if (m.txHash) c.string.preencode(state, m.txHash)
    if (m.delegationEnabled) c.int.preencode(state, m.delegationEnabled)
  },
  encode(state, m) {
    const flags =
      (m.label ? 1 : 0) |
      (m.amount ? 2 : 0) |
      (m.payment ? 4 : 0) |
      (m.document ? 8 : 0) |
      (m.template ? 16 : 0) |
      (m.customDoc ? 32 : 0) |
      (m.docName ? 64 : 0) |
      (m.txHash ? 128 : 0) |
      (m.delegationEnabled ? 256 : 0)

    c.buffer.encode(state, m.id)
    c.buffer.encode(state, m.boardId)
    c.string.encode(state, m.from)
    c.string.encode(state, m.to)
    c.uint.encode(state, flags)

    if (m.label) c.string.encode(state, m.label)
    c.int.encode(state, m.updatedAt)
    if (m.amount) c.string.encode(state, m.amount)
    if (m.payment) c.int.encode(state, m.payment)
    if (m.document) c.int.encode(state, m.document)
    if (m.template) c.string.encode(state, m.template)
    if (m.customDoc) c.string.encode(state, m.customDoc)
    if (m.docName) c.string.encode(state, m.docName)
    if (m.txHash) c.string.encode(state, m.txHash)
    if (m.delegationEnabled) c.int.encode(state, m.delegationEnabled)
  },
  decode(state) {
    const r0 = c.buffer.decode(state)
    const r1 = c.buffer.decode(state)
    const r2 = c.string.decode(state)
    const r3 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      id: r0,
      boardId: r1,
      from: r2,
      to: r3,
      label: (flags & 1) !== 0 ? c.string.decode(state) : null,
      updatedAt: c.int.decode(state),
      amount: (flags & 2) !== 0 ? c.string.decode(state) : null,
      payment: (flags & 4) !== 0 ? c.int.decode(state) : 0,
      document: (flags & 8) !== 0 ? c.int.decode(state) : 0,
      template: (flags & 16) !== 0 ? c.string.decode(state) : null,
      customDoc: (flags & 32) !== 0 ? c.string.decode(state) : null,
      docName: (flags & 64) !== 0 ? c.string.decode(state) : null,
      txHash: (flags & 128) !== 0 ? c.string.decode(state) : null,
      delegationEnabled: (flags & 256) !== 0 ? c.int.decode(state) : 0
    }
  }
}

// @goji/chat-msg
const encoding5 = {
  preencode(state, m) {
    c.string.preencode(state, m.id)
    c.string.preencode(state, m.text)
    state.end++ // max flag is 2 so always one byte

    if (m.info) c.json.preencode(state, m.info)
    if (m.proof) c.buffer.preencode(state, m.proof)
  },
  encode(state, m) {
    const flags = (m.info ? 1 : 0) | (m.proof ? 2 : 0)

    c.string.encode(state, m.id)
    c.string.encode(state, m.text)
    c.uint.encode(state, flags)

    if (m.info) c.json.encode(state, m.info)
    if (m.proof) c.buffer.encode(state, m.proof)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      id: r0,
      text: r1,
      info: (flags & 1) !== 0 ? c.json.decode(state) : null,
      proof: (flags & 2) !== 0 ? c.buffer.decode(state) : null
    }
  }
}

// @goji/wallet
const encoding6 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.id)
    c.string.preencode(state, m.address)
    state.end++ // max flag is 16 so always one byte

    if (m.chainType) c.string.preencode(state, m.chainType)
    if (m.walletType) c.string.preencode(state, m.walletType)
    if (m.name) c.string.preencode(state, m.name)
    c.buffer.preencode(state, m.identityKey)
    if (m.proof) c.buffer.preencode(state, m.proof)
    c.int.preencode(state, m.createdAt)
    if (m.identityPublicKey) c.buffer.preencode(state, m.identityPublicKey)
  },
  encode(state, m) {
    const flags =
      (m.chainType ? 1 : 0) |
      (m.walletType ? 2 : 0) |
      (m.name ? 4 : 0) |
      (m.proof ? 8 : 0) |
      (m.identityPublicKey ? 16 : 0)

    c.buffer.encode(state, m.id)
    c.string.encode(state, m.address)
    c.uint.encode(state, flags)

    if (m.chainType) c.string.encode(state, m.chainType)
    if (m.walletType) c.string.encode(state, m.walletType)
    if (m.name) c.string.encode(state, m.name)
    c.buffer.encode(state, m.identityKey)
    if (m.proof) c.buffer.encode(state, m.proof)
    c.int.encode(state, m.createdAt)
    if (m.identityPublicKey) c.buffer.encode(state, m.identityPublicKey)
  },
  decode(state) {
    const r0 = c.buffer.decode(state)
    const r1 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      id: r0,
      address: r1,
      chainType: (flags & 1) !== 0 ? c.string.decode(state) : null,
      walletType: (flags & 2) !== 0 ? c.string.decode(state) : null,
      name: (flags & 4) !== 0 ? c.string.decode(state) : null,
      identityKey: c.buffer.decode(state),
      proof: (flags & 8) !== 0 ? c.buffer.decode(state) : null,
      createdAt: c.int.decode(state),
      identityPublicKey: (flags & 16) !== 0 ? c.buffer.decode(state) : null
    }
  }
}

// @goji/board-rename
const encoding7 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.id)
    c.string.preencode(state, m.name)
    c.int.preencode(state, m.at)
  },
  encode(state, m) {
    c.buffer.encode(state, m.id)
    c.string.encode(state, m.name)
    c.int.encode(state, m.at)
  },
  decode(state) {
    const r0 = c.buffer.decode(state)
    const r1 = c.string.decode(state)
    const r2 = c.int.decode(state)

    return {
      id: r0,
      name: r1,
      at: r2
    }
  }
}

// @goji/board-delete
const encoding8 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.id)
  },
  encode(state, m) {
    c.buffer.encode(state, m.id)
  },
  decode(state) {
    const r0 = c.buffer.decode(state)

    return {
      id: r0
    }
  }
}

// @goji/card-update
const encoding9 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.id)
    c.json.preencode(state, m.patch)
    c.int.preencode(state, m.at)
  },
  encode(state, m) {
    c.buffer.encode(state, m.id)
    c.json.encode(state, m.patch)
    c.int.encode(state, m.at)
  },
  decode(state) {
    const r0 = c.buffer.decode(state)
    const r1 = c.json.decode(state)
    const r2 = c.int.decode(state)

    return {
      id: r0,
      patch: r1,
      at: r2
    }
  }
}

// @goji/card-remove
const encoding10 = encoding8

// @goji/connection-add
const encoding11 = encoding4

// @goji/connection-remove
const encoding12 = encoding8

// @goji/connection-update
const encoding13 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.id)
    c.json.preencode(state, m.patch)
  },
  encode(state, m) {
    c.buffer.encode(state, m.id)
    c.json.encode(state, m.patch)
  },
  decode(state) {
    const r0 = c.buffer.decode(state)
    const r1 = c.json.decode(state)

    return {
      id: r0,
      patch: r1
    }
  }
}

// @goji/chats-remove
const encoding14 = {
  preencode(state, m) {
    c.json.preencode(state, m.ids)
  },
  encode(state, m) {
    c.json.encode(state, m.ids)
  },
  decode(state) {
    const r0 = c.json.decode(state)

    return {
      ids: r0
    }
  }
}

// @goji/wallet-remove
const encoding15 = encoding8

// @goji/identity
const encoding16 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.writerKey)
    c.string.preencode(state, m.displayName)
    state.end++ // max flag is 4 so always one byte

    if (m.role) c.string.preencode(state, m.role)
    if (m.assignedBy) c.buffer.preencode(state, m.assignedBy)
    if (m.assignedAt) c.int.preencode(state, m.assignedAt)
    c.int.preencode(state, m.updatedAt)
  },
  encode(state, m) {
    const flags = (m.role ? 1 : 0) | (m.assignedBy ? 2 : 0) | (m.assignedAt ? 4 : 0)

    c.buffer.encode(state, m.writerKey)
    c.string.encode(state, m.displayName)
    c.uint.encode(state, flags)

    if (m.role) c.string.encode(state, m.role)
    if (m.assignedBy) c.buffer.encode(state, m.assignedBy)
    if (m.assignedAt) c.int.encode(state, m.assignedAt)
    c.int.encode(state, m.updatedAt)
  },
  decode(state) {
    const r0 = c.buffer.decode(state)
    const r1 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      writerKey: r0,
      displayName: r1,
      role: (flags & 1) !== 0 ? c.string.decode(state) : null,
      assignedBy: (flags & 2) !== 0 ? c.buffer.decode(state) : null,
      assignedAt: (flags & 4) !== 0 ? c.int.decode(state) : 0,
      updatedAt: c.int.decode(state)
    }
  }
}

// @goji/flow-status
const encoding17 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.id)
    c.buffer.preencode(state, m.flowId)
    c.string.preencode(state, m.routeId)
    c.string.preencode(state, m.status)
    state.end++ // max flag is 8 so always one byte

    if (m.txHash) c.string.preencode(state, m.txHash)
    if (m.error) c.string.preencode(state, m.error)
    if (m.payslipHtml) c.string.preencode(state, m.payslipHtml)
    if (m.merkleRoot) c.string.preencode(state, m.merkleRoot)
    c.int.preencode(state, m.updatedAt)
  },
  encode(state, m) {
    const flags =
      (m.txHash ? 1 : 0) | (m.error ? 2 : 0) | (m.payslipHtml ? 4 : 0) | (m.merkleRoot ? 8 : 0)

    c.buffer.encode(state, m.id)
    c.buffer.encode(state, m.flowId)
    c.string.encode(state, m.routeId)
    c.string.encode(state, m.status)
    c.uint.encode(state, flags)

    if (m.txHash) c.string.encode(state, m.txHash)
    if (m.error) c.string.encode(state, m.error)
    if (m.payslipHtml) c.string.encode(state, m.payslipHtml)
    if (m.merkleRoot) c.string.encode(state, m.merkleRoot)
    c.int.encode(state, m.updatedAt)
  },
  decode(state) {
    const r0 = c.buffer.decode(state)
    const r1 = c.buffer.decode(state)
    const r2 = c.string.decode(state)
    const r3 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      id: r0,
      flowId: r1,
      routeId: r2,
      status: r3,
      txHash: (flags & 1) !== 0 ? c.string.decode(state) : null,
      error: (flags & 2) !== 0 ? c.string.decode(state) : null,
      payslipHtml: (flags & 4) !== 0 ? c.string.decode(state) : null,
      merkleRoot: (flags & 8) !== 0 ? c.string.decode(state) : null,
      updatedAt: c.int.decode(state)
    }
  }
}

// @goji/flow-status-remove
const encoding18 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.flowId)
  },
  encode(state, m) {
    c.buffer.encode(state, m.flowId)
  },
  decode(state) {
    const r0 = c.buffer.decode(state)

    return {
      flowId: r0
    }
  }
}

// @goji/template
const encoding19 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.id)
    c.string.preencode(state, m.name)
    state.end++ // max flag is 8 so always one byte

    if (m.companyName) c.string.preencode(state, m.companyName)
    if (m.fields) c.json.preencode(state, m.fields)
    c.string.preencode(state, m.html)
    if (m.isDefault) c.int.preencode(state, m.isDefault)
    if (m.createdBy) c.buffer.preencode(state, m.createdBy)
    c.int.preencode(state, m.createdAt)
    c.int.preencode(state, m.updatedAt)
  },
  encode(state, m) {
    const flags =
      (m.companyName ? 1 : 0) | (m.fields ? 2 : 0) | (m.isDefault ? 4 : 0) | (m.createdBy ? 8 : 0)

    c.buffer.encode(state, m.id)
    c.string.encode(state, m.name)
    c.uint.encode(state, flags)

    if (m.companyName) c.string.encode(state, m.companyName)
    if (m.fields) c.json.encode(state, m.fields)
    c.string.encode(state, m.html)
    if (m.isDefault) c.int.encode(state, m.isDefault)
    if (m.createdBy) c.buffer.encode(state, m.createdBy)
    c.int.encode(state, m.createdAt)
    c.int.encode(state, m.updatedAt)
  },
  decode(state) {
    const r0 = c.buffer.decode(state)
    const r1 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      id: r0,
      name: r1,
      companyName: (flags & 1) !== 0 ? c.string.decode(state) : null,
      fields: (flags & 2) !== 0 ? c.json.decode(state) : null,
      html: c.string.decode(state),
      isDefault: (flags & 4) !== 0 ? c.int.decode(state) : 0,
      createdBy: (flags & 8) !== 0 ? c.buffer.decode(state) : null,
      createdAt: c.int.decode(state),
      updatedAt: c.int.decode(state)
    }
  }
}

// @goji/template-remove
const encoding20 = encoding8

// @goji/receivable
const encoding21 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.id)
    c.string.preencode(state, m.tokenAddress)
    c.string.preencode(state, m.name)
    c.string.preencode(state, m.type)
    c.string.preencode(state, m.amount)
    c.string.preencode(state, m.interestRate)
    c.string.preencode(state, m.minInvestment)
    c.string.preencode(state, m.expiryDays)
    c.json.preencode(state, m.proofs)
    c.string.preencode(state, m.status)
    c.buffer.preencode(state, m.issuer)
    c.int.preencode(state, m.createdAt)
    c.int.preencode(state, m.updatedAt)
  },
  encode(state, m) {
    c.buffer.encode(state, m.id)
    c.string.encode(state, m.tokenAddress)
    c.string.encode(state, m.name)
    c.string.encode(state, m.type)
    c.string.encode(state, m.amount)
    c.string.encode(state, m.interestRate)
    c.string.encode(state, m.minInvestment)
    c.string.encode(state, m.expiryDays)
    c.json.encode(state, m.proofs)
    c.string.encode(state, m.status)
    c.buffer.encode(state, m.issuer)
    c.int.encode(state, m.createdAt)
    c.int.encode(state, m.updatedAt)
  },
  decode(state) {
    const r0 = c.buffer.decode(state)
    const r1 = c.string.decode(state)
    const r2 = c.string.decode(state)
    const r3 = c.string.decode(state)
    const r4 = c.string.decode(state)
    const r5 = c.string.decode(state)
    const r6 = c.string.decode(state)
    const r7 = c.string.decode(state)
    const r8 = c.json.decode(state)
    const r9 = c.string.decode(state)
    const r10 = c.buffer.decode(state)
    const r11 = c.int.decode(state)
    const r12 = c.int.decode(state)

    return {
      id: r0,
      tokenAddress: r1,
      name: r2,
      type: r3,
      amount: r4,
      interestRate: r5,
      minInvestment: r6,
      expiryDays: r7,
      proofs: r8,
      status: r9,
      issuer: r10,
      createdAt: r11,
      updatedAt: r12
    }
  }
}

// @goji/receivable-remove
const encoding22 = encoding8

function setVersion(v) {
  version = v
}

function encode(name, value, v = VERSION) {
  version = v
  return c.encode(getEncoding(name), value)
}

function decode(name, buffer, v = VERSION) {
  version = v
  return c.decode(getEncoding(name), buffer)
}

function getEnum(name) {
  switch (name) {
    default:
      throw new Error('Enum not found ' + name)
  }
}

function getEncoding(name) {
  switch (name) {
    case '@goji/writer':
      return encoding0
    case '@goji/invite':
      return encoding1
    case '@goji/board':
      return encoding2
    case '@goji/card':
      return encoding3
    case '@goji/connection':
      return encoding4
    case '@goji/chat-msg':
      return encoding5
    case '@goji/wallet':
      return encoding6
    case '@goji/board-rename':
      return encoding7
    case '@goji/board-delete':
      return encoding8
    case '@goji/card-update':
      return encoding9
    case '@goji/card-remove':
      return encoding10
    case '@goji/connection-add':
      return encoding11
    case '@goji/connection-remove':
      return encoding12
    case '@goji/connection-update':
      return encoding13
    case '@goji/chats-remove':
      return encoding14
    case '@goji/wallet-remove':
      return encoding15
    case '@goji/identity':
      return encoding16
    case '@goji/flow-status':
      return encoding17
    case '@goji/flow-status-remove':
      return encoding18
    case '@goji/template':
      return encoding19
    case '@goji/template-remove':
      return encoding20
    case '@goji/receivable':
      return encoding21
    case '@goji/receivable-remove':
      return encoding22
    default:
      throw new Error('Encoder not found ' + name)
  }
}

function getStruct(name, v = VERSION) {
  const enc = getEncoding(name)
  return {
    preencode(state, m) {
      version = v
      enc.preencode(state, m)
    },
    encode(state, m) {
      version = v
      enc.encode(state, m)
    },
    decode(state) {
      version = v
      return enc.decode(state)
    }
  }
}

const resolveStruct = getStruct // compat

module.exports = {
  resolveStruct,
  getStruct,
  getEnum,
  getEncoding,
  encode,
  decode,
  setVersion,
  version
}
