// This file is autogenerated by the hyperdb compiler
/* eslint-disable camelcase */

const { IndexEncoder, c, b4a } = require('hyperdb/runtime')
const { version, getEncoding, setVersion } = require('./messages.js')

const versions = { schema: version, db: 4 }

// '@goji/boards' collection key
const collection0_key = new IndexEncoder([
  IndexEncoder.BUFFER
], { prefix: 0 })

function collection0_indexify (record) {
  const a = record.id
  return a === undefined ? [] : [a]
}

// '@goji/boards' value encoding
const collection0_enc = getEncoding('@goji/board/hyperdb#0')

// '@goji/boards' reconstruction function
function collection0_reconstruct (schemaVersion, keyBuf, valueBuf) {
  const key = collection0_key.decode(keyBuf)
  setVersion(schemaVersion)
  const state = { start: 0, end: valueBuf.byteLength, buffer: valueBuf }
  const type = c.uint.decode(state)
  if (type !== 0) throw new Error('Unknown collection type: ' + type)
  collection0.decodedVersion = c.uint.decode(state)
  const record = collection0_enc.decode(state)
  record.id = key[0]
  return record
}
// '@goji/boards' key reconstruction function
function collection0_reconstruct_key (keyBuf) {
  const key = collection0_key.decode(keyBuf)
  return {
    id: key[0]
  }
}

// '@goji/boards'
const collection0 = {
  name: '@goji/boards',
  id: 0,
  version: 1,
  encodeKey (record) {
    const key = [record.id]
    return collection0_key.encode(key)
  },
  encodeKeyRange ({ gt, lt, gte, lte } = {}) {
    return collection0_key.encodeRange({
      gt: gt ? collection0_indexify(gt) : null,
      lt: lt ? collection0_indexify(lt) : null,
      gte: gte ? collection0_indexify(gte) : null,
      lte: lte ? collection0_indexify(lte) : null
    })
  },
  encodeValue (schemaVersion, collectionVersion, record) {
    setVersion(schemaVersion)
    const state = { start: 0, end: 2, buffer: null }
    collection0_enc.preencode(state, record)
    state.buffer = b4a.allocUnsafe(state.end)
    state.buffer[state.start++] = 0
    state.buffer[state.start++] = collectionVersion
    collection0_enc.encode(state, record)
    return state.buffer
  },
  trigger: null,
  reconstruct: collection0_reconstruct,
  reconstructKey: collection0_reconstruct_key,
  indexes: [],
  decodedVersion: 0
}

// '@goji/cards' collection key
const collection1_key = new IndexEncoder([
  IndexEncoder.BUFFER
], { prefix: 1 })

function collection1_indexify (record) {
  const a = record.id
  return a === undefined ? [] : [a]
}

// '@goji/cards' value encoding
const collection1_enc = getEncoding('@goji/card/hyperdb#1')

// '@goji/cards' reconstruction function
function collection1_reconstruct (schemaVersion, keyBuf, valueBuf) {
  const key = collection1_key.decode(keyBuf)
  setVersion(schemaVersion)
  const state = { start: 0, end: valueBuf.byteLength, buffer: valueBuf }
  const type = c.uint.decode(state)
  if (type !== 0) throw new Error('Unknown collection type: ' + type)
  collection1.decodedVersion = c.uint.decode(state)
  const record = collection1_enc.decode(state)
  record.id = key[0]
  return record
}
// '@goji/cards' key reconstruction function
function collection1_reconstruct_key (keyBuf) {
  const key = collection1_key.decode(keyBuf)
  return {
    id: key[0]
  }
}

// '@goji/cards'
const collection1 = {
  name: '@goji/cards',
  id: 1,
  version: 1,
  encodeKey (record) {
    const key = [record.id]
    return collection1_key.encode(key)
  },
  encodeKeyRange ({ gt, lt, gte, lte } = {}) {
    return collection1_key.encodeRange({
      gt: gt ? collection1_indexify(gt) : null,
      lt: lt ? collection1_indexify(lt) : null,
      gte: gte ? collection1_indexify(gte) : null,
      lte: lte ? collection1_indexify(lte) : null
    })
  },
  encodeValue (schemaVersion, collectionVersion, record) {
    setVersion(schemaVersion)
    const state = { start: 0, end: 2, buffer: null }
    collection1_enc.preencode(state, record)
    state.buffer = b4a.allocUnsafe(state.end)
    state.buffer[state.start++] = 0
    state.buffer[state.start++] = collectionVersion
    collection1_enc.encode(state, record)
    return state.buffer
  },
  trigger: null,
  reconstruct: collection1_reconstruct,
  reconstructKey: collection1_reconstruct_key,
  indexes: [],
  decodedVersion: 0
}

// '@goji/connections' collection key
const collection2_key = new IndexEncoder([
  IndexEncoder.BUFFER
], { prefix: 2 })

function collection2_indexify (record) {
  const a = record.id
  return a === undefined ? [] : [a]
}

// '@goji/connections' value encoding
const collection2_enc = getEncoding('@goji/connection/hyperdb#2')

// '@goji/connections' reconstruction function
function collection2_reconstruct (schemaVersion, keyBuf, valueBuf) {
  const key = collection2_key.decode(keyBuf)
  setVersion(schemaVersion)
  const state = { start: 0, end: valueBuf.byteLength, buffer: valueBuf }
  const type = c.uint.decode(state)
  if (type !== 0) throw new Error('Unknown collection type: ' + type)
  collection2.decodedVersion = c.uint.decode(state)
  const record = collection2_enc.decode(state)
  record.id = key[0]
  return record
}
// '@goji/connections' key reconstruction function
function collection2_reconstruct_key (keyBuf) {
  const key = collection2_key.decode(keyBuf)
  return {
    id: key[0]
  }
}

// '@goji/connections'
const collection2 = {
  name: '@goji/connections',
  id: 2,
  version: 1,
  encodeKey (record) {
    const key = [record.id]
    return collection2_key.encode(key)
  },
  encodeKeyRange ({ gt, lt, gte, lte } = {}) {
    return collection2_key.encodeRange({
      gt: gt ? collection2_indexify(gt) : null,
      lt: lt ? collection2_indexify(lt) : null,
      gte: gte ? collection2_indexify(gte) : null,
      lte: lte ? collection2_indexify(lte) : null
    })
  },
  encodeValue (schemaVersion, collectionVersion, record) {
    setVersion(schemaVersion)
    const state = { start: 0, end: 2, buffer: null }
    collection2_enc.preencode(state, record)
    state.buffer = b4a.allocUnsafe(state.end)
    state.buffer[state.start++] = 0
    state.buffer[state.start++] = collectionVersion
    collection2_enc.encode(state, record)
    return state.buffer
  },
  trigger: null,
  reconstruct: collection2_reconstruct,
  reconstructKey: collection2_reconstruct_key,
  indexes: [],
  decodedVersion: 0
}

// '@goji/chat' collection key
const collection3_key = new IndexEncoder([
  IndexEncoder.STRING
], { prefix: 3 })

function collection3_indexify (record) {
  const a = record.id
  return a === undefined ? [] : [a]
}

// '@goji/chat' value encoding
const collection3_enc = getEncoding('@goji/chat-msg/hyperdb#3')

// '@goji/chat' reconstruction function
function collection3_reconstruct (schemaVersion, keyBuf, valueBuf) {
  const key = collection3_key.decode(keyBuf)
  setVersion(schemaVersion)
  const state = { start: 0, end: valueBuf.byteLength, buffer: valueBuf }
  const type = c.uint.decode(state)
  if (type !== 0) throw new Error('Unknown collection type: ' + type)
  collection3.decodedVersion = c.uint.decode(state)
  const record = collection3_enc.decode(state)
  record.id = key[0]
  return record
}
// '@goji/chat' key reconstruction function
function collection3_reconstruct_key (keyBuf) {
  const key = collection3_key.decode(keyBuf)
  return {
    id: key[0]
  }
}

// '@goji/chat'
const collection3 = {
  name: '@goji/chat',
  id: 3,
  version: 1,
  encodeKey (record) {
    const key = [record.id]
    return collection3_key.encode(key)
  },
  encodeKeyRange ({ gt, lt, gte, lte } = {}) {
    return collection3_key.encodeRange({
      gt: gt ? collection3_indexify(gt) : null,
      lt: lt ? collection3_indexify(lt) : null,
      gte: gte ? collection3_indexify(gte) : null,
      lte: lte ? collection3_indexify(lte) : null
    })
  },
  encodeValue (schemaVersion, collectionVersion, record) {
    setVersion(schemaVersion)
    const state = { start: 0, end: 2, buffer: null }
    collection3_enc.preencode(state, record)
    state.buffer = b4a.allocUnsafe(state.end)
    state.buffer[state.start++] = 0
    state.buffer[state.start++] = collectionVersion
    collection3_enc.encode(state, record)
    return state.buffer
  },
  trigger: null,
  reconstruct: collection3_reconstruct,
  reconstructKey: collection3_reconstruct_key,
  indexes: [],
  decodedVersion: 0
}

// '@goji/invites' collection key
const collection4_key = new IndexEncoder([
  IndexEncoder.BUFFER
], { prefix: 4 })

function collection4_indexify (record) {
  const a = record.id
  return a === undefined ? [] : [a]
}

// '@goji/invites' value encoding
const collection4_enc = getEncoding('@goji/invite/hyperdb#4')

// '@goji/invites' reconstruction function
function collection4_reconstruct (schemaVersion, keyBuf, valueBuf) {
  const key = collection4_key.decode(keyBuf)
  setVersion(schemaVersion)
  const state = { start: 0, end: valueBuf.byteLength, buffer: valueBuf }
  const type = c.uint.decode(state)
  if (type !== 0) throw new Error('Unknown collection type: ' + type)
  collection4.decodedVersion = c.uint.decode(state)
  const record = collection4_enc.decode(state)
  record.id = key[0]
  return record
}
// '@goji/invites' key reconstruction function
function collection4_reconstruct_key (keyBuf) {
  const key = collection4_key.decode(keyBuf)
  return {
    id: key[0]
  }
}

// '@goji/invites'
const collection4 = {
  name: '@goji/invites',
  id: 4,
  version: 1,
  encodeKey (record) {
    const key = [record.id]
    return collection4_key.encode(key)
  },
  encodeKeyRange ({ gt, lt, gte, lte } = {}) {
    return collection4_key.encodeRange({
      gt: gt ? collection4_indexify(gt) : null,
      lt: lt ? collection4_indexify(lt) : null,
      gte: gte ? collection4_indexify(gte) : null,
      lte: lte ? collection4_indexify(lte) : null
    })
  },
  encodeValue (schemaVersion, collectionVersion, record) {
    setVersion(schemaVersion)
    const state = { start: 0, end: 2, buffer: null }
    collection4_enc.preencode(state, record)
    state.buffer = b4a.allocUnsafe(state.end)
    state.buffer[state.start++] = 0
    state.buffer[state.start++] = collectionVersion
    collection4_enc.encode(state, record)
    return state.buffer
  },
  trigger: null,
  reconstruct: collection4_reconstruct,
  reconstructKey: collection4_reconstruct_key,
  indexes: [],
  decodedVersion: 0
}

// '@goji/identity' collection key
const collection5_key = new IndexEncoder([
  IndexEncoder.BUFFER
], { prefix: 5 })

function collection5_indexify (record) {
  const a = record.writerKey
  return a === undefined ? [] : [a]
}

// '@goji/identity' value encoding
const collection5_enc = getEncoding('@goji/identity/hyperdb#5')

// '@goji/identity' reconstruction function
function collection5_reconstruct (schemaVersion, keyBuf, valueBuf) {
  const key = collection5_key.decode(keyBuf)
  setVersion(schemaVersion)
  const state = { start: 0, end: valueBuf.byteLength, buffer: valueBuf }
  const type = c.uint.decode(state)
  if (type !== 0) throw new Error('Unknown collection type: ' + type)
  collection5.decodedVersion = c.uint.decode(state)
  const record = collection5_enc.decode(state)
  record.writerKey = key[0]
  return record
}
// '@goji/identity' key reconstruction function
function collection5_reconstruct_key (keyBuf) {
  const key = collection5_key.decode(keyBuf)
  return {
    writerKey: key[0]
  }
}

// '@goji/identity'
const collection5 = {
  name: '@goji/identity',
  id: 5,
  version: 1,
  encodeKey (record) {
    const key = [record.writerKey]
    return collection5_key.encode(key)
  },
  encodeKeyRange ({ gt, lt, gte, lte } = {}) {
    return collection5_key.encodeRange({
      gt: gt ? collection5_indexify(gt) : null,
      lt: lt ? collection5_indexify(lt) : null,
      gte: gte ? collection5_indexify(gte) : null,
      lte: lte ? collection5_indexify(lte) : null
    })
  },
  encodeValue (schemaVersion, collectionVersion, record) {
    setVersion(schemaVersion)
    const state = { start: 0, end: 2, buffer: null }
    collection5_enc.preencode(state, record)
    state.buffer = b4a.allocUnsafe(state.end)
    state.buffer[state.start++] = 0
    state.buffer[state.start++] = collectionVersion
    collection5_enc.encode(state, record)
    return state.buffer
  },
  trigger: null,
  reconstruct: collection5_reconstruct,
  reconstructKey: collection5_reconstruct_key,
  indexes: [],
  decodedVersion: 0
}

// '@goji/wallets' collection key
const collection6_key = new IndexEncoder([
  IndexEncoder.BUFFER
], { prefix: 6 })

function collection6_indexify (record) {
  const a = record.id
  return a === undefined ? [] : [a]
}

// '@goji/wallets' value encoding
const collection6_enc = getEncoding('@goji/wallet/hyperdb#6')

// '@goji/wallets' reconstruction function
function collection6_reconstruct (schemaVersion, keyBuf, valueBuf) {
  const key = collection6_key.decode(keyBuf)
  setVersion(schemaVersion)
  const state = { start: 0, end: valueBuf.byteLength, buffer: valueBuf }
  const type = c.uint.decode(state)
  if (type !== 0) throw new Error('Unknown collection type: ' + type)
  collection6.decodedVersion = c.uint.decode(state)
  const record = collection6_enc.decode(state)
  record.id = key[0]
  return record
}
// '@goji/wallets' key reconstruction function
function collection6_reconstruct_key (keyBuf) {
  const key = collection6_key.decode(keyBuf)
  return {
    id: key[0]
  }
}

// '@goji/wallets'
const collection6 = {
  name: '@goji/wallets',
  id: 6,
  version: 1,
  encodeKey (record) {
    const key = [record.id]
    return collection6_key.encode(key)
  },
  encodeKeyRange ({ gt, lt, gte, lte } = {}) {
    return collection6_key.encodeRange({
      gt: gt ? collection6_indexify(gt) : null,
      lt: lt ? collection6_indexify(lt) : null,
      gte: gte ? collection6_indexify(gte) : null,
      lte: lte ? collection6_indexify(lte) : null
    })
  },
  encodeValue (schemaVersion, collectionVersion, record) {
    setVersion(schemaVersion)
    const state = { start: 0, end: 2, buffer: null }
    collection6_enc.preencode(state, record)
    state.buffer = b4a.allocUnsafe(state.end)
    state.buffer[state.start++] = 0
    state.buffer[state.start++] = collectionVersion
    collection6_enc.encode(state, record)
    return state.buffer
  },
  trigger: null,
  reconstruct: collection6_reconstruct,
  reconstructKey: collection6_reconstruct_key,
  indexes: [],
  decodedVersion: 0
}

// '@goji/flowStatuses' collection key
const collection7_key = new IndexEncoder([
  IndexEncoder.BUFFER
], { prefix: 7 })

function collection7_indexify (record) {
  const a = record.id
  return a === undefined ? [] : [a]
}

// '@goji/flowStatuses' value encoding
const collection7_enc = getEncoding('@goji/flow-status/hyperdb#7')

// '@goji/flowStatuses' reconstruction function
function collection7_reconstruct (schemaVersion, keyBuf, valueBuf) {
  const key = collection7_key.decode(keyBuf)
  setVersion(schemaVersion)
  const state = { start: 0, end: valueBuf.byteLength, buffer: valueBuf }
  const type = c.uint.decode(state)
  if (type !== 0) throw new Error('Unknown collection type: ' + type)
  collection7.decodedVersion = c.uint.decode(state)
  const record = collection7_enc.decode(state)
  record.id = key[0]
  return record
}
// '@goji/flowStatuses' key reconstruction function
function collection7_reconstruct_key (keyBuf) {
  const key = collection7_key.decode(keyBuf)
  return {
    id: key[0]
  }
}

// '@goji/flowStatuses'
const collection7 = {
  name: '@goji/flowStatuses',
  id: 7,
  version: 1,
  encodeKey (record) {
    const key = [record.id]
    return collection7_key.encode(key)
  },
  encodeKeyRange ({ gt, lt, gte, lte } = {}) {
    return collection7_key.encodeRange({
      gt: gt ? collection7_indexify(gt) : null,
      lt: lt ? collection7_indexify(lt) : null,
      gte: gte ? collection7_indexify(gte) : null,
      lte: lte ? collection7_indexify(lte) : null
    })
  },
  encodeValue (schemaVersion, collectionVersion, record) {
    setVersion(schemaVersion)
    const state = { start: 0, end: 2, buffer: null }
    collection7_enc.preencode(state, record)
    state.buffer = b4a.allocUnsafe(state.end)
    state.buffer[state.start++] = 0
    state.buffer[state.start++] = collectionVersion
    collection7_enc.encode(state, record)
    return state.buffer
  },
  trigger: null,
  reconstruct: collection7_reconstruct,
  reconstructKey: collection7_reconstruct_key,
  indexes: [],
  decodedVersion: 0
}

// '@goji/templates' collection key
const collection8_key = new IndexEncoder([
  IndexEncoder.BUFFER
], { prefix: 8 })

function collection8_indexify (record) {
  const a = record.id
  return a === undefined ? [] : [a]
}

// '@goji/templates' value encoding
const collection8_enc = getEncoding('@goji/template/hyperdb#8')

// '@goji/templates' reconstruction function
function collection8_reconstruct (schemaVersion, keyBuf, valueBuf) {
  const key = collection8_key.decode(keyBuf)
  setVersion(schemaVersion)
  const state = { start: 0, end: valueBuf.byteLength, buffer: valueBuf }
  const type = c.uint.decode(state)
  if (type !== 0) throw new Error('Unknown collection type: ' + type)
  collection8.decodedVersion = c.uint.decode(state)
  const record = collection8_enc.decode(state)
  record.id = key[0]
  return record
}
// '@goji/templates' key reconstruction function
function collection8_reconstruct_key (keyBuf) {
  const key = collection8_key.decode(keyBuf)
  return {
    id: key[0]
  }
}

// '@goji/templates'
const collection8 = {
  name: '@goji/templates',
  id: 8,
  version: 1,
  encodeKey (record) {
    const key = [record.id]
    return collection8_key.encode(key)
  },
  encodeKeyRange ({ gt, lt, gte, lte } = {}) {
    return collection8_key.encodeRange({
      gt: gt ? collection8_indexify(gt) : null,
      lt: lt ? collection8_indexify(lt) : null,
      gte: gte ? collection8_indexify(gte) : null,
      lte: lte ? collection8_indexify(lte) : null
    })
  },
  encodeValue (schemaVersion, collectionVersion, record) {
    setVersion(schemaVersion)
    const state = { start: 0, end: 2, buffer: null }
    collection8_enc.preencode(state, record)
    state.buffer = b4a.allocUnsafe(state.end)
    state.buffer[state.start++] = 0
    state.buffer[state.start++] = collectionVersion
    collection8_enc.encode(state, record)
    return state.buffer
  },
  trigger: null,
  reconstruct: collection8_reconstruct,
  reconstructKey: collection8_reconstruct_key,
  indexes: [],
  decodedVersion: 0
}

// '@goji/receivables' collection key
const collection9_key = new IndexEncoder([
  IndexEncoder.BUFFER
], { prefix: 9 })

function collection9_indexify (record) {
  const a = record.id
  return a === undefined ? [] : [a]
}

// '@goji/receivables' value encoding
const collection9_enc = getEncoding('@goji/receivable/hyperdb#9')

// '@goji/receivables' reconstruction function
function collection9_reconstruct (schemaVersion, keyBuf, valueBuf) {
  const key = collection9_key.decode(keyBuf)
  setVersion(schemaVersion)
  const state = { start: 0, end: valueBuf.byteLength, buffer: valueBuf }
  const type = c.uint.decode(state)
  if (type !== 0) throw new Error('Unknown collection type: ' + type)
  collection9.decodedVersion = c.uint.decode(state)
  const record = collection9_enc.decode(state)
  record.id = key[0]
  return record
}
// '@goji/receivables' key reconstruction function
function collection9_reconstruct_key (keyBuf) {
  const key = collection9_key.decode(keyBuf)
  return {
    id: key[0]
  }
}

// '@goji/receivables'
const collection9 = {
  name: '@goji/receivables',
  id: 9,
  version: 2,
  encodeKey (record) {
    const key = [record.id]
    return collection9_key.encode(key)
  },
  encodeKeyRange ({ gt, lt, gte, lte } = {}) {
    return collection9_key.encodeRange({
      gt: gt ? collection9_indexify(gt) : null,
      lt: lt ? collection9_indexify(lt) : null,
      gte: gte ? collection9_indexify(gte) : null,
      lte: lte ? collection9_indexify(lte) : null
    })
  },
  encodeValue (schemaVersion, collectionVersion, record) {
    setVersion(schemaVersion)
    const state = { start: 0, end: 2, buffer: null }
    collection9_enc.preencode(state, record)
    state.buffer = b4a.allocUnsafe(state.end)
    state.buffer[state.start++] = 0
    state.buffer[state.start++] = collectionVersion
    collection9_enc.encode(state, record)
    return state.buffer
  },
  trigger: null,
  reconstruct: collection9_reconstruct,
  reconstructKey: collection9_reconstruct_key,
  indexes: [],
  decodedVersion: 0
}

// '@goji/knowledgeDocuments' collection key
const collection10_key = new IndexEncoder([
  IndexEncoder.STRING
], { prefix: 10 })

function collection10_indexify (record) {
  const a = record.id
  return a === undefined ? [] : [a]
}

// '@goji/knowledgeDocuments' value encoding
const collection10_enc = getEncoding('@goji/knowledge-document/hyperdb#10')

// '@goji/knowledgeDocuments' reconstruction function
function collection10_reconstruct (schemaVersion, keyBuf, valueBuf) {
  const key = collection10_key.decode(keyBuf)
  setVersion(schemaVersion)
  const state = { start: 0, end: valueBuf.byteLength, buffer: valueBuf }
  const type = c.uint.decode(state)
  if (type !== 0) throw new Error('Unknown collection type: ' + type)
  collection10.decodedVersion = c.uint.decode(state)
  const record = collection10_enc.decode(state)
  record.id = key[0]
  return record
}
// '@goji/knowledgeDocuments' key reconstruction function
function collection10_reconstruct_key (keyBuf) {
  const key = collection10_key.decode(keyBuf)
  return {
    id: key[0]
  }
}

// '@goji/knowledgeDocuments'
const collection10 = {
  name: '@goji/knowledgeDocuments',
  id: 10,
  version: 3,
  encodeKey (record) {
    const key = [record.id]
    return collection10_key.encode(key)
  },
  encodeKeyRange ({ gt, lt, gte, lte } = {}) {
    return collection10_key.encodeRange({
      gt: gt ? collection10_indexify(gt) : null,
      lt: lt ? collection10_indexify(lt) : null,
      gte: gte ? collection10_indexify(gte) : null,
      lte: lte ? collection10_indexify(lte) : null
    })
  },
  encodeValue (schemaVersion, collectionVersion, record) {
    setVersion(schemaVersion)
    const state = { start: 0, end: 2, buffer: null }
    collection10_enc.preencode(state, record)
    state.buffer = b4a.allocUnsafe(state.end)
    state.buffer[state.start++] = 0
    state.buffer[state.start++] = collectionVersion
    collection10_enc.encode(state, record)
    return state.buffer
  },
  trigger: null,
  reconstruct: collection10_reconstruct,
  reconstructKey: collection10_reconstruct_key,
  indexes: [],
  decodedVersion: 0
}

// '@goji/ragSearches' collection key
const collection11_key = new IndexEncoder([
  IndexEncoder.STRING
], { prefix: 11 })

function collection11_indexify (record) {
  const a = record.requestId
  return a === undefined ? [] : [a]
}

// '@goji/ragSearches' value encoding
const collection11_enc = getEncoding('@goji/rag-search/hyperdb#11')

// '@goji/ragSearches' reconstruction function
function collection11_reconstruct (schemaVersion, keyBuf, valueBuf) {
  const key = collection11_key.decode(keyBuf)
  setVersion(schemaVersion)
  const state = { start: 0, end: valueBuf.byteLength, buffer: valueBuf }
  const type = c.uint.decode(state)
  if (type !== 0) throw new Error('Unknown collection type: ' + type)
  collection11.decodedVersion = c.uint.decode(state)
  const record = collection11_enc.decode(state)
  record.requestId = key[0]
  return record
}
// '@goji/ragSearches' key reconstruction function
function collection11_reconstruct_key (keyBuf) {
  const key = collection11_key.decode(keyBuf)
  return {
    requestId: key[0]
  }
}

// '@goji/ragSearches'
const collection11 = {
  name: '@goji/ragSearches',
  id: 11,
  version: 3,
  encodeKey (record) {
    const key = [record.requestId]
    return collection11_key.encode(key)
  },
  encodeKeyRange ({ gt, lt, gte, lte } = {}) {
    return collection11_key.encodeRange({
      gt: gt ? collection11_indexify(gt) : null,
      lt: lt ? collection11_indexify(lt) : null,
      gte: gte ? collection11_indexify(gte) : null,
      lte: lte ? collection11_indexify(lte) : null
    })
  },
  encodeValue (schemaVersion, collectionVersion, record) {
    setVersion(schemaVersion)
    const state = { start: 0, end: 2, buffer: null }
    collection11_enc.preencode(state, record)
    state.buffer = b4a.allocUnsafe(state.end)
    state.buffer[state.start++] = 0
    state.buffer[state.start++] = collectionVersion
    collection11_enc.encode(state, record)
    return state.buffer
  },
  trigger: null,
  reconstruct: collection11_reconstruct,
  reconstructKey: collection11_reconstruct_key,
  indexes: [],
  decodedVersion: 0
}

// '@goji/ragSearchResults' collection key
const collection12_key = new IndexEncoder([
  IndexEncoder.STRING
], { prefix: 12 })

function collection12_indexify (record) {
  const a = record.requestId
  return a === undefined ? [] : [a]
}

// '@goji/ragSearchResults' value encoding
const collection12_enc = getEncoding('@goji/rag-search-result/hyperdb#12')

// '@goji/ragSearchResults' reconstruction function
function collection12_reconstruct (schemaVersion, keyBuf, valueBuf) {
  const key = collection12_key.decode(keyBuf)
  setVersion(schemaVersion)
  const state = { start: 0, end: valueBuf.byteLength, buffer: valueBuf }
  const type = c.uint.decode(state)
  if (type !== 0) throw new Error('Unknown collection type: ' + type)
  collection12.decodedVersion = c.uint.decode(state)
  const record = collection12_enc.decode(state)
  record.requestId = key[0]
  return record
}
// '@goji/ragSearchResults' key reconstruction function
function collection12_reconstruct_key (keyBuf) {
  const key = collection12_key.decode(keyBuf)
  return {
    requestId: key[0]
  }
}

// '@goji/ragSearchResults'
const collection12 = {
  name: '@goji/ragSearchResults',
  id: 12,
  version: 3,
  encodeKey (record) {
    const key = [record.requestId]
    return collection12_key.encode(key)
  },
  encodeKeyRange ({ gt, lt, gte, lte } = {}) {
    return collection12_key.encodeRange({
      gt: gt ? collection12_indexify(gt) : null,
      lt: lt ? collection12_indexify(lt) : null,
      gte: gte ? collection12_indexify(gte) : null,
      lte: lte ? collection12_indexify(lte) : null
    })
  },
  encodeValue (schemaVersion, collectionVersion, record) {
    setVersion(schemaVersion)
    const state = { start: 0, end: 2, buffer: null }
    collection12_enc.preencode(state, record)
    state.buffer = b4a.allocUnsafe(state.end)
    state.buffer[state.start++] = 0
    state.buffer[state.start++] = collectionVersion
    collection12_enc.encode(state, record)
    return state.buffer
  },
  trigger: null,
  reconstruct: collection12_reconstruct,
  reconstructKey: collection12_reconstruct_key,
  indexes: [],
  decodedVersion: 0
}

// '@goji/companyProfiles' collection key
const collection13_key = new IndexEncoder([
  IndexEncoder.BUFFER
], { prefix: 13 })

function collection13_indexify (record) {
  const a = record.id
  return a === undefined ? [] : [a]
}

// '@goji/companyProfiles' value encoding
const collection13_enc = getEncoding('@goji/company-profile/hyperdb#13')

// '@goji/companyProfiles' reconstruction function
function collection13_reconstruct (schemaVersion, keyBuf, valueBuf) {
  const key = collection13_key.decode(keyBuf)
  setVersion(schemaVersion)
  const state = { start: 0, end: valueBuf.byteLength, buffer: valueBuf }
  const type = c.uint.decode(state)
  if (type !== 0) throw new Error('Unknown collection type: ' + type)
  collection13.decodedVersion = c.uint.decode(state)
  const record = collection13_enc.decode(state)
  record.id = key[0]
  return record
}
// '@goji/companyProfiles' key reconstruction function
function collection13_reconstruct_key (keyBuf) {
  const key = collection13_key.decode(keyBuf)
  return {
    id: key[0]
  }
}

// '@goji/companyProfiles'
const collection13 = {
  name: '@goji/companyProfiles',
  id: 13,
  version: 4,
  encodeKey (record) {
    const key = [record.id]
    return collection13_key.encode(key)
  },
  encodeKeyRange ({ gt, lt, gte, lte } = {}) {
    return collection13_key.encodeRange({
      gt: gt ? collection13_indexify(gt) : null,
      lt: lt ? collection13_indexify(lt) : null,
      gte: gte ? collection13_indexify(gte) : null,
      lte: lte ? collection13_indexify(lte) : null
    })
  },
  encodeValue (schemaVersion, collectionVersion, record) {
    setVersion(schemaVersion)
    const state = { start: 0, end: 2, buffer: null }
    collection13_enc.preencode(state, record)
    state.buffer = b4a.allocUnsafe(state.end)
    state.buffer[state.start++] = 0
    state.buffer[state.start++] = collectionVersion
    collection13_enc.encode(state, record)
    return state.buffer
  },
  trigger: null,
  reconstruct: collection13_reconstruct,
  reconstructKey: collection13_reconstruct_key,
  indexes: [],
  decodedVersion: 0
}

const collections = [
  collection0,
  collection1,
  collection2,
  collection3,
  collection4,
  collection5,
  collection6,
  collection7,
  collection8,
  collection9,
  collection10,
  collection11,
  collection12,
  collection13
]

const indexes = [
]

module.exports = { versions, collections, indexes, resolveCollection, resolveIndex }

function resolveCollection (name) {
  switch (name) {
    case '@goji/boards': return collection0
    case '@goji/cards': return collection1
    case '@goji/connections': return collection2
    case '@goji/chat': return collection3
    case '@goji/invites': return collection4
    case '@goji/identity': return collection5
    case '@goji/wallets': return collection6
    case '@goji/flowStatuses': return collection7
    case '@goji/templates': return collection8
    case '@goji/receivables': return collection9
    case '@goji/knowledgeDocuments': return collection10
    case '@goji/ragSearches': return collection11
    case '@goji/ragSearchResults': return collection12
    case '@goji/companyProfiles': return collection13
    default: return null
  }
}

function resolveIndex (name) {
  switch (name) {
    default: return null
  }
}
