// This file is autogenerated by the hyperdb compiler
/* eslint-disable camelcase */

const { IndexEncoder, c, b4a } = require('hyperdb/runtime')
const { version, getEncoding, setVersion } = require('./messages.js')

const versions = { schema: version, db: 1 }

// '@goji/boards' collection key
const collection0_key = new IndexEncoder([
  IndexEncoder.BUFFER
], { prefix: 0 })

function collection0_indexify (record) {
  const a = record.id
  return a === undefined ? [] : [a]
}

// '@goji/boards' value encoding
const collection0_enc = getEncoding('@goji/board/hyperdb#0')

// '@goji/boards' reconstruction function
function collection0_reconstruct (schemaVersion, keyBuf, valueBuf) {
  const key = collection0_key.decode(keyBuf)
  setVersion(schemaVersion)
  const state = { start: 0, end: valueBuf.byteLength, buffer: valueBuf }
  const type = c.uint.decode(state)
  if (type !== 0) throw new Error('Unknown collection type: ' + type)
  collection0.decodedVersion = c.uint.decode(state)
  const record = collection0_enc.decode(state)
  record.id = key[0]
  return record
}
// '@goji/boards' key reconstruction function
function collection0_reconstruct_key (keyBuf) {
  const key = collection0_key.decode(keyBuf)
  return {
    id: key[0]
  }
}

// '@goji/boards'
const collection0 = {
  name: '@goji/boards',
  id: 0,
  version: 1,
  encodeKey (record) {
    const key = [record.id]
    return collection0_key.encode(key)
  },
  encodeKeyRange ({ gt, lt, gte, lte } = {}) {
    return collection0_key.encodeRange({
      gt: gt ? collection0_indexify(gt) : null,
      lt: lt ? collection0_indexify(lt) : null,
      gte: gte ? collection0_indexify(gte) : null,
      lte: lte ? collection0_indexify(lte) : null
    })
  },
  encodeValue (schemaVersion, collectionVersion, record) {
    setVersion(schemaVersion)
    const state = { start: 0, end: 2, buffer: null }
    collection0_enc.preencode(state, record)
    state.buffer = b4a.allocUnsafe(state.end)
    state.buffer[state.start++] = 0
    state.buffer[state.start++] = collectionVersion
    collection0_enc.encode(state, record)
    return state.buffer
  },
  trigger: null,
  reconstruct: collection0_reconstruct,
  reconstructKey: collection0_reconstruct_key,
  indexes: [],
  decodedVersion: 0
}

// '@goji/cards' collection key
const collection1_key = new IndexEncoder([
  IndexEncoder.BUFFER
], { prefix: 1 })

function collection1_indexify (record) {
  const a = record.id
  return a === undefined ? [] : [a]
}

// '@goji/cards' value encoding
const collection1_enc = getEncoding('@goji/card/hyperdb#1')

// '@goji/cards' reconstruction function
function collection1_reconstruct (schemaVersion, keyBuf, valueBuf) {
  const key = collection1_key.decode(keyBuf)
  setVersion(schemaVersion)
  const state = { start: 0, end: valueBuf.byteLength, buffer: valueBuf }
  const type = c.uint.decode(state)
  if (type !== 0) throw new Error('Unknown collection type: ' + type)
  collection1.decodedVersion = c.uint.decode(state)
  const record = collection1_enc.decode(state)
  record.id = key[0]
  return record
}
// '@goji/cards' key reconstruction function
function collection1_reconstruct_key (keyBuf) {
  const key = collection1_key.decode(keyBuf)
  return {
    id: key[0]
  }
}

// '@goji/cards'
const collection1 = {
  name: '@goji/cards',
  id: 1,
  version: 1,
  encodeKey (record) {
    const key = [record.id]
    return collection1_key.encode(key)
  },
  encodeKeyRange ({ gt, lt, gte, lte } = {}) {
    return collection1_key.encodeRange({
      gt: gt ? collection1_indexify(gt) : null,
      lt: lt ? collection1_indexify(lt) : null,
      gte: gte ? collection1_indexify(gte) : null,
      lte: lte ? collection1_indexify(lte) : null
    })
  },
  encodeValue (schemaVersion, collectionVersion, record) {
    setVersion(schemaVersion)
    const state = { start: 0, end: 2, buffer: null }
    collection1_enc.preencode(state, record)
    state.buffer = b4a.allocUnsafe(state.end)
    state.buffer[state.start++] = 0
    state.buffer[state.start++] = collectionVersion
    collection1_enc.encode(state, record)
    return state.buffer
  },
  trigger: null,
  reconstruct: collection1_reconstruct,
  reconstructKey: collection1_reconstruct_key,
  indexes: [],
  decodedVersion: 0
}

// '@goji/connections' collection key
const collection2_key = new IndexEncoder([
  IndexEncoder.BUFFER
], { prefix: 2 })

function collection2_indexify (record) {
  const a = record.id
  return a === undefined ? [] : [a]
}

// '@goji/connections' value encoding
const collection2_enc = getEncoding('@goji/connection/hyperdb#2')

// '@goji/connections' reconstruction function
function collection2_reconstruct (schemaVersion, keyBuf, valueBuf) {
  const key = collection2_key.decode(keyBuf)
  setVersion(schemaVersion)
  const state = { start: 0, end: valueBuf.byteLength, buffer: valueBuf }
  const type = c.uint.decode(state)
  if (type !== 0) throw new Error('Unknown collection type: ' + type)
  collection2.decodedVersion = c.uint.decode(state)
  const record = collection2_enc.decode(state)
  record.id = key[0]
  return record
}
// '@goji/connections' key reconstruction function
function collection2_reconstruct_key (keyBuf) {
  const key = collection2_key.decode(keyBuf)
  return {
    id: key[0]
  }
}

// '@goji/connections'
const collection2 = {
  name: '@goji/connections',
  id: 2,
  version: 1,
  encodeKey (record) {
    const key = [record.id]
    return collection2_key.encode(key)
  },
  encodeKeyRange ({ gt, lt, gte, lte } = {}) {
    return collection2_key.encodeRange({
      gt: gt ? collection2_indexify(gt) : null,
      lt: lt ? collection2_indexify(lt) : null,
      gte: gte ? collection2_indexify(gte) : null,
      lte: lte ? collection2_indexify(lte) : null
    })
  },
  encodeValue (schemaVersion, collectionVersion, record) {
    setVersion(schemaVersion)
    const state = { start: 0, end: 2, buffer: null }
    collection2_enc.preencode(state, record)
    state.buffer = b4a.allocUnsafe(state.end)
    state.buffer[state.start++] = 0
    state.buffer[state.start++] = collectionVersion
    collection2_enc.encode(state, record)
    return state.buffer
  },
  trigger: null,
  reconstruct: collection2_reconstruct,
  reconstructKey: collection2_reconstruct_key,
  indexes: [],
  decodedVersion: 0
}

// '@goji/chat' collection key
const collection3_key = new IndexEncoder([
  IndexEncoder.STRING
], { prefix: 3 })

function collection3_indexify (record) {
  const a = record.id
  return a === undefined ? [] : [a]
}

// '@goji/chat' value encoding
const collection3_enc = getEncoding('@goji/chat-msg/hyperdb#3')

// '@goji/chat' reconstruction function
function collection3_reconstruct (schemaVersion, keyBuf, valueBuf) {
  const key = collection3_key.decode(keyBuf)
  setVersion(schemaVersion)
  const state = { start: 0, end: valueBuf.byteLength, buffer: valueBuf }
  const type = c.uint.decode(state)
  if (type !== 0) throw new Error('Unknown collection type: ' + type)
  collection3.decodedVersion = c.uint.decode(state)
  const record = collection3_enc.decode(state)
  record.id = key[0]
  return record
}
// '@goji/chat' key reconstruction function
function collection3_reconstruct_key (keyBuf) {
  const key = collection3_key.decode(keyBuf)
  return {
    id: key[0]
  }
}

// '@goji/chat'
const collection3 = {
  name: '@goji/chat',
  id: 3,
  version: 1,
  encodeKey (record) {
    const key = [record.id]
    return collection3_key.encode(key)
  },
  encodeKeyRange ({ gt, lt, gte, lte } = {}) {
    return collection3_key.encodeRange({
      gt: gt ? collection3_indexify(gt) : null,
      lt: lt ? collection3_indexify(lt) : null,
      gte: gte ? collection3_indexify(gte) : null,
      lte: lte ? collection3_indexify(lte) : null
    })
  },
  encodeValue (schemaVersion, collectionVersion, record) {
    setVersion(schemaVersion)
    const state = { start: 0, end: 2, buffer: null }
    collection3_enc.preencode(state, record)
    state.buffer = b4a.allocUnsafe(state.end)
    state.buffer[state.start++] = 0
    state.buffer[state.start++] = collectionVersion
    collection3_enc.encode(state, record)
    return state.buffer
  },
  trigger: null,
  reconstruct: collection3_reconstruct,
  reconstructKey: collection3_reconstruct_key,
  indexes: [],
  decodedVersion: 0
}

// '@goji/invites' collection key
const collection4_key = new IndexEncoder([
  IndexEncoder.BUFFER
], { prefix: 4 })

function collection4_indexify (record) {
  const a = record.id
  return a === undefined ? [] : [a]
}

// '@goji/invites' value encoding
const collection4_enc = getEncoding('@goji/invite/hyperdb#4')

// '@goji/invites' reconstruction function
function collection4_reconstruct (schemaVersion, keyBuf, valueBuf) {
  const key = collection4_key.decode(keyBuf)
  setVersion(schemaVersion)
  const state = { start: 0, end: valueBuf.byteLength, buffer: valueBuf }
  const type = c.uint.decode(state)
  if (type !== 0) throw new Error('Unknown collection type: ' + type)
  collection4.decodedVersion = c.uint.decode(state)
  const record = collection4_enc.decode(state)
  record.id = key[0]
  return record
}
// '@goji/invites' key reconstruction function
function collection4_reconstruct_key (keyBuf) {
  const key = collection4_key.decode(keyBuf)
  return {
    id: key[0]
  }
}

// '@goji/invites'
const collection4 = {
  name: '@goji/invites',
  id: 4,
  version: 1,
  encodeKey (record) {
    const key = [record.id]
    return collection4_key.encode(key)
  },
  encodeKeyRange ({ gt, lt, gte, lte } = {}) {
    return collection4_key.encodeRange({
      gt: gt ? collection4_indexify(gt) : null,
      lt: lt ? collection4_indexify(lt) : null,
      gte: gte ? collection4_indexify(gte) : null,
      lte: lte ? collection4_indexify(lte) : null
    })
  },
  encodeValue (schemaVersion, collectionVersion, record) {
    setVersion(schemaVersion)
    const state = { start: 0, end: 2, buffer: null }
    collection4_enc.preencode(state, record)
    state.buffer = b4a.allocUnsafe(state.end)
    state.buffer[state.start++] = 0
    state.buffer[state.start++] = collectionVersion
    collection4_enc.encode(state, record)
    return state.buffer
  },
  trigger: null,
  reconstruct: collection4_reconstruct,
  reconstructKey: collection4_reconstruct_key,
  indexes: [],
  decodedVersion: 0
}

// '@goji/identity' collection key
const collection5_key = new IndexEncoder([
  IndexEncoder.BUFFER
], { prefix: 5 })

function collection5_indexify (record) {
  const a = record.writerKey
  return a === undefined ? [] : [a]
}

// '@goji/identity' value encoding
const collection5_enc = getEncoding('@goji/identity/hyperdb#5')

// '@goji/identity' reconstruction function
function collection5_reconstruct (schemaVersion, keyBuf, valueBuf) {
  const key = collection5_key.decode(keyBuf)
  setVersion(schemaVersion)
  const state = { start: 0, end: valueBuf.byteLength, buffer: valueBuf }
  const type = c.uint.decode(state)
  if (type !== 0) throw new Error('Unknown collection type: ' + type)
  collection5.decodedVersion = c.uint.decode(state)
  const record = collection5_enc.decode(state)
  record.writerKey = key[0]
  return record
}
// '@goji/identity' key reconstruction function
function collection5_reconstruct_key (keyBuf) {
  const key = collection5_key.decode(keyBuf)
  return {
    writerKey: key[0]
  }
}

// '@goji/identity'
const collection5 = {
  name: '@goji/identity',
  id: 5,
  version: 1,
  encodeKey (record) {
    const key = [record.writerKey]
    return collection5_key.encode(key)
  },
  encodeKeyRange ({ gt, lt, gte, lte } = {}) {
    return collection5_key.encodeRange({
      gt: gt ? collection5_indexify(gt) : null,
      lt: lt ? collection5_indexify(lt) : null,
      gte: gte ? collection5_indexify(gte) : null,
      lte: lte ? collection5_indexify(lte) : null
    })
  },
  encodeValue (schemaVersion, collectionVersion, record) {
    setVersion(schemaVersion)
    const state = { start: 0, end: 2, buffer: null }
    collection5_enc.preencode(state, record)
    state.buffer = b4a.allocUnsafe(state.end)
    state.buffer[state.start++] = 0
    state.buffer[state.start++] = collectionVersion
    collection5_enc.encode(state, record)
    return state.buffer
  },
  trigger: null,
  reconstruct: collection5_reconstruct,
  reconstructKey: collection5_reconstruct_key,
  indexes: [],
  decodedVersion: 0
}

// '@goji/wallets' collection key
const collection6_key = new IndexEncoder([
  IndexEncoder.BUFFER
], { prefix: 6 })

function collection6_indexify (record) {
  const a = record.id
  return a === undefined ? [] : [a]
}

// '@goji/wallets' value encoding
const collection6_enc = getEncoding('@goji/wallet/hyperdb#6')

// '@goji/wallets' reconstruction function
function collection6_reconstruct (schemaVersion, keyBuf, valueBuf) {
  const key = collection6_key.decode(keyBuf)
  setVersion(schemaVersion)
  const state = { start: 0, end: valueBuf.byteLength, buffer: valueBuf }
  const type = c.uint.decode(state)
  if (type !== 0) throw new Error('Unknown collection type: ' + type)
  collection6.decodedVersion = c.uint.decode(state)
  const record = collection6_enc.decode(state)
  record.id = key[0]
  return record
}
// '@goji/wallets' key reconstruction function
function collection6_reconstruct_key (keyBuf) {
  const key = collection6_key.decode(keyBuf)
  return {
    id: key[0]
  }
}

// '@goji/wallets'
const collection6 = {
  name: '@goji/wallets',
  id: 6,
  version: 1,
  encodeKey (record) {
    const key = [record.id]
    return collection6_key.encode(key)
  },
  encodeKeyRange ({ gt, lt, gte, lte } = {}) {
    return collection6_key.encodeRange({
      gt: gt ? collection6_indexify(gt) : null,
      lt: lt ? collection6_indexify(lt) : null,
      gte: gte ? collection6_indexify(gte) : null,
      lte: lte ? collection6_indexify(lte) : null
    })
  },
  encodeValue (schemaVersion, collectionVersion, record) {
    setVersion(schemaVersion)
    const state = { start: 0, end: 2, buffer: null }
    collection6_enc.preencode(state, record)
    state.buffer = b4a.allocUnsafe(state.end)
    state.buffer[state.start++] = 0
    state.buffer[state.start++] = collectionVersion
    collection6_enc.encode(state, record)
    return state.buffer
  },
  trigger: null,
  reconstruct: collection6_reconstruct,
  reconstructKey: collection6_reconstruct_key,
  indexes: [],
  decodedVersion: 0
}

const collections = [
  collection0,
  collection1,
  collection2,
  collection3,
  collection4,
  collection5,
  collection6
]

const indexes = [
]

module.exports = { versions, collections, indexes, resolveCollection, resolveIndex }

function resolveCollection (name) {
  switch (name) {
    case '@goji/boards': return collection0
    case '@goji/cards': return collection1
    case '@goji/connections': return collection2
    case '@goji/chat': return collection3
    case '@goji/invites': return collection4
    case '@goji/identity': return collection5
    case '@goji/wallets': return collection6
    default: return null
  }
}

function resolveIndex (name) {
  switch (name) {
    default: return null
  }
}
