// This file is autogenerated by the hyperschema compiler
// Schema Version: 1
/* eslint-disable camelcase */
/* eslint-disable quotes */
/* eslint-disable space-before-function-paren */

const { c } = require('hyperschema/runtime')

const VERSION = 1

// eslint-disable-next-line no-unused-vars
let version = VERSION

// @goji/writer
const encoding0 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.key)
  },
  encode(state, m) {
    c.buffer.encode(state, m.key)
  },
  decode(state) {
    const r0 = c.buffer.decode(state)

    return {
      key: r0
    }
  }
}

// @goji/invite
const encoding1 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.id)
    c.buffer.preencode(state, m.invite)
    c.buffer.preencode(state, m.publicKey)
    c.int.preencode(state, m.expires)
  },
  encode(state, m) {
    c.buffer.encode(state, m.id)
    c.buffer.encode(state, m.invite)
    c.buffer.encode(state, m.publicKey)
    c.int.encode(state, m.expires)
  },
  decode(state) {
    const r0 = c.buffer.decode(state)
    const r1 = c.buffer.decode(state)
    const r2 = c.buffer.decode(state)
    const r3 = c.int.decode(state)

    return {
      id: r0,
      invite: r1,
      publicKey: r2,
      expires: r3
    }
  }
}

// @goji/board
const encoding2 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.id)
    c.string.preencode(state, m.name)
    c.int.preencode(state, m.createdAt)
    c.int.preencode(state, m.updatedAt)
  },
  encode(state, m) {
    c.buffer.encode(state, m.id)
    c.string.encode(state, m.name)
    c.int.encode(state, m.createdAt)
    c.int.encode(state, m.updatedAt)
  },
  decode(state) {
    const r0 = c.buffer.decode(state)
    const r1 = c.string.decode(state)
    const r2 = c.int.decode(state)
    const r3 = c.int.decode(state)

    return {
      id: r0,
      name: r1,
      createdAt: r2,
      updatedAt: r3
    }
  }
}

// @goji/card
const encoding3 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.id)
    c.buffer.preencode(state, m.boardId)
    c.string.preencode(state, m.category)
    c.string.preencode(state, m.title)
    c.float64.preencode(state, m.x)
    c.float64.preencode(state, m.y)
    state.end++ // max flag is 1 so always one byte

    if (m.fields) c.json.preencode(state, m.fields)
    c.int.preencode(state, m.updatedAt)
  },
  encode(state, m) {
    const flags = m.fields ? 1 : 0

    c.buffer.encode(state, m.id)
    c.buffer.encode(state, m.boardId)
    c.string.encode(state, m.category)
    c.string.encode(state, m.title)
    c.float64.encode(state, m.x)
    c.float64.encode(state, m.y)
    c.uint.encode(state, flags)

    if (m.fields) c.json.encode(state, m.fields)
    c.int.encode(state, m.updatedAt)
  },
  decode(state) {
    const r0 = c.buffer.decode(state)
    const r1 = c.buffer.decode(state)
    const r2 = c.string.decode(state)
    const r3 = c.string.decode(state)
    const r4 = c.float64.decode(state)
    const r5 = c.float64.decode(state)
    const flags = c.uint.decode(state)

    return {
      id: r0,
      boardId: r1,
      category: r2,
      title: r3,
      x: r4,
      y: r5,
      fields: (flags & 1) !== 0 ? c.json.decode(state) : null,
      updatedAt: c.int.decode(state)
    }
  }
}

// @goji/connection
const encoding4 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.id)
    c.buffer.preencode(state, m.boardId)
    c.string.preencode(state, m.from)
    c.string.preencode(state, m.to)
    state.end++ // max flag is 1 so always one byte

    if (m.label) c.string.preencode(state, m.label)
    c.int.preencode(state, m.updatedAt)
  },
  encode(state, m) {
    const flags = m.label ? 1 : 0

    c.buffer.encode(state, m.id)
    c.buffer.encode(state, m.boardId)
    c.string.encode(state, m.from)
    c.string.encode(state, m.to)
    c.uint.encode(state, flags)

    if (m.label) c.string.encode(state, m.label)
    c.int.encode(state, m.updatedAt)
  },
  decode(state) {
    const r0 = c.buffer.decode(state)
    const r1 = c.buffer.decode(state)
    const r2 = c.string.decode(state)
    const r3 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      id: r0,
      boardId: r1,
      from: r2,
      to: r3,
      label: (flags & 1) !== 0 ? c.string.decode(state) : null,
      updatedAt: c.int.decode(state)
    }
  }
}

// @goji/chat-msg
const encoding5 = {
  preencode(state, m) {
    c.string.preencode(state, m.id)
    c.string.preencode(state, m.text)
    state.end++ // max flag is 2 so always one byte

    if (m.info) c.json.preencode(state, m.info)
    if (m.proof) c.buffer.preencode(state, m.proof)
  },
  encode(state, m) {
    const flags = (m.info ? 1 : 0) | (m.proof ? 2 : 0)

    c.string.encode(state, m.id)
    c.string.encode(state, m.text)
    c.uint.encode(state, flags)

    if (m.info) c.json.encode(state, m.info)
    if (m.proof) c.buffer.encode(state, m.proof)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      id: r0,
      text: r1,
      info: (flags & 1) !== 0 ? c.json.decode(state) : null,
      proof: (flags & 2) !== 0 ? c.buffer.decode(state) : null
    }
  }
}

// @goji/board-rename
const encoding6 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.id)
    c.string.preencode(state, m.name)
    c.int.preencode(state, m.at)
  },
  encode(state, m) {
    c.buffer.encode(state, m.id)
    c.string.encode(state, m.name)
    c.int.encode(state, m.at)
  },
  decode(state) {
    const r0 = c.buffer.decode(state)
    const r1 = c.string.decode(state)
    const r2 = c.int.decode(state)

    return {
      id: r0,
      name: r1,
      at: r2
    }
  }
}

// @goji/board-delete
const encoding7 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.id)
  },
  encode(state, m) {
    c.buffer.encode(state, m.id)
  },
  decode(state) {
    const r0 = c.buffer.decode(state)

    return {
      id: r0
    }
  }
}

// @goji/card-update
const encoding8 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.id)
    c.json.preencode(state, m.patch)
    c.int.preencode(state, m.at)
  },
  encode(state, m) {
    c.buffer.encode(state, m.id)
    c.json.encode(state, m.patch)
    c.int.encode(state, m.at)
  },
  decode(state) {
    const r0 = c.buffer.decode(state)
    const r1 = c.json.decode(state)
    const r2 = c.int.decode(state)

    return {
      id: r0,
      patch: r1,
      at: r2
    }
  }
}

// @goji/card-remove
const encoding9 = encoding7

// @goji/connection-add
const encoding10 = encoding4

// @goji/connection-remove
const encoding11 = encoding7

// @goji/chats-remove
const encoding12 = {
  preencode(state, m) {
    c.json.preencode(state, m.ids)
  },
  encode(state, m) {
    c.json.encode(state, m.ids)
  },
  decode(state) {
    const r0 = c.json.decode(state)

    return {
      ids: r0
    }
  }
}

// @goji/identity
const encoding13 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.writerKey)
    c.string.preencode(state, m.displayName)
    c.int.preencode(state, m.updatedAt)
  },
  encode(state, m) {
    c.buffer.encode(state, m.writerKey)
    c.string.encode(state, m.displayName)
    c.int.encode(state, m.updatedAt)
  },
  decode(state) {
    const r0 = c.buffer.decode(state)
    const r1 = c.string.decode(state)
    const r2 = c.int.decode(state)

    return {
      writerKey: r0,
      displayName: r1,
      updatedAt: r2
    }
  }
}

// @goji/board/hyperdb#0
const encoding14 = {
  preencode(state, m) {
    c.string.preencode(state, m.name)
    c.int.preencode(state, m.createdAt)
    c.int.preencode(state, m.updatedAt)
  },
  encode(state, m) {
    c.string.encode(state, m.name)
    c.int.encode(state, m.createdAt)
    c.int.encode(state, m.updatedAt)
  },
  decode(state) {
    const r1 = c.string.decode(state)
    const r2 = c.int.decode(state)
    const r3 = c.int.decode(state)

    return {
      id: null,
      name: r1,
      createdAt: r2,
      updatedAt: r3
    }
  }
}

// @goji/card/hyperdb#1
const encoding15 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.boardId)
    c.string.preencode(state, m.category)
    c.string.preencode(state, m.title)
    c.float64.preencode(state, m.x)
    c.float64.preencode(state, m.y)
    state.end++ // max flag is 1 so always one byte

    if (m.fields) c.json.preencode(state, m.fields)
    c.int.preencode(state, m.updatedAt)
  },
  encode(state, m) {
    const flags = m.fields ? 1 : 0

    c.buffer.encode(state, m.boardId)
    c.string.encode(state, m.category)
    c.string.encode(state, m.title)
    c.float64.encode(state, m.x)
    c.float64.encode(state, m.y)
    c.uint.encode(state, flags)

    if (m.fields) c.json.encode(state, m.fields)
    c.int.encode(state, m.updatedAt)
  },
  decode(state) {
    const r1 = c.buffer.decode(state)
    const r2 = c.string.decode(state)
    const r3 = c.string.decode(state)
    const r4 = c.float64.decode(state)
    const r5 = c.float64.decode(state)
    const flags = c.uint.decode(state)

    return {
      id: null,
      boardId: r1,
      category: r2,
      title: r3,
      x: r4,
      y: r5,
      fields: (flags & 1) !== 0 ? c.json.decode(state) : null,
      updatedAt: c.int.decode(state)
    }
  }
}

// @goji/connection/hyperdb#2
const encoding16 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.boardId)
    c.string.preencode(state, m.from)
    c.string.preencode(state, m.to)
    state.end++ // max flag is 1 so always one byte

    if (m.label) c.string.preencode(state, m.label)
    c.int.preencode(state, m.updatedAt)
  },
  encode(state, m) {
    const flags = m.label ? 1 : 0

    c.buffer.encode(state, m.boardId)
    c.string.encode(state, m.from)
    c.string.encode(state, m.to)
    c.uint.encode(state, flags)

    if (m.label) c.string.encode(state, m.label)
    c.int.encode(state, m.updatedAt)
  },
  decode(state) {
    const r1 = c.buffer.decode(state)
    const r2 = c.string.decode(state)
    const r3 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      id: null,
      boardId: r1,
      from: r2,
      to: r3,
      label: (flags & 1) !== 0 ? c.string.decode(state) : null,
      updatedAt: c.int.decode(state)
    }
  }
}

// @goji/chat-msg/hyperdb#3
const encoding17 = {
  preencode(state, m) {
    c.string.preencode(state, m.text)
    state.end++ // max flag is 2 so always one byte

    if (m.info) c.json.preencode(state, m.info)
    if (m.proof) c.buffer.preencode(state, m.proof)
  },
  encode(state, m) {
    const flags = (m.info ? 1 : 0) | (m.proof ? 2 : 0)

    c.string.encode(state, m.text)
    c.uint.encode(state, flags)

    if (m.info) c.json.encode(state, m.info)
    if (m.proof) c.buffer.encode(state, m.proof)
  },
  decode(state) {
    const r1 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      id: null,
      text: r1,
      info: (flags & 1) !== 0 ? c.json.decode(state) : null,
      proof: (flags & 2) !== 0 ? c.buffer.decode(state) : null
    }
  }
}

// @goji/invite/hyperdb#4
const encoding18 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.invite)
    c.buffer.preencode(state, m.publicKey)
    c.int.preencode(state, m.expires)
  },
  encode(state, m) {
    c.buffer.encode(state, m.invite)
    c.buffer.encode(state, m.publicKey)
    c.int.encode(state, m.expires)
  },
  decode(state) {
    const r1 = c.buffer.decode(state)
    const r2 = c.buffer.decode(state)
    const r3 = c.int.decode(state)

    return {
      id: null,
      invite: r1,
      publicKey: r2,
      expires: r3
    }
  }
}

// @goji/identity/hyperdb#5
const encoding19 = {
  preencode(state, m) {
    c.string.preencode(state, m.displayName)
    c.int.preencode(state, m.updatedAt)
  },
  encode(state, m) {
    c.string.encode(state, m.displayName)
    c.int.encode(state, m.updatedAt)
  },
  decode(state) {
    const r1 = c.string.decode(state)
    const r2 = c.int.decode(state)

    return {
      writerKey: null,
      displayName: r1,
      updatedAt: r2
    }
  }
}

function setVersion(v) {
  version = v
}

function encode(name, value, v = VERSION) {
  version = v
  return c.encode(getEncoding(name), value)
}

function decode(name, buffer, v = VERSION) {
  version = v
  return c.decode(getEncoding(name), buffer)
}

function getEnum(name) {
  switch (name) {
    default:
      throw new Error('Enum not found ' + name)
  }
}

function getEncoding(name) {
  switch (name) {
    case '@goji/writer':
      return encoding0
    case '@goji/invite':
      return encoding1
    case '@goji/board':
      return encoding2
    case '@goji/card':
      return encoding3
    case '@goji/connection':
      return encoding4
    case '@goji/chat-msg':
      return encoding5
    case '@goji/board-rename':
      return encoding6
    case '@goji/board-delete':
      return encoding7
    case '@goji/card-update':
      return encoding8
    case '@goji/card-remove':
      return encoding9
    case '@goji/connection-add':
      return encoding10
    case '@goji/connection-remove':
      return encoding11
    case '@goji/chats-remove':
      return encoding12
    case '@goji/identity':
      return encoding13
    case '@goji/board/hyperdb#0':
      return encoding14
    case '@goji/card/hyperdb#1':
      return encoding15
    case '@goji/connection/hyperdb#2':
      return encoding16
    case '@goji/chat-msg/hyperdb#3':
      return encoding17
    case '@goji/invite/hyperdb#4':
      return encoding18
    case '@goji/identity/hyperdb#5':
      return encoding19
    default:
      throw new Error('Encoder not found ' + name)
  }
}

function getStruct(name, v = VERSION) {
  const enc = getEncoding(name)
  return {
    preencode(state, m) {
      version = v
      enc.preencode(state, m)
    },
    encode(state, m) {
      version = v
      enc.encode(state, m)
    },
    decode(state) {
      version = v
      return enc.decode(state)
    }
  }
}

const resolveStruct = getStruct // compat

module.exports = {
  resolveStruct,
  getStruct,
  getEnum,
  getEncoding,
  encode,
  decode,
  setVersion,
  version
}
