// This file is autogenerated by the hyperschema compiler
// Schema Version: 8
/* eslint-disable camelcase */
/* eslint-disable quotes */
/* eslint-disable space-before-function-paren */

const { c } = require('hyperschema/runtime')

const VERSION = 8

// eslint-disable-next-line no-unused-vars
let version = VERSION

// @goji/writer
const encoding0 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.key)
  },
  encode(state, m) {
    c.buffer.encode(state, m.key)
  },
  decode(state) {
    const r0 = c.buffer.decode(state)

    return {
      key: r0
    }
  }
}

// @goji/invite
const encoding1 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.id)
    c.buffer.preencode(state, m.invite)
    c.buffer.preencode(state, m.publicKey)
    c.int.preencode(state, m.expires)
  },
  encode(state, m) {
    c.buffer.encode(state, m.id)
    c.buffer.encode(state, m.invite)
    c.buffer.encode(state, m.publicKey)
    c.int.encode(state, m.expires)
  },
  decode(state) {
    const r0 = c.buffer.decode(state)
    const r1 = c.buffer.decode(state)
    const r2 = c.buffer.decode(state)
    const r3 = c.int.decode(state)

    return {
      id: r0,
      invite: r1,
      publicKey: r2,
      expires: r3
    }
  }
}

// @goji/board
const encoding2 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.id)
    c.string.preencode(state, m.name)
    c.int.preencode(state, m.createdAt)
    c.int.preencode(state, m.updatedAt)
  },
  encode(state, m) {
    c.buffer.encode(state, m.id)
    c.string.encode(state, m.name)
    c.int.encode(state, m.createdAt)
    c.int.encode(state, m.updatedAt)
  },
  decode(state) {
    const r0 = c.buffer.decode(state)
    const r1 = c.string.decode(state)
    const r2 = c.int.decode(state)
    const r3 = c.int.decode(state)

    return {
      id: r0,
      name: r1,
      createdAt: r2,
      updatedAt: r3
    }
  }
}

// @goji/card
const encoding3 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.id)
    c.buffer.preencode(state, m.boardId)
    c.string.preencode(state, m.category)
    c.string.preencode(state, m.title)
    c.float64.preencode(state, m.x)
    c.float64.preencode(state, m.y)
    state.end++ // max flag is 1 so always one byte

    if (m.fields) c.json.preencode(state, m.fields)
    c.int.preencode(state, m.updatedAt)
  },
  encode(state, m) {
    const flags = m.fields ? 1 : 0

    c.buffer.encode(state, m.id)
    c.buffer.encode(state, m.boardId)
    c.string.encode(state, m.category)
    c.string.encode(state, m.title)
    c.float64.encode(state, m.x)
    c.float64.encode(state, m.y)
    c.uint.encode(state, flags)

    if (m.fields) c.json.encode(state, m.fields)
    c.int.encode(state, m.updatedAt)
  },
  decode(state) {
    const r0 = c.buffer.decode(state)
    const r1 = c.buffer.decode(state)
    const r2 = c.string.decode(state)
    const r3 = c.string.decode(state)
    const r4 = c.float64.decode(state)
    const r5 = c.float64.decode(state)
    const flags = c.uint.decode(state)

    return {
      id: r0,
      boardId: r1,
      category: r2,
      title: r3,
      x: r4,
      y: r5,
      fields: (flags & 1) !== 0 ? c.json.decode(state) : null,
      updatedAt: c.int.decode(state)
    }
  }
}

// @goji/connection
const encoding4 = {
  preencode(state, m) {
    const flags =
      (m.label ? 1 : 0) |
      (m.amount ? 2 : 0) |
      (m.payment ? 4 : 0) |
      (m.document ? 8 : 0) |
      (m.template ? 16 : 0) |
      (m.customDoc ? 32 : 0) |
      (m.docName ? 64 : 0) |
      (m.txHash ? 128 : 0) |
      (m.delegationEnabled ? 256 : 0)

    c.buffer.preencode(state, m.id)
    c.buffer.preencode(state, m.boardId)
    c.string.preencode(state, m.from)
    c.string.preencode(state, m.to)
    c.uint.preencode(state, flags)

    if (m.label) c.string.preencode(state, m.label)
    c.int.preencode(state, m.updatedAt)
    if (m.amount) c.string.preencode(state, m.amount)
    if (m.payment) c.int.preencode(state, m.payment)
    if (m.document) c.int.preencode(state, m.document)
    if (m.template) c.string.preencode(state, m.template)
    if (m.customDoc) c.string.preencode(state, m.customDoc)
    if (m.docName) c.string.preencode(state, m.docName)
    if (m.txHash) c.string.preencode(state, m.txHash)
    if (m.delegationEnabled) c.int.preencode(state, m.delegationEnabled)
  },
  encode(state, m) {
    const flags =
      (m.label ? 1 : 0) |
      (m.amount ? 2 : 0) |
      (m.payment ? 4 : 0) |
      (m.document ? 8 : 0) |
      (m.template ? 16 : 0) |
      (m.customDoc ? 32 : 0) |
      (m.docName ? 64 : 0) |
      (m.txHash ? 128 : 0) |
      (m.delegationEnabled ? 256 : 0)

    c.buffer.encode(state, m.id)
    c.buffer.encode(state, m.boardId)
    c.string.encode(state, m.from)
    c.string.encode(state, m.to)
    c.uint.encode(state, flags)

    if (m.label) c.string.encode(state, m.label)
    c.int.encode(state, m.updatedAt)
    if (m.amount) c.string.encode(state, m.amount)
    if (m.payment) c.int.encode(state, m.payment)
    if (m.document) c.int.encode(state, m.document)
    if (m.template) c.string.encode(state, m.template)
    if (m.customDoc) c.string.encode(state, m.customDoc)
    if (m.docName) c.string.encode(state, m.docName)
    if (m.txHash) c.string.encode(state, m.txHash)
    if (m.delegationEnabled) c.int.encode(state, m.delegationEnabled)
  },
  decode(state) {
    const r0 = c.buffer.decode(state)
    const r1 = c.buffer.decode(state)
    const r2 = c.string.decode(state)
    const r3 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      id: r0,
      boardId: r1,
      from: r2,
      to: r3,
      label: (flags & 1) !== 0 ? c.string.decode(state) : null,
      updatedAt: c.int.decode(state),
      amount: (flags & 2) !== 0 ? c.string.decode(state) : null,
      payment: (flags & 4) !== 0 ? c.int.decode(state) : 0,
      document: (flags & 8) !== 0 ? c.int.decode(state) : 0,
      template: (flags & 16) !== 0 ? c.string.decode(state) : null,
      customDoc: (flags & 32) !== 0 ? c.string.decode(state) : null,
      docName: (flags & 64) !== 0 ? c.string.decode(state) : null,
      txHash: (flags & 128) !== 0 ? c.string.decode(state) : null,
      delegationEnabled: (flags & 256) !== 0 ? c.int.decode(state) : 0
    }
  }
}

// @goji/chat-msg
const encoding5 = {
  preencode(state, m) {
    c.string.preencode(state, m.id)
    c.string.preencode(state, m.text)
    state.end++ // max flag is 2 so always one byte

    if (m.info) c.json.preencode(state, m.info)
    if (m.proof) c.buffer.preencode(state, m.proof)
  },
  encode(state, m) {
    const flags = (m.info ? 1 : 0) | (m.proof ? 2 : 0)

    c.string.encode(state, m.id)
    c.string.encode(state, m.text)
    c.uint.encode(state, flags)

    if (m.info) c.json.encode(state, m.info)
    if (m.proof) c.buffer.encode(state, m.proof)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      id: r0,
      text: r1,
      info: (flags & 1) !== 0 ? c.json.decode(state) : null,
      proof: (flags & 2) !== 0 ? c.buffer.decode(state) : null
    }
  }
}

// @goji/wallet
const encoding6 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.id)
    c.string.preencode(state, m.address)
    state.end++ // max flag is 16 so always one byte

    if (m.chainType) c.string.preencode(state, m.chainType)
    if (m.walletType) c.string.preencode(state, m.walletType)
    if (m.name) c.string.preencode(state, m.name)
    c.buffer.preencode(state, m.identityKey)
    if (m.proof) c.buffer.preencode(state, m.proof)
    c.int.preencode(state, m.createdAt)
    if (m.identityPublicKey) c.buffer.preencode(state, m.identityPublicKey)
  },
  encode(state, m) {
    const flags =
      (m.chainType ? 1 : 0) |
      (m.walletType ? 2 : 0) |
      (m.name ? 4 : 0) |
      (m.proof ? 8 : 0) |
      (m.identityPublicKey ? 16 : 0)

    c.buffer.encode(state, m.id)
    c.string.encode(state, m.address)
    c.uint.encode(state, flags)

    if (m.chainType) c.string.encode(state, m.chainType)
    if (m.walletType) c.string.encode(state, m.walletType)
    if (m.name) c.string.encode(state, m.name)
    c.buffer.encode(state, m.identityKey)
    if (m.proof) c.buffer.encode(state, m.proof)
    c.int.encode(state, m.createdAt)
    if (m.identityPublicKey) c.buffer.encode(state, m.identityPublicKey)
  },
  decode(state) {
    const r0 = c.buffer.decode(state)
    const r1 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      id: r0,
      address: r1,
      chainType: (flags & 1) !== 0 ? c.string.decode(state) : null,
      walletType: (flags & 2) !== 0 ? c.string.decode(state) : null,
      name: (flags & 4) !== 0 ? c.string.decode(state) : null,
      identityKey: c.buffer.decode(state),
      proof: (flags & 8) !== 0 ? c.buffer.decode(state) : null,
      createdAt: c.int.decode(state),
      identityPublicKey: (flags & 16) !== 0 ? c.buffer.decode(state) : null
    }
  }
}

// @goji/board-rename
const encoding7 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.id)
    c.string.preencode(state, m.name)
    c.int.preencode(state, m.at)
  },
  encode(state, m) {
    c.buffer.encode(state, m.id)
    c.string.encode(state, m.name)
    c.int.encode(state, m.at)
  },
  decode(state) {
    const r0 = c.buffer.decode(state)
    const r1 = c.string.decode(state)
    const r2 = c.int.decode(state)

    return {
      id: r0,
      name: r1,
      at: r2
    }
  }
}

// @goji/board-delete
const encoding8 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.id)
  },
  encode(state, m) {
    c.buffer.encode(state, m.id)
  },
  decode(state) {
    const r0 = c.buffer.decode(state)

    return {
      id: r0
    }
  }
}

// @goji/card-update
const encoding9 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.id)
    c.json.preencode(state, m.patch)
    c.int.preencode(state, m.at)
  },
  encode(state, m) {
    c.buffer.encode(state, m.id)
    c.json.encode(state, m.patch)
    c.int.encode(state, m.at)
  },
  decode(state) {
    const r0 = c.buffer.decode(state)
    const r1 = c.json.decode(state)
    const r2 = c.int.decode(state)

    return {
      id: r0,
      patch: r1,
      at: r2
    }
  }
}

// @goji/card-remove
const encoding10 = encoding8

// @goji/connection-add
const encoding11 = encoding4

// @goji/connection-remove
const encoding12 = encoding8

// @goji/connection-update
const encoding13 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.id)
    c.json.preencode(state, m.patch)
  },
  encode(state, m) {
    c.buffer.encode(state, m.id)
    c.json.encode(state, m.patch)
  },
  decode(state) {
    const r0 = c.buffer.decode(state)
    const r1 = c.json.decode(state)

    return {
      id: r0,
      patch: r1
    }
  }
}

// @goji/chats-remove
const encoding14 = {
  preencode(state, m) {
    c.json.preencode(state, m.ids)
  },
  encode(state, m) {
    c.json.encode(state, m.ids)
  },
  decode(state) {
    const r0 = c.json.decode(state)

    return {
      ids: r0
    }
  }
}

// @goji/wallet-remove
const encoding15 = encoding8

// @goji/identity
const encoding16 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.writerKey)
    c.string.preencode(state, m.displayName)
    state.end++ // max flag is 4 so always one byte

    if (m.role) c.string.preencode(state, m.role)
    if (m.assignedBy) c.buffer.preencode(state, m.assignedBy)
    if (m.assignedAt) c.int.preencode(state, m.assignedAt)
    c.int.preencode(state, m.updatedAt)
  },
  encode(state, m) {
    const flags = (m.role ? 1 : 0) | (m.assignedBy ? 2 : 0) | (m.assignedAt ? 4 : 0)

    c.buffer.encode(state, m.writerKey)
    c.string.encode(state, m.displayName)
    c.uint.encode(state, flags)

    if (m.role) c.string.encode(state, m.role)
    if (m.assignedBy) c.buffer.encode(state, m.assignedBy)
    if (m.assignedAt) c.int.encode(state, m.assignedAt)
    c.int.encode(state, m.updatedAt)
  },
  decode(state) {
    const r0 = c.buffer.decode(state)
    const r1 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      writerKey: r0,
      displayName: r1,
      role: (flags & 1) !== 0 ? c.string.decode(state) : null,
      assignedBy: (flags & 2) !== 0 ? c.buffer.decode(state) : null,
      assignedAt: (flags & 4) !== 0 ? c.int.decode(state) : 0,
      updatedAt: c.int.decode(state)
    }
  }
}

// @goji/flow-status
const encoding17 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.id)
    c.buffer.preencode(state, m.flowId)
    c.string.preencode(state, m.routeId)
    c.string.preencode(state, m.status)
    state.end++ // max flag is 8 so always one byte

    if (m.txHash) c.string.preencode(state, m.txHash)
    if (m.error) c.string.preencode(state, m.error)
    if (m.payslipHtml) c.string.preencode(state, m.payslipHtml)
    if (m.merkleRoot) c.string.preencode(state, m.merkleRoot)
    c.int.preencode(state, m.updatedAt)
  },
  encode(state, m) {
    const flags =
      (m.txHash ? 1 : 0) | (m.error ? 2 : 0) | (m.payslipHtml ? 4 : 0) | (m.merkleRoot ? 8 : 0)

    c.buffer.encode(state, m.id)
    c.buffer.encode(state, m.flowId)
    c.string.encode(state, m.routeId)
    c.string.encode(state, m.status)
    c.uint.encode(state, flags)

    if (m.txHash) c.string.encode(state, m.txHash)
    if (m.error) c.string.encode(state, m.error)
    if (m.payslipHtml) c.string.encode(state, m.payslipHtml)
    if (m.merkleRoot) c.string.encode(state, m.merkleRoot)
    c.int.encode(state, m.updatedAt)
  },
  decode(state) {
    const r0 = c.buffer.decode(state)
    const r1 = c.buffer.decode(state)
    const r2 = c.string.decode(state)
    const r3 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      id: r0,
      flowId: r1,
      routeId: r2,
      status: r3,
      txHash: (flags & 1) !== 0 ? c.string.decode(state) : null,
      error: (flags & 2) !== 0 ? c.string.decode(state) : null,
      payslipHtml: (flags & 4) !== 0 ? c.string.decode(state) : null,
      merkleRoot: (flags & 8) !== 0 ? c.string.decode(state) : null,
      updatedAt: c.int.decode(state)
    }
  }
}

// @goji/flow-status-remove
const encoding18 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.flowId)
  },
  encode(state, m) {
    c.buffer.encode(state, m.flowId)
  },
  decode(state) {
    const r0 = c.buffer.decode(state)

    return {
      flowId: r0
    }
  }
}

// @goji/template
const encoding19 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.id)
    c.string.preencode(state, m.name)
    state.end++ // max flag is 64 so always one byte

    if (m.companyName) c.string.preencode(state, m.companyName)
    if (m.fields) c.json.preencode(state, m.fields)
    c.string.preencode(state, m.html)
    if (m.isDefault) c.int.preencode(state, m.isDefault)
    if (m.createdBy) c.buffer.preencode(state, m.createdBy)
    c.int.preencode(state, m.createdAt)
    c.int.preencode(state, m.updatedAt)
    if (version >= 5 && m.key) c.string.preencode(state, m.key)
    if (version >= 5 && m.flowType) c.string.preencode(state, m.flowType)
    if (version >= 5 && m.version) c.int.preencode(state, m.version)
  },
  encode(state, m) {
    const flags =
      (m.companyName ? 1 : 0) |
      (m.fields ? 2 : 0) |
      (m.isDefault ? 4 : 0) |
      (m.createdBy ? 8 : 0) |
      ((version >= 5 && m.key) ? 16 : 0) |
      ((version >= 5 && m.flowType) ? 32 : 0) |
      ((version >= 5 && m.version) ? 64 : 0)

    c.buffer.encode(state, m.id)
    c.string.encode(state, m.name)
    c.uint.encode(state, flags)

    if (m.companyName) c.string.encode(state, m.companyName)
    if (m.fields) c.json.encode(state, m.fields)
    c.string.encode(state, m.html)
    if (m.isDefault) c.int.encode(state, m.isDefault)
    if (m.createdBy) c.buffer.encode(state, m.createdBy)
    c.int.encode(state, m.createdAt)
    c.int.encode(state, m.updatedAt)
    if (version >= 5 && m.key) c.string.encode(state, m.key)
    if (version >= 5 && m.flowType) c.string.encode(state, m.flowType)
    if (version >= 5 && m.version) c.int.encode(state, m.version)
  },
  decode(state) {
    const r0 = c.buffer.decode(state)
    const r1 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      id: r0,
      name: r1,
      companyName: (flags & 1) !== 0 ? c.string.decode(state) : null,
      fields: (flags & 2) !== 0 ? c.json.decode(state) : null,
      html: c.string.decode(state),
      isDefault: (flags & 4) !== 0 ? c.int.decode(state) : 0,
      createdBy: (flags & 8) !== 0 ? c.buffer.decode(state) : null,
      createdAt: c.int.decode(state),
      updatedAt: c.int.decode(state),
      key: (version >= 5 && (flags & 16) !== 0) ? c.string.decode(state) : null,
      flowType: (version >= 5 && (flags & 32) !== 0) ? c.string.decode(state) : null,
      version: (version >= 5 && (flags & 64) !== 0) ? c.int.decode(state) : 0
    }
  }
}

// @goji/template-remove
const encoding20 = encoding8

// @goji/receivable
const encoding21 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.id)
    c.string.preencode(state, m.tokenAddress)
    c.string.preencode(state, m.name)
    c.string.preencode(state, m.type)
    c.string.preencode(state, m.amount)
    c.string.preencode(state, m.interestRate)
    c.string.preencode(state, m.minInvestment)
    c.string.preencode(state, m.expiryDays)
    c.json.preencode(state, m.proofs)
    c.string.preencode(state, m.status)
    c.buffer.preencode(state, m.issuer)
    c.int.preencode(state, m.createdAt)
    c.int.preencode(state, m.updatedAt)
    state.end++ // max flag is 4 so always one byte

    if (version >= 8 && m.complianceRegistry) c.string.preencode(state, m.complianceRegistry)
    if (version >= 8 && m.requiredTier) c.int.preencode(state, m.requiredTier)
    if (version >= 8 && m.allowedCountries) c.json.preencode(state, m.allowedCountries)
  },
  encode(state, m) {
    const flags =
      ((version >= 8 && m.complianceRegistry) ? 1 : 0) |
      ((version >= 8 && m.requiredTier) ? 2 : 0) |
      ((version >= 8 && m.allowedCountries) ? 4 : 0)

    c.buffer.encode(state, m.id)
    c.string.encode(state, m.tokenAddress)
    c.string.encode(state, m.name)
    c.string.encode(state, m.type)
    c.string.encode(state, m.amount)
    c.string.encode(state, m.interestRate)
    c.string.encode(state, m.minInvestment)
    c.string.encode(state, m.expiryDays)
    c.json.encode(state, m.proofs)
    c.string.encode(state, m.status)
    c.buffer.encode(state, m.issuer)
    c.int.encode(state, m.createdAt)
    c.int.encode(state, m.updatedAt)
    c.uint.encode(state, flags)

    if (version >= 8 && m.complianceRegistry) c.string.encode(state, m.complianceRegistry)
    if (version >= 8 && m.requiredTier) c.int.encode(state, m.requiredTier)
    if (version >= 8 && m.allowedCountries) c.json.encode(state, m.allowedCountries)
  },
  decode(state) {
    const r0 = c.buffer.decode(state)
    const r1 = c.string.decode(state)
    const r2 = c.string.decode(state)
    const r3 = c.string.decode(state)
    const r4 = c.string.decode(state)
    const r5 = c.string.decode(state)
    const r6 = c.string.decode(state)
    const r7 = c.string.decode(state)
    const r8 = c.json.decode(state)
    const r9 = c.string.decode(state)
    const r10 = c.buffer.decode(state)
    const r11 = c.int.decode(state)
    const r12 = c.int.decode(state)
    const flags = state.start < state.end ? c.uint.decode(state) : 0

    return {
      id: r0,
      tokenAddress: r1,
      name: r2,
      type: r3,
      amount: r4,
      interestRate: r5,
      minInvestment: r6,
      expiryDays: r7,
      proofs: r8,
      status: r9,
      issuer: r10,
      createdAt: r11,
      updatedAt: r12,
      complianceRegistry: (version >= 8 && (flags & 1) !== 0) ? c.string.decode(state) : null,
      requiredTier: (version >= 8 && (flags & 2) !== 0) ? c.int.decode(state) : 0,
      allowedCountries: (version >= 8 && (flags & 4) !== 0) ? c.json.decode(state) : null
    }
  }
}

// @goji/receivable-remove
const encoding22 = encoding8

// @goji/knowledge-document
const encoding23 = {
  preencode(state, m) {
    c.string.preencode(state, m.id)
    c.string.preencode(state, m.name)
    c.string.preencode(state, m.source)
    c.string.preencode(state, m.createdAt)
    state.end++ // max flag is 1 so always one byte

    if (version >= 3 && m.chunkCount) c.int.preencode(state, m.chunkCount)
  },
  encode(state, m) {
    const flags = (version >= 3 && m.chunkCount) ? 1 : 0

    c.string.encode(state, m.id)
    c.string.encode(state, m.name)
    c.string.encode(state, m.source)
    c.string.encode(state, m.createdAt)
    c.uint.encode(state, flags)

    if (version >= 3 && m.chunkCount) c.int.encode(state, m.chunkCount)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.string.decode(state)
    const r2 = c.string.decode(state)
    const r3 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      id: r0,
      name: r1,
      source: r2,
      createdAt: r3,
      chunkCount: (version >= 3 && (flags & 1) !== 0) ? c.int.decode(state) : 0
    }
  }
}

// @goji/rag-search
const encoding24 = {
  preencode(state, m) {
    c.string.preencode(state, m.requestId)
    c.buffer.preencode(state, m.fromKey)
    c.buffer.preencode(state, m.toKey)
    c.string.preencode(state, m.query)
    state.end++ // max flag is 1 so always one byte

    if (version >= 3 && m.topK) c.int.preencode(state, m.topK)
    c.int.preencode(state, m.createdAt)
  },
  encode(state, m) {
    const flags = (version >= 3 && m.topK) ? 1 : 0

    c.string.encode(state, m.requestId)
    c.buffer.encode(state, m.fromKey)
    c.buffer.encode(state, m.toKey)
    c.string.encode(state, m.query)
    c.uint.encode(state, flags)

    if (version >= 3 && m.topK) c.int.encode(state, m.topK)
    c.int.encode(state, m.createdAt)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.buffer.decode(state)
    const r2 = c.buffer.decode(state)
    const r3 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      requestId: r0,
      fromKey: r1,
      toKey: r2,
      query: r3,
      topK: (version >= 3 && (flags & 1) !== 0) ? c.int.decode(state) : 0,
      createdAt: c.int.decode(state)
    }
  }
}

// @goji/rag-search-result
const encoding25 = {
  preencode(state, m) {
    c.string.preencode(state, m.requestId)
    c.buffer.preencode(state, m.fromKey)
    c.buffer.preencode(state, m.toKey)
    c.json.preencode(state, m.results)
    state.end++ // max flag is 1 so always one byte

    if (version >= 3 && m.error) c.string.preencode(state, m.error)
    c.int.preencode(state, m.createdAt)
  },
  encode(state, m) {
    const flags = (version >= 3 && m.error) ? 1 : 0

    c.string.encode(state, m.requestId)
    c.buffer.encode(state, m.fromKey)
    c.buffer.encode(state, m.toKey)
    c.json.encode(state, m.results)
    c.uint.encode(state, flags)

    if (version >= 3 && m.error) c.string.encode(state, m.error)
    c.int.encode(state, m.createdAt)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.buffer.decode(state)
    const r2 = c.buffer.decode(state)
    const r3 = c.json.decode(state)
    const flags = c.uint.decode(state)

    return {
      requestId: r0,
      fromKey: r1,
      toKey: r2,
      results: r3,
      error: (version >= 3 && (flags & 1) !== 0) ? c.string.decode(state) : null,
      createdAt: c.int.decode(state)
    }
  }
}

// @goji/company-profile
const encoding26 = {
  preencode(state, m) {
    const flags =
      ((version >= 4 && m.tradingName) ? 1 : 0) |
      ((version >= 4 && m.country) ? 2 : 0) |
      ((version >= 4 && m.entityType) ? 4 : 0) |
      ((version >= 4 && m.registrationNumber) ? 8 : 0) |
      ((version >= 4 && m.taxId) ? 16 : 0) |
      ((version >= 4 && m.localCurrency) ? 32 : 0) |
      ((version >= 4 && m.fiscalYearStart) ? 64 : 0) |
      ((version >= 4 && m.contactEmail) ? 128 : 0) |
      ((version >= 4 && m.contactPhone) ? 256 : 0) |
      ((version >= 4 && m.address) ? 512 : 0) |
      ((version >= 4 && m.description) ? 1024 : 0)

    c.buffer.preencode(state, m.id)
    c.string.preencode(state, m.legalName)
    c.uint.preencode(state, flags)

    if (version >= 4 && m.tradingName) c.string.preencode(state, m.tradingName)
    if (version >= 4 && m.country) c.string.preencode(state, m.country)
    if (version >= 4 && m.entityType) c.string.preencode(state, m.entityType)
    if (version >= 4 && m.registrationNumber) c.string.preencode(state, m.registrationNumber)
    if (version >= 4 && m.taxId) c.string.preencode(state, m.taxId)
    if (version >= 4 && m.localCurrency) c.string.preencode(state, m.localCurrency)
    if (version >= 4 && m.fiscalYearStart) c.string.preencode(state, m.fiscalYearStart)
    if (version >= 4 && m.contactEmail) c.string.preencode(state, m.contactEmail)
    if (version >= 4 && m.contactPhone) c.string.preencode(state, m.contactPhone)
    if (version >= 4 && m.address) c.string.preencode(state, m.address)
    if (version >= 4 && m.description) c.string.preencode(state, m.description)
    c.int.preencode(state, m.updatedAt)
  },
  encode(state, m) {
    const flags =
      ((version >= 4 && m.tradingName) ? 1 : 0) |
      ((version >= 4 && m.country) ? 2 : 0) |
      ((version >= 4 && m.entityType) ? 4 : 0) |
      ((version >= 4 && m.registrationNumber) ? 8 : 0) |
      ((version >= 4 && m.taxId) ? 16 : 0) |
      ((version >= 4 && m.localCurrency) ? 32 : 0) |
      ((version >= 4 && m.fiscalYearStart) ? 64 : 0) |
      ((version >= 4 && m.contactEmail) ? 128 : 0) |
      ((version >= 4 && m.contactPhone) ? 256 : 0) |
      ((version >= 4 && m.address) ? 512 : 0) |
      ((version >= 4 && m.description) ? 1024 : 0)

    c.buffer.encode(state, m.id)
    c.string.encode(state, m.legalName)
    c.uint.encode(state, flags)

    if (version >= 4 && m.tradingName) c.string.encode(state, m.tradingName)
    if (version >= 4 && m.country) c.string.encode(state, m.country)
    if (version >= 4 && m.entityType) c.string.encode(state, m.entityType)
    if (version >= 4 && m.registrationNumber) c.string.encode(state, m.registrationNumber)
    if (version >= 4 && m.taxId) c.string.encode(state, m.taxId)
    if (version >= 4 && m.localCurrency) c.string.encode(state, m.localCurrency)
    if (version >= 4 && m.fiscalYearStart) c.string.encode(state, m.fiscalYearStart)
    if (version >= 4 && m.contactEmail) c.string.encode(state, m.contactEmail)
    if (version >= 4 && m.contactPhone) c.string.encode(state, m.contactPhone)
    if (version >= 4 && m.address) c.string.encode(state, m.address)
    if (version >= 4 && m.description) c.string.encode(state, m.description)
    c.int.encode(state, m.updatedAt)
  },
  decode(state) {
    const r0 = c.buffer.decode(state)
    const r1 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      id: r0,
      legalName: r1,
      tradingName: (version >= 4 && (flags & 1) !== 0) ? c.string.decode(state) : null,
      country: (version >= 4 && (flags & 2) !== 0) ? c.string.decode(state) : null,
      entityType: (version >= 4 && (flags & 4) !== 0) ? c.string.decode(state) : null,
      registrationNumber: (version >= 4 && (flags & 8) !== 0) ? c.string.decode(state) : null,
      taxId: (version >= 4 && (flags & 16) !== 0) ? c.string.decode(state) : null,
      localCurrency: (version >= 4 && (flags & 32) !== 0) ? c.string.decode(state) : null,
      fiscalYearStart: (version >= 4 && (flags & 64) !== 0) ? c.string.decode(state) : null,
      contactEmail: (version >= 4 && (flags & 128) !== 0) ? c.string.decode(state) : null,
      contactPhone: (version >= 4 && (flags & 256) !== 0) ? c.string.decode(state) : null,
      address: (version >= 4 && (flags & 512) !== 0) ? c.string.decode(state) : null,
      description: (version >= 4 && (flags & 1024) !== 0) ? c.string.decode(state) : null,
      updatedAt: c.int.decode(state)
    }
  }
}

// @goji/company-profile-remove
const encoding27 = encoding8

// @goji/compliance-identity
const encoding28 = {
  preencode(state, m) {
    const flags =
      ((version >= 6 && m.kycSource) ? 1 : 0) |
      ((version >= 6 && m.kycId) ? 2 : 0) |
      ((version >= 6 && m.subTier) ? 4 : 0) |
      ((version >= 6 && m.subGroup) ? 8 : 0) |
      ((version >= 6 && m.expirationTime) ? 16 : 0) |
      ((version >= 6 && m.identityData) ? 32 : 0) |
      ((version >= 6 && m.bankAccountData) ? 64 : 0) |
      ((version >= 6 && m.approvedBy) ? 128 : 0) |
      ((version >= 6 && m.approvedAt) ? 256 : 0) |
      ((version >= 6 && m.lockedAt) ? 512 : 0) |
      ((version >= 6 && m.rejectionReason) ? 1024 : 0) |
      ((version >= 7 && m.auditLog) ? 2048 : 0)

    c.string.preencode(state, m.id)
    c.string.preencode(state, m.walletId)
    c.string.preencode(state, m.walletAddress)
    c.string.preencode(state, m.tokenId)
    c.string.preencode(state, m.passId)
    c.buffer.preencode(state, m.ownerKey)
    c.string.preencode(state, m.status)
    c.uint.preencode(state, flags)

    if (version >= 6 && m.kycSource) c.string.preencode(state, m.kycSource)
    if (version >= 6 && m.kycId) c.string.preencode(state, m.kycId)
    if (version >= 6 && m.subTier) c.int.preencode(state, m.subTier)
    if (version >= 6 && m.subGroup) c.string.preencode(state, m.subGroup)
    if (version >= 6 && m.expirationTime) c.int.preencode(state, m.expirationTime)
    if (version >= 6 && m.identityData) c.json.preencode(state, m.identityData)
    if (version >= 6 && m.bankAccountData) c.json.preencode(state, m.bankAccountData)
    if (version >= 6 && m.approvedBy) c.buffer.preencode(state, m.approvedBy)
    if (version >= 6 && m.approvedAt) c.int.preencode(state, m.approvedAt)
    if (version >= 6 && m.lockedAt) c.int.preencode(state, m.lockedAt)
    if (version >= 6 && m.rejectionReason) c.string.preencode(state, m.rejectionReason)
    c.int.preencode(state, m.createdAt)
    c.int.preencode(state, m.updatedAt)
    if (version >= 7 && m.auditLog) c.json.preencode(state, m.auditLog)
  },
  encode(state, m) {
    const flags =
      ((version >= 6 && m.kycSource) ? 1 : 0) |
      ((version >= 6 && m.kycId) ? 2 : 0) |
      ((version >= 6 && m.subTier) ? 4 : 0) |
      ((version >= 6 && m.subGroup) ? 8 : 0) |
      ((version >= 6 && m.expirationTime) ? 16 : 0) |
      ((version >= 6 && m.identityData) ? 32 : 0) |
      ((version >= 6 && m.bankAccountData) ? 64 : 0) |
      ((version >= 6 && m.approvedBy) ? 128 : 0) |
      ((version >= 6 && m.approvedAt) ? 256 : 0) |
      ((version >= 6 && m.lockedAt) ? 512 : 0) |
      ((version >= 6 && m.rejectionReason) ? 1024 : 0) |
      ((version >= 7 && m.auditLog) ? 2048 : 0)

    c.string.encode(state, m.id)
    c.string.encode(state, m.walletId)
    c.string.encode(state, m.walletAddress)
    c.string.encode(state, m.tokenId)
    c.string.encode(state, m.passId)
    c.buffer.encode(state, m.ownerKey)
    c.string.encode(state, m.status)
    c.uint.encode(state, flags)

    if (version >= 6 && m.kycSource) c.string.encode(state, m.kycSource)
    if (version >= 6 && m.kycId) c.string.encode(state, m.kycId)
    if (version >= 6 && m.subTier) c.int.encode(state, m.subTier)
    if (version >= 6 && m.subGroup) c.string.encode(state, m.subGroup)
    if (version >= 6 && m.expirationTime) c.int.encode(state, m.expirationTime)
    if (version >= 6 && m.identityData) c.json.encode(state, m.identityData)
    if (version >= 6 && m.bankAccountData) c.json.encode(state, m.bankAccountData)
    if (version >= 6 && m.approvedBy) c.buffer.encode(state, m.approvedBy)
    if (version >= 6 && m.approvedAt) c.int.encode(state, m.approvedAt)
    if (version >= 6 && m.lockedAt) c.int.encode(state, m.lockedAt)
    if (version >= 6 && m.rejectionReason) c.string.encode(state, m.rejectionReason)
    c.int.encode(state, m.createdAt)
    c.int.encode(state, m.updatedAt)
    if (version >= 7 && m.auditLog) c.json.encode(state, m.auditLog)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.string.decode(state)
    const r2 = c.string.decode(state)
    const r3 = c.string.decode(state)
    const r4 = c.string.decode(state)
    const r5 = c.buffer.decode(state)
    const r6 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      id: r0,
      walletId: r1,
      walletAddress: r2,
      tokenId: r3,
      passId: r4,
      ownerKey: r5,
      status: r6,
      kycSource: (version >= 6 && (flags & 1) !== 0) ? c.string.decode(state) : null,
      kycId: (version >= 6 && (flags & 2) !== 0) ? c.string.decode(state) : null,
      subTier: (version >= 6 && (flags & 4) !== 0) ? c.int.decode(state) : 0,
      subGroup: (version >= 6 && (flags & 8) !== 0) ? c.string.decode(state) : null,
      expirationTime: (version >= 6 && (flags & 16) !== 0) ? c.int.decode(state) : 0,
      identityData: (version >= 6 && (flags & 32) !== 0) ? c.json.decode(state) : null,
      bankAccountData: (version >= 6 && (flags & 64) !== 0) ? c.json.decode(state) : null,
      approvedBy: (version >= 6 && (flags & 128) !== 0) ? c.buffer.decode(state) : null,
      approvedAt: (version >= 6 && (flags & 256) !== 0) ? c.int.decode(state) : 0,
      lockedAt: (version >= 6 && (flags & 512) !== 0) ? c.int.decode(state) : 0,
      rejectionReason: (version >= 6 && (flags & 1024) !== 0) ? c.string.decode(state) : null,
      createdAt: c.int.decode(state),
      updatedAt: c.int.decode(state),
      auditLog: (version >= 7 && (flags & 2048) !== 0) ? c.json.decode(state) : null
    }
  }
}

// @goji/board/hyperdb#0
const encoding29 = {
  preencode(state, m) {
    c.string.preencode(state, m.name)
    c.int.preencode(state, m.createdAt)
    c.int.preencode(state, m.updatedAt)
  },
  encode(state, m) {
    c.string.encode(state, m.name)
    c.int.encode(state, m.createdAt)
    c.int.encode(state, m.updatedAt)
  },
  decode(state) {
    const r1 = c.string.decode(state)
    const r2 = c.int.decode(state)
    const r3 = c.int.decode(state)

    return {
      id: null,
      name: r1,
      createdAt: r2,
      updatedAt: r3
    }
  }
}

// @goji/card/hyperdb#1
const encoding30 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.boardId)
    c.string.preencode(state, m.category)
    c.string.preencode(state, m.title)
    c.float64.preencode(state, m.x)
    c.float64.preencode(state, m.y)
    state.end++ // max flag is 1 so always one byte

    if (m.fields) c.json.preencode(state, m.fields)
    c.int.preencode(state, m.updatedAt)
  },
  encode(state, m) {
    const flags = m.fields ? 1 : 0

    c.buffer.encode(state, m.boardId)
    c.string.encode(state, m.category)
    c.string.encode(state, m.title)
    c.float64.encode(state, m.x)
    c.float64.encode(state, m.y)
    c.uint.encode(state, flags)

    if (m.fields) c.json.encode(state, m.fields)
    c.int.encode(state, m.updatedAt)
  },
  decode(state) {
    const r1 = c.buffer.decode(state)
    const r2 = c.string.decode(state)
    const r3 = c.string.decode(state)
    const r4 = c.float64.decode(state)
    const r5 = c.float64.decode(state)
    const flags = c.uint.decode(state)

    return {
      id: null,
      boardId: r1,
      category: r2,
      title: r3,
      x: r4,
      y: r5,
      fields: (flags & 1) !== 0 ? c.json.decode(state) : null,
      updatedAt: c.int.decode(state)
    }
  }
}

// @goji/connection/hyperdb#2
const encoding31 = {
  preencode(state, m) {
    const flags =
      (m.label ? 1 : 0) |
      (m.amount ? 2 : 0) |
      (m.payment ? 4 : 0) |
      (m.document ? 8 : 0) |
      (m.template ? 16 : 0) |
      (m.customDoc ? 32 : 0) |
      (m.docName ? 64 : 0) |
      (m.txHash ? 128 : 0) |
      (m.delegationEnabled ? 256 : 0)

    c.buffer.preencode(state, m.boardId)
    c.string.preencode(state, m.from)
    c.string.preencode(state, m.to)
    c.uint.preencode(state, flags)

    if (m.label) c.string.preencode(state, m.label)
    c.int.preencode(state, m.updatedAt)
    if (m.amount) c.string.preencode(state, m.amount)
    if (m.payment) c.int.preencode(state, m.payment)
    if (m.document) c.int.preencode(state, m.document)
    if (m.template) c.string.preencode(state, m.template)
    if (m.customDoc) c.string.preencode(state, m.customDoc)
    if (m.docName) c.string.preencode(state, m.docName)
    if (m.txHash) c.string.preencode(state, m.txHash)
    if (m.delegationEnabled) c.int.preencode(state, m.delegationEnabled)
  },
  encode(state, m) {
    const flags =
      (m.label ? 1 : 0) |
      (m.amount ? 2 : 0) |
      (m.payment ? 4 : 0) |
      (m.document ? 8 : 0) |
      (m.template ? 16 : 0) |
      (m.customDoc ? 32 : 0) |
      (m.docName ? 64 : 0) |
      (m.txHash ? 128 : 0) |
      (m.delegationEnabled ? 256 : 0)

    c.buffer.encode(state, m.boardId)
    c.string.encode(state, m.from)
    c.string.encode(state, m.to)
    c.uint.encode(state, flags)

    if (m.label) c.string.encode(state, m.label)
    c.int.encode(state, m.updatedAt)
    if (m.amount) c.string.encode(state, m.amount)
    if (m.payment) c.int.encode(state, m.payment)
    if (m.document) c.int.encode(state, m.document)
    if (m.template) c.string.encode(state, m.template)
    if (m.customDoc) c.string.encode(state, m.customDoc)
    if (m.docName) c.string.encode(state, m.docName)
    if (m.txHash) c.string.encode(state, m.txHash)
    if (m.delegationEnabled) c.int.encode(state, m.delegationEnabled)
  },
  decode(state) {
    const r1 = c.buffer.decode(state)
    const r2 = c.string.decode(state)
    const r3 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      id: null,
      boardId: r1,
      from: r2,
      to: r3,
      label: (flags & 1) !== 0 ? c.string.decode(state) : null,
      updatedAt: c.int.decode(state),
      amount: (flags & 2) !== 0 ? c.string.decode(state) : null,
      payment: (flags & 4) !== 0 ? c.int.decode(state) : 0,
      document: (flags & 8) !== 0 ? c.int.decode(state) : 0,
      template: (flags & 16) !== 0 ? c.string.decode(state) : null,
      customDoc: (flags & 32) !== 0 ? c.string.decode(state) : null,
      docName: (flags & 64) !== 0 ? c.string.decode(state) : null,
      txHash: (flags & 128) !== 0 ? c.string.decode(state) : null,
      delegationEnabled: (flags & 256) !== 0 ? c.int.decode(state) : 0
    }
  }
}

// @goji/chat-msg/hyperdb#3
const encoding32 = {
  preencode(state, m) {
    c.string.preencode(state, m.text)
    state.end++ // max flag is 2 so always one byte

    if (m.info) c.json.preencode(state, m.info)
    if (m.proof) c.buffer.preencode(state, m.proof)
  },
  encode(state, m) {
    const flags = (m.info ? 1 : 0) | (m.proof ? 2 : 0)

    c.string.encode(state, m.text)
    c.uint.encode(state, flags)

    if (m.info) c.json.encode(state, m.info)
    if (m.proof) c.buffer.encode(state, m.proof)
  },
  decode(state) {
    const r1 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      id: null,
      text: r1,
      info: (flags & 1) !== 0 ? c.json.decode(state) : null,
      proof: (flags & 2) !== 0 ? c.buffer.decode(state) : null
    }
  }
}

// @goji/invite/hyperdb#4
const encoding33 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.invite)
    c.buffer.preencode(state, m.publicKey)
    c.int.preencode(state, m.expires)
  },
  encode(state, m) {
    c.buffer.encode(state, m.invite)
    c.buffer.encode(state, m.publicKey)
    c.int.encode(state, m.expires)
  },
  decode(state) {
    const r1 = c.buffer.decode(state)
    const r2 = c.buffer.decode(state)
    const r3 = c.int.decode(state)

    return {
      id: null,
      invite: r1,
      publicKey: r2,
      expires: r3
    }
  }
}

// @goji/identity/hyperdb#5
const encoding34 = {
  preencode(state, m) {
    c.string.preencode(state, m.displayName)
    state.end++ // max flag is 4 so always one byte

    if (m.role) c.string.preencode(state, m.role)
    if (m.assignedBy) c.buffer.preencode(state, m.assignedBy)
    if (m.assignedAt) c.int.preencode(state, m.assignedAt)
    c.int.preencode(state, m.updatedAt)
  },
  encode(state, m) {
    const flags = (m.role ? 1 : 0) | (m.assignedBy ? 2 : 0) | (m.assignedAt ? 4 : 0)

    c.string.encode(state, m.displayName)
    c.uint.encode(state, flags)

    if (m.role) c.string.encode(state, m.role)
    if (m.assignedBy) c.buffer.encode(state, m.assignedBy)
    if (m.assignedAt) c.int.encode(state, m.assignedAt)
    c.int.encode(state, m.updatedAt)
  },
  decode(state) {
    const r1 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      writerKey: null,
      displayName: r1,
      role: (flags & 1) !== 0 ? c.string.decode(state) : null,
      assignedBy: (flags & 2) !== 0 ? c.buffer.decode(state) : null,
      assignedAt: (flags & 4) !== 0 ? c.int.decode(state) : 0,
      updatedAt: c.int.decode(state)
    }
  }
}

// @goji/wallet/hyperdb#6
const encoding35 = {
  preencode(state, m) {
    c.string.preencode(state, m.address)
    state.end++ // max flag is 16 so always one byte

    if (m.chainType) c.string.preencode(state, m.chainType)
    if (m.walletType) c.string.preencode(state, m.walletType)
    if (m.name) c.string.preencode(state, m.name)
    c.buffer.preencode(state, m.identityKey)
    if (m.proof) c.buffer.preencode(state, m.proof)
    c.int.preencode(state, m.createdAt)
    if (m.identityPublicKey) c.buffer.preencode(state, m.identityPublicKey)
  },
  encode(state, m) {
    const flags =
      (m.chainType ? 1 : 0) |
      (m.walletType ? 2 : 0) |
      (m.name ? 4 : 0) |
      (m.proof ? 8 : 0) |
      (m.identityPublicKey ? 16 : 0)

    c.string.encode(state, m.address)
    c.uint.encode(state, flags)

    if (m.chainType) c.string.encode(state, m.chainType)
    if (m.walletType) c.string.encode(state, m.walletType)
    if (m.name) c.string.encode(state, m.name)
    c.buffer.encode(state, m.identityKey)
    if (m.proof) c.buffer.encode(state, m.proof)
    c.int.encode(state, m.createdAt)
    if (m.identityPublicKey) c.buffer.encode(state, m.identityPublicKey)
  },
  decode(state) {
    const r1 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      id: null,
      address: r1,
      chainType: (flags & 1) !== 0 ? c.string.decode(state) : null,
      walletType: (flags & 2) !== 0 ? c.string.decode(state) : null,
      name: (flags & 4) !== 0 ? c.string.decode(state) : null,
      identityKey: c.buffer.decode(state),
      proof: (flags & 8) !== 0 ? c.buffer.decode(state) : null,
      createdAt: c.int.decode(state),
      identityPublicKey: (flags & 16) !== 0 ? c.buffer.decode(state) : null
    }
  }
}

// @goji/flow-status/hyperdb#7
const encoding36 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.flowId)
    c.string.preencode(state, m.routeId)
    c.string.preencode(state, m.status)
    state.end++ // max flag is 8 so always one byte

    if (m.txHash) c.string.preencode(state, m.txHash)
    if (m.error) c.string.preencode(state, m.error)
    if (m.payslipHtml) c.string.preencode(state, m.payslipHtml)
    if (m.merkleRoot) c.string.preencode(state, m.merkleRoot)
    c.int.preencode(state, m.updatedAt)
  },
  encode(state, m) {
    const flags =
      (m.txHash ? 1 : 0) | (m.error ? 2 : 0) | (m.payslipHtml ? 4 : 0) | (m.merkleRoot ? 8 : 0)

    c.buffer.encode(state, m.flowId)
    c.string.encode(state, m.routeId)
    c.string.encode(state, m.status)
    c.uint.encode(state, flags)

    if (m.txHash) c.string.encode(state, m.txHash)
    if (m.error) c.string.encode(state, m.error)
    if (m.payslipHtml) c.string.encode(state, m.payslipHtml)
    if (m.merkleRoot) c.string.encode(state, m.merkleRoot)
    c.int.encode(state, m.updatedAt)
  },
  decode(state) {
    const r1 = c.buffer.decode(state)
    const r2 = c.string.decode(state)
    const r3 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      id: null,
      flowId: r1,
      routeId: r2,
      status: r3,
      txHash: (flags & 1) !== 0 ? c.string.decode(state) : null,
      error: (flags & 2) !== 0 ? c.string.decode(state) : null,
      payslipHtml: (flags & 4) !== 0 ? c.string.decode(state) : null,
      merkleRoot: (flags & 8) !== 0 ? c.string.decode(state) : null,
      updatedAt: c.int.decode(state)
    }
  }
}

// @goji/template/hyperdb#8
const encoding37 = {
  preencode(state, m) {
    c.string.preencode(state, m.name)
    state.end++ // max flag is 64 so always one byte

    if (m.companyName) c.string.preencode(state, m.companyName)
    if (m.fields) c.json.preencode(state, m.fields)
    c.string.preencode(state, m.html)
    if (m.isDefault) c.int.preencode(state, m.isDefault)
    if (m.createdBy) c.buffer.preencode(state, m.createdBy)
    c.int.preencode(state, m.createdAt)
    c.int.preencode(state, m.updatedAt)
    if (version >= 5 && m.key) c.string.preencode(state, m.key)
    if (version >= 5 && m.flowType) c.string.preencode(state, m.flowType)
    if (version >= 5 && m.version) c.int.preencode(state, m.version)
  },
  encode(state, m) {
    const flags =
      (m.companyName ? 1 : 0) |
      (m.fields ? 2 : 0) |
      (m.isDefault ? 4 : 0) |
      (m.createdBy ? 8 : 0) |
      ((version >= 5 && m.key) ? 16 : 0) |
      ((version >= 5 && m.flowType) ? 32 : 0) |
      ((version >= 5 && m.version) ? 64 : 0)

    c.string.encode(state, m.name)
    c.uint.encode(state, flags)

    if (m.companyName) c.string.encode(state, m.companyName)
    if (m.fields) c.json.encode(state, m.fields)
    c.string.encode(state, m.html)
    if (m.isDefault) c.int.encode(state, m.isDefault)
    if (m.createdBy) c.buffer.encode(state, m.createdBy)
    c.int.encode(state, m.createdAt)
    c.int.encode(state, m.updatedAt)
    if (version >= 5 && m.key) c.string.encode(state, m.key)
    if (version >= 5 && m.flowType) c.string.encode(state, m.flowType)
    if (version >= 5 && m.version) c.int.encode(state, m.version)
  },
  decode(state) {
    const r1 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      id: null,
      name: r1,
      companyName: (flags & 1) !== 0 ? c.string.decode(state) : null,
      fields: (flags & 2) !== 0 ? c.json.decode(state) : null,
      html: c.string.decode(state),
      isDefault: (flags & 4) !== 0 ? c.int.decode(state) : 0,
      createdBy: (flags & 8) !== 0 ? c.buffer.decode(state) : null,
      createdAt: c.int.decode(state),
      updatedAt: c.int.decode(state),
      key: (version >= 5 && (flags & 16) !== 0) ? c.string.decode(state) : null,
      flowType: (version >= 5 && (flags & 32) !== 0) ? c.string.decode(state) : null,
      version: (version >= 5 && (flags & 64) !== 0) ? c.int.decode(state) : 0
    }
  }
}

// @goji/receivable/hyperdb#9
const encoding38 = {
  preencode(state, m) {
    c.string.preencode(state, m.tokenAddress)
    c.string.preencode(state, m.name)
    c.string.preencode(state, m.type)
    c.string.preencode(state, m.amount)
    c.string.preencode(state, m.interestRate)
    c.string.preencode(state, m.minInvestment)
    c.string.preencode(state, m.expiryDays)
    c.json.preencode(state, m.proofs)
    c.string.preencode(state, m.status)
    c.buffer.preencode(state, m.issuer)
    c.int.preencode(state, m.createdAt)
    c.int.preencode(state, m.updatedAt)
    state.end++ // max flag is 4 so always one byte

    if (version >= 8 && m.complianceRegistry) c.string.preencode(state, m.complianceRegistry)
    if (version >= 8 && m.requiredTier) c.int.preencode(state, m.requiredTier)
    if (version >= 8 && m.allowedCountries) c.json.preencode(state, m.allowedCountries)
  },
  encode(state, m) {
    const flags =
      ((version >= 8 && m.complianceRegistry) ? 1 : 0) |
      ((version >= 8 && m.requiredTier) ? 2 : 0) |
      ((version >= 8 && m.allowedCountries) ? 4 : 0)

    c.string.encode(state, m.tokenAddress)
    c.string.encode(state, m.name)
    c.string.encode(state, m.type)
    c.string.encode(state, m.amount)
    c.string.encode(state, m.interestRate)
    c.string.encode(state, m.minInvestment)
    c.string.encode(state, m.expiryDays)
    c.json.encode(state, m.proofs)
    c.string.encode(state, m.status)
    c.buffer.encode(state, m.issuer)
    c.int.encode(state, m.createdAt)
    c.int.encode(state, m.updatedAt)
    c.uint.encode(state, flags)

    if (version >= 8 && m.complianceRegistry) c.string.encode(state, m.complianceRegistry)
    if (version >= 8 && m.requiredTier) c.int.encode(state, m.requiredTier)
    if (version >= 8 && m.allowedCountries) c.json.encode(state, m.allowedCountries)
  },
  decode(state) {
    const r1 = c.string.decode(state)
    const r2 = c.string.decode(state)
    const r3 = c.string.decode(state)
    const r4 = c.string.decode(state)
    const r5 = c.string.decode(state)
    const r6 = c.string.decode(state)
    const r7 = c.string.decode(state)
    const r8 = c.json.decode(state)
    const r9 = c.string.decode(state)
    const r10 = c.buffer.decode(state)
    const r11 = c.int.decode(state)
    const r12 = c.int.decode(state)
    const flags = state.start < state.end ? c.uint.decode(state) : 0

    return {
      id: null,
      tokenAddress: r1,
      name: r2,
      type: r3,
      amount: r4,
      interestRate: r5,
      minInvestment: r6,
      expiryDays: r7,
      proofs: r8,
      status: r9,
      issuer: r10,
      createdAt: r11,
      updatedAt: r12,
      complianceRegistry: (version >= 8 && (flags & 1) !== 0) ? c.string.decode(state) : null,
      requiredTier: (version >= 8 && (flags & 2) !== 0) ? c.int.decode(state) : 0,
      allowedCountries: (version >= 8 && (flags & 4) !== 0) ? c.json.decode(state) : null
    }
  }
}

// @goji/knowledge-document/hyperdb#10
const encoding39 = {
  preencode(state, m) {
    c.string.preencode(state, m.name)
    c.string.preencode(state, m.source)
    c.string.preencode(state, m.createdAt)
    state.end++ // max flag is 1 so always one byte

    if (version >= 3 && m.chunkCount) c.int.preencode(state, m.chunkCount)
  },
  encode(state, m) {
    const flags = (version >= 3 && m.chunkCount) ? 1 : 0

    c.string.encode(state, m.name)
    c.string.encode(state, m.source)
    c.string.encode(state, m.createdAt)
    c.uint.encode(state, flags)

    if (version >= 3 && m.chunkCount) c.int.encode(state, m.chunkCount)
  },
  decode(state) {
    const r1 = c.string.decode(state)
    const r2 = c.string.decode(state)
    const r3 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      id: null,
      name: r1,
      source: r2,
      createdAt: r3,
      chunkCount: (version >= 3 && (flags & 1) !== 0) ? c.int.decode(state) : 0
    }
  }
}

// @goji/rag-search/hyperdb#11
const encoding40 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.fromKey)
    c.buffer.preencode(state, m.toKey)
    c.string.preencode(state, m.query)
    state.end++ // max flag is 1 so always one byte

    if (version >= 3 && m.topK) c.int.preencode(state, m.topK)
    c.int.preencode(state, m.createdAt)
  },
  encode(state, m) {
    const flags = (version >= 3 && m.topK) ? 1 : 0

    c.buffer.encode(state, m.fromKey)
    c.buffer.encode(state, m.toKey)
    c.string.encode(state, m.query)
    c.uint.encode(state, flags)

    if (version >= 3 && m.topK) c.int.encode(state, m.topK)
    c.int.encode(state, m.createdAt)
  },
  decode(state) {
    const r1 = c.buffer.decode(state)
    const r2 = c.buffer.decode(state)
    const r3 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      requestId: null,
      fromKey: r1,
      toKey: r2,
      query: r3,
      topK: (version >= 3 && (flags & 1) !== 0) ? c.int.decode(state) : 0,
      createdAt: c.int.decode(state)
    }
  }
}

// @goji/rag-search-result/hyperdb#12
const encoding41 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.fromKey)
    c.buffer.preencode(state, m.toKey)
    c.json.preencode(state, m.results)
    state.end++ // max flag is 1 so always one byte

    if (version >= 3 && m.error) c.string.preencode(state, m.error)
    c.int.preencode(state, m.createdAt)
  },
  encode(state, m) {
    const flags = (version >= 3 && m.error) ? 1 : 0

    c.buffer.encode(state, m.fromKey)
    c.buffer.encode(state, m.toKey)
    c.json.encode(state, m.results)
    c.uint.encode(state, flags)

    if (version >= 3 && m.error) c.string.encode(state, m.error)
    c.int.encode(state, m.createdAt)
  },
  decode(state) {
    const r1 = c.buffer.decode(state)
    const r2 = c.buffer.decode(state)
    const r3 = c.json.decode(state)
    const flags = c.uint.decode(state)

    return {
      requestId: null,
      fromKey: r1,
      toKey: r2,
      results: r3,
      error: (version >= 3 && (flags & 1) !== 0) ? c.string.decode(state) : null,
      createdAt: c.int.decode(state)
    }
  }
}

// @goji/company-profile/hyperdb#13
const encoding42 = {
  preencode(state, m) {
    const flags =
      ((version >= 4 && m.tradingName) ? 1 : 0) |
      ((version >= 4 && m.country) ? 2 : 0) |
      ((version >= 4 && m.entityType) ? 4 : 0) |
      ((version >= 4 && m.registrationNumber) ? 8 : 0) |
      ((version >= 4 && m.taxId) ? 16 : 0) |
      ((version >= 4 && m.localCurrency) ? 32 : 0) |
      ((version >= 4 && m.fiscalYearStart) ? 64 : 0) |
      ((version >= 4 && m.contactEmail) ? 128 : 0) |
      ((version >= 4 && m.contactPhone) ? 256 : 0) |
      ((version >= 4 && m.address) ? 512 : 0) |
      ((version >= 4 && m.description) ? 1024 : 0)

    c.string.preencode(state, m.legalName)
    c.uint.preencode(state, flags)

    if (version >= 4 && m.tradingName) c.string.preencode(state, m.tradingName)
    if (version >= 4 && m.country) c.string.preencode(state, m.country)
    if (version >= 4 && m.entityType) c.string.preencode(state, m.entityType)
    if (version >= 4 && m.registrationNumber) c.string.preencode(state, m.registrationNumber)
    if (version >= 4 && m.taxId) c.string.preencode(state, m.taxId)
    if (version >= 4 && m.localCurrency) c.string.preencode(state, m.localCurrency)
    if (version >= 4 && m.fiscalYearStart) c.string.preencode(state, m.fiscalYearStart)
    if (version >= 4 && m.contactEmail) c.string.preencode(state, m.contactEmail)
    if (version >= 4 && m.contactPhone) c.string.preencode(state, m.contactPhone)
    if (version >= 4 && m.address) c.string.preencode(state, m.address)
    if (version >= 4 && m.description) c.string.preencode(state, m.description)
    c.int.preencode(state, m.updatedAt)
  },
  encode(state, m) {
    const flags =
      ((version >= 4 && m.tradingName) ? 1 : 0) |
      ((version >= 4 && m.country) ? 2 : 0) |
      ((version >= 4 && m.entityType) ? 4 : 0) |
      ((version >= 4 && m.registrationNumber) ? 8 : 0) |
      ((version >= 4 && m.taxId) ? 16 : 0) |
      ((version >= 4 && m.localCurrency) ? 32 : 0) |
      ((version >= 4 && m.fiscalYearStart) ? 64 : 0) |
      ((version >= 4 && m.contactEmail) ? 128 : 0) |
      ((version >= 4 && m.contactPhone) ? 256 : 0) |
      ((version >= 4 && m.address) ? 512 : 0) |
      ((version >= 4 && m.description) ? 1024 : 0)

    c.string.encode(state, m.legalName)
    c.uint.encode(state, flags)

    if (version >= 4 && m.tradingName) c.string.encode(state, m.tradingName)
    if (version >= 4 && m.country) c.string.encode(state, m.country)
    if (version >= 4 && m.entityType) c.string.encode(state, m.entityType)
    if (version >= 4 && m.registrationNumber) c.string.encode(state, m.registrationNumber)
    if (version >= 4 && m.taxId) c.string.encode(state, m.taxId)
    if (version >= 4 && m.localCurrency) c.string.encode(state, m.localCurrency)
    if (version >= 4 && m.fiscalYearStart) c.string.encode(state, m.fiscalYearStart)
    if (version >= 4 && m.contactEmail) c.string.encode(state, m.contactEmail)
    if (version >= 4 && m.contactPhone) c.string.encode(state, m.contactPhone)
    if (version >= 4 && m.address) c.string.encode(state, m.address)
    if (version >= 4 && m.description) c.string.encode(state, m.description)
    c.int.encode(state, m.updatedAt)
  },
  decode(state) {
    const r1 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      id: null,
      legalName: r1,
      tradingName: (version >= 4 && (flags & 1) !== 0) ? c.string.decode(state) : null,
      country: (version >= 4 && (flags & 2) !== 0) ? c.string.decode(state) : null,
      entityType: (version >= 4 && (flags & 4) !== 0) ? c.string.decode(state) : null,
      registrationNumber: (version >= 4 && (flags & 8) !== 0) ? c.string.decode(state) : null,
      taxId: (version >= 4 && (flags & 16) !== 0) ? c.string.decode(state) : null,
      localCurrency: (version >= 4 && (flags & 32) !== 0) ? c.string.decode(state) : null,
      fiscalYearStart: (version >= 4 && (flags & 64) !== 0) ? c.string.decode(state) : null,
      contactEmail: (version >= 4 && (flags & 128) !== 0) ? c.string.decode(state) : null,
      contactPhone: (version >= 4 && (flags & 256) !== 0) ? c.string.decode(state) : null,
      address: (version >= 4 && (flags & 512) !== 0) ? c.string.decode(state) : null,
      description: (version >= 4 && (flags & 1024) !== 0) ? c.string.decode(state) : null,
      updatedAt: c.int.decode(state)
    }
  }
}

// @goji/compliance-identity/hyperdb#14
const encoding43 = {
  preencode(state, m) {
    const flags =
      ((version >= 6 && m.kycSource) ? 1 : 0) |
      ((version >= 6 && m.kycId) ? 2 : 0) |
      ((version >= 6 && m.subTier) ? 4 : 0) |
      ((version >= 6 && m.subGroup) ? 8 : 0) |
      ((version >= 6 && m.expirationTime) ? 16 : 0) |
      ((version >= 6 && m.identityData) ? 32 : 0) |
      ((version >= 6 && m.bankAccountData) ? 64 : 0) |
      ((version >= 6 && m.approvedBy) ? 128 : 0) |
      ((version >= 6 && m.approvedAt) ? 256 : 0) |
      ((version >= 6 && m.lockedAt) ? 512 : 0) |
      ((version >= 6 && m.rejectionReason) ? 1024 : 0) |
      ((version >= 7 && m.auditLog) ? 2048 : 0)

    c.string.preencode(state, m.walletId)
    c.string.preencode(state, m.walletAddress)
    c.string.preencode(state, m.tokenId)
    c.string.preencode(state, m.passId)
    c.buffer.preencode(state, m.ownerKey)
    c.string.preencode(state, m.status)
    c.uint.preencode(state, flags)

    if (version >= 6 && m.kycSource) c.string.preencode(state, m.kycSource)
    if (version >= 6 && m.kycId) c.string.preencode(state, m.kycId)
    if (version >= 6 && m.subTier) c.int.preencode(state, m.subTier)
    if (version >= 6 && m.subGroup) c.string.preencode(state, m.subGroup)
    if (version >= 6 && m.expirationTime) c.int.preencode(state, m.expirationTime)
    if (version >= 6 && m.identityData) c.json.preencode(state, m.identityData)
    if (version >= 6 && m.bankAccountData) c.json.preencode(state, m.bankAccountData)
    if (version >= 6 && m.approvedBy) c.buffer.preencode(state, m.approvedBy)
    if (version >= 6 && m.approvedAt) c.int.preencode(state, m.approvedAt)
    if (version >= 6 && m.lockedAt) c.int.preencode(state, m.lockedAt)
    if (version >= 6 && m.rejectionReason) c.string.preencode(state, m.rejectionReason)
    c.int.preencode(state, m.createdAt)
    c.int.preencode(state, m.updatedAt)
    if (version >= 7 && m.auditLog) c.json.preencode(state, m.auditLog)
  },
  encode(state, m) {
    const flags =
      ((version >= 6 && m.kycSource) ? 1 : 0) |
      ((version >= 6 && m.kycId) ? 2 : 0) |
      ((version >= 6 && m.subTier) ? 4 : 0) |
      ((version >= 6 && m.subGroup) ? 8 : 0) |
      ((version >= 6 && m.expirationTime) ? 16 : 0) |
      ((version >= 6 && m.identityData) ? 32 : 0) |
      ((version >= 6 && m.bankAccountData) ? 64 : 0) |
      ((version >= 6 && m.approvedBy) ? 128 : 0) |
      ((version >= 6 && m.approvedAt) ? 256 : 0) |
      ((version >= 6 && m.lockedAt) ? 512 : 0) |
      ((version >= 6 && m.rejectionReason) ? 1024 : 0) |
      ((version >= 7 && m.auditLog) ? 2048 : 0)

    c.string.encode(state, m.walletId)
    c.string.encode(state, m.walletAddress)
    c.string.encode(state, m.tokenId)
    c.string.encode(state, m.passId)
    c.buffer.encode(state, m.ownerKey)
    c.string.encode(state, m.status)
    c.uint.encode(state, flags)

    if (version >= 6 && m.kycSource) c.string.encode(state, m.kycSource)
    if (version >= 6 && m.kycId) c.string.encode(state, m.kycId)
    if (version >= 6 && m.subTier) c.int.encode(state, m.subTier)
    if (version >= 6 && m.subGroup) c.string.encode(state, m.subGroup)
    if (version >= 6 && m.expirationTime) c.int.encode(state, m.expirationTime)
    if (version >= 6 && m.identityData) c.json.encode(state, m.identityData)
    if (version >= 6 && m.bankAccountData) c.json.encode(state, m.bankAccountData)
    if (version >= 6 && m.approvedBy) c.buffer.encode(state, m.approvedBy)
    if (version >= 6 && m.approvedAt) c.int.encode(state, m.approvedAt)
    if (version >= 6 && m.lockedAt) c.int.encode(state, m.lockedAt)
    if (version >= 6 && m.rejectionReason) c.string.encode(state, m.rejectionReason)
    c.int.encode(state, m.createdAt)
    c.int.encode(state, m.updatedAt)
    if (version >= 7 && m.auditLog) c.json.encode(state, m.auditLog)
  },
  decode(state) {
    const r1 = c.string.decode(state)
    const r2 = c.string.decode(state)
    const r3 = c.string.decode(state)
    const r4 = c.string.decode(state)
    const r5 = c.buffer.decode(state)
    const r6 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      id: null,
      walletId: r1,
      walletAddress: r2,
      tokenId: r3,
      passId: r4,
      ownerKey: r5,
      status: r6,
      kycSource: (version >= 6 && (flags & 1) !== 0) ? c.string.decode(state) : null,
      kycId: (version >= 6 && (flags & 2) !== 0) ? c.string.decode(state) : null,
      subTier: (version >= 6 && (flags & 4) !== 0) ? c.int.decode(state) : 0,
      subGroup: (version >= 6 && (flags & 8) !== 0) ? c.string.decode(state) : null,
      expirationTime: (version >= 6 && (flags & 16) !== 0) ? c.int.decode(state) : 0,
      identityData: (version >= 6 && (flags & 32) !== 0) ? c.json.decode(state) : null,
      bankAccountData: (version >= 6 && (flags & 64) !== 0) ? c.json.decode(state) : null,
      approvedBy: (version >= 6 && (flags & 128) !== 0) ? c.buffer.decode(state) : null,
      approvedAt: (version >= 6 && (flags & 256) !== 0) ? c.int.decode(state) : 0,
      lockedAt: (version >= 6 && (flags & 512) !== 0) ? c.int.decode(state) : 0,
      rejectionReason: (version >= 6 && (flags & 1024) !== 0) ? c.string.decode(state) : null,
      createdAt: c.int.decode(state),
      updatedAt: c.int.decode(state),
      auditLog: (version >= 7 && (flags & 2048) !== 0) ? c.json.decode(state) : null
    }
  }
}

function setVersion(v) {
  version = v
}

function encode(name, value, v = VERSION) {
  version = v
  return c.encode(getEncoding(name), value)
}

function decode(name, buffer, v = VERSION) {
  version = v
  return c.decode(getEncoding(name), buffer)
}

function getEnum(name) {
  switch (name) {
    default:
      throw new Error('Enum not found ' + name)
  }
}

function getEncoding(name) {
  switch (name) {
    case '@goji/writer':
      return encoding0
    case '@goji/invite':
      return encoding1
    case '@goji/board':
      return encoding2
    case '@goji/card':
      return encoding3
    case '@goji/connection':
      return encoding4
    case '@goji/chat-msg':
      return encoding5
    case '@goji/wallet':
      return encoding6
    case '@goji/board-rename':
      return encoding7
    case '@goji/board-delete':
      return encoding8
    case '@goji/card-update':
      return encoding9
    case '@goji/card-remove':
      return encoding10
    case '@goji/connection-add':
      return encoding11
    case '@goji/connection-remove':
      return encoding12
    case '@goji/connection-update':
      return encoding13
    case '@goji/chats-remove':
      return encoding14
    case '@goji/wallet-remove':
      return encoding15
    case '@goji/identity':
      return encoding16
    case '@goji/flow-status':
      return encoding17
    case '@goji/flow-status-remove':
      return encoding18
    case '@goji/template':
      return encoding19
    case '@goji/template-remove':
      return encoding20
    case '@goji/receivable':
      return encoding21
    case '@goji/receivable-remove':
      return encoding22
    case '@goji/knowledge-document':
      return encoding23
    case '@goji/rag-search':
      return encoding24
    case '@goji/rag-search-result':
      return encoding25
    case '@goji/company-profile':
      return encoding26
    case '@goji/company-profile-remove':
      return encoding27
    case '@goji/compliance-identity':
      return encoding28
    case '@goji/board/hyperdb#0':
      return encoding29
    case '@goji/card/hyperdb#1':
      return encoding30
    case '@goji/connection/hyperdb#2':
      return encoding31
    case '@goji/chat-msg/hyperdb#3':
      return encoding32
    case '@goji/invite/hyperdb#4':
      return encoding33
    case '@goji/identity/hyperdb#5':
      return encoding34
    case '@goji/wallet/hyperdb#6':
      return encoding35
    case '@goji/flow-status/hyperdb#7':
      return encoding36
    case '@goji/template/hyperdb#8':
      return encoding37
    case '@goji/receivable/hyperdb#9':
      return encoding38
    case '@goji/knowledge-document/hyperdb#10':
      return encoding39
    case '@goji/rag-search/hyperdb#11':
      return encoding40
    case '@goji/rag-search-result/hyperdb#12':
      return encoding41
    case '@goji/company-profile/hyperdb#13':
      return encoding42
    case '@goji/compliance-identity/hyperdb#14':
      return encoding43
    default:
      throw new Error('Encoder not found ' + name)
  }
}

function getStruct(name, v = VERSION) {
  const enc = getEncoding(name)
  return {
    preencode(state, m) {
      version = v
      enc.preencode(state, m)
    },
    encode(state, m) {
      version = v
      enc.encode(state, m)
    },
    decode(state) {
      version = v
      return enc.decode(state)
    }
  }
}

const resolveStruct = getStruct // compat

module.exports = {
  resolveStruct,
  getStruct,
  getEnum,
  getEncoding,
  encode,
  decode,
  setVersion,
  version
}
