export interface PayslipTemplate {
  id: string
  name: string
  docName: string
  html: string
}

const CSS_RESET = `*{margin:0;padding:0;box-sizing:border-box}`

export const DEFAULT_TEMPLATES: PayslipTemplate[] = [
  {
    id: 'standard',
    name: 'Payment Receipt',
    docName: 'Payment Receipt',
    html: `<html><head><style>${CSS_RESET}
body{font-family:'Segoe UI',system-ui,sans-serif;padding:32px;max-width:640px;margin:0 auto;color:#1a1a2e;background:#fafafa}
.container{background:#fff;border-radius:12px;padding:32px;box-shadow:0 2px 12px rgba(0,0,0,0.08)}
.header{display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:24px;padding-bottom:16px;border-bottom:2px solid #7FD9B0}
.header-left h1{font-size:22px;color:#1a1a2e;margin:0 0 4px}
.header-left .company{font-size:13px;color:#666}
.header-right{text-align:right}
.badge{padding:4px 12px;border-radius:20px;font-size:11px;font-weight:600;display:inline-block}
.badge-paid{background:#7FD9B0;color:#fff}
.badge-unpaid{background:#f0f0f0;color:#666}
.section{margin:20px 0}
.section-title{font-size:11px;text-transform:uppercase;letter-spacing:1px;color:#999;margin-bottom:12px;border-bottom:1px solid #eee;padding-bottom:6px}
.party{display:flex;gap:24px;margin-bottom:16px}
.party-box{flex:1;background:#f8f9fa;border-radius:8px;padding:16px}
.party-box .role{font-size:10px;text-transform:uppercase;color:#999;margin-bottom:4px}
.party-box .name{font-weight:600;color:#1a1a2e;font-size:14px}
.party-box .address{font-size:12px;color:#666;margin-top:4px}
.row{display:flex;justify-content:space-between;padding:8px 0;border-bottom:1px solid #f0f0f0}
.row:last-child{border-bottom:none}
.label{color:#666;font-size:13px}
.value{font-weight:600;color:#1a1a2e;font-size:13px}
.amount-box{background:#f8f9fa;border-radius:8px;padding:16px;margin:16px 0;text-align:center}
.amount-box .label{font-size:12px;color:#999;margin-bottom:4px}
.amount-box .value{font-size:28px;font-weight:700;color:#1a1a1a}
.notes{background:#fffde7;border-radius:8px;padding:12px;margin-top:16px;font-size:12px;color:#666}
.notes strong{color:#1a1a2e}
.footer{margin-top:32px;padding-top:16px;border-top:1px solid #eee;font-size:11px;color:#999;text-align:center}
</style></head><body>
<div class="container">
  <div class="header">
    <div class="header-left">
      <h1>Payment Receipt</h1>
      <div class="company">{{companyName}}</div>
    </div>
    <div class="header-right">
      <span class="badge {{statusClass}}">{{status}}</span>
    </div>
  </div>
  
  <div class="party">
    <div class="party-box">
      <div class="role">From</div>
      <div class="name">{{sender}}</div>
      {{#senderAddress}}<div class="address">{{senderAddress}}</div>{{/senderAddress}}
    </div>
    <div class="party-box">
      <div class="role">To</div>
      <div class="name">{{recipient}}</div>
      {{#recipientAddress}}<div class="address">{{recipientAddress}}</div>{{/recipientAddress}}
    </div>
  </div>

  <div class="section">
    <div class="section-title">Payment Details</div>
    <div class="row"><span class="label">Date</span><span class="value">{{date}}</span></div>
    <div class="row"><span class="label">Reference</span><span class="value">{{txHash}}</span></div>
    {{#reference}}<div class="row"><span class="label">Reference #</span><span class="value">{{reference}}</span></div>{{/reference}}
  </div>

  <div class="amount-box">
    <div class="label">Amount Paid</div>
    <div class="value">{{amount}} USDC</div>
  </div>

  {{#notes}}<div class="notes"><strong>Notes:</strong> {{notes}}</div>{{/notes}}

  <div class="footer">Generated by Goji P2P Workspace</div>
</div>
</body></html>`
  },
  {
    id: 'invoice',
    name: 'Invoice',
    docName: 'Invoice',
    html: `<html><head><style>${CSS_RESET}
body{font-family:'Segoe UI',system-ui,sans-serif;padding:32px;max-width:640px;margin:0 auto;color:#1a1a2e;background:#fafafa}
.container{background:#fff;border-radius:12px;padding:32px;box-shadow:0 2px 12px rgba(0,0,0,0.08)}
.header{display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:24px;padding-bottom:16px;border-bottom:2px solid #8B7FD6}
.header-left h1{font-size:22px;color:#5A4FB8;margin:0 0 4px}
.header-left .company{font-size:13px;color:#666}
.header-right{text-align:right}
.badge{padding:4px 12px;border-radius:20px;font-size:11px;font-weight:600;display:inline-block}
.badge-paid{background:#7FD9B0;color:#fff}
.badge-unpaid{background:#f0f0f0;color:#666}
.meta{display:flex;gap:24px;margin-bottom:24px;padding:12px;background:#f8f9fa;border-radius:8px}
.meta-item{font-size:12px;color:#666}
.meta-item strong{display:block;color:#1a1a2e;font-size:13px}
.section{margin:20px 0}
.section-title{font-size:11px;text-transform:uppercase;letter-spacing:1px;color:#999;margin-bottom:12px;border-bottom:1px solid #eee;padding-bottom:6px}
.party{display:flex;gap:24px;margin-bottom:16px}
.party-box{flex:1;background:#f8f9fa;border-radius:8px;padding:16px}
.party-box .role{font-size:10px;text-transform:uppercase;color:#999;margin-bottom:4px}
.party-box .name{font-weight:600;color:#1a1a2e;font-size:14px}
.party-box .address{font-size:12px;color:#666;margin-top:4px}
.party-box .tax-id{font-size:11px;color:#999;margin-top:2px}
table{width:100%;border-collapse:collapse;margin:16px 0}
th{text-align:left;font-size:11px;text-transform:uppercase;letter-spacing:1px;color:#999;padding:8px 0;border-bottom:2px solid #eee}
td{padding:10px 0;border-bottom:1px solid #f0f0f0;font-size:13px}
td:last-child{text-align:right}
.total-box{background:#f0eeff;border-radius:8px;padding:16px;margin:20px 0}
.total-row{display:flex;justify-content:space-between;padding:4px 0}
.total-row.grand{font-size:18px;font-weight:700;color:#5A4FB8;padding-top:8px;border-top:2px solid #8B7FD6}
.notes{background:#fffde7;border-radius:8px;padding:12px;margin-top:16px;font-size:12px;color:#666}
.notes strong{color:#1a1a2e}
.payment-terms{background:#f8f9fa;border-radius:8px;padding:12px;margin-top:16px;font-size:12px;color:#666}
.payment-terms strong{color:#1a1a2e}
.footer{margin-top:32px;padding-top:16px;border-top:1px solid #eee;font-size:11px;color:#999;text-align:center}
</style></head><body>
<div class="container">
  <div class="header">
    <div class="header-left">
      <h1>INVOICE</h1>
      <div class="company">{{companyName}}</div>
      {{#companyAddress}}<div class="company">{{companyAddress}}</div>{{/companyAddress}}
    </div>
    <div class="header-right">
      <span class="badge {{statusClass}}">{{status}}</span>
    </div>
  </div>

  <div class="meta">
    <div class="meta-item"><strong>Invoice #</strong>{{invoiceNumber}}</div>
    <div class="meta-item"><strong>Date</strong>{{invoiceDate}}</div>
    <div class="meta-item"><strong>Due Date</strong>{{dueDate}}</div>
  </div>

  <div class="party">
    <div class="party-box">
      <div class="role">From</div>
      <div class="name">{{sender}}</div>
    </div>
    <div class="party-box">
      <div class="role">Bill To</div>
      <div class="name">{{billToName}}</div>
      {{#billToAddress}}<div class="address">{{billToAddress}}</div>{{/billToAddress}}
      {{#billToTaxId}}<div class="tax-id">Tax ID: {{billToTaxId}}</div>{{/billToTaxId}}
    </div>
  </div>

  <div class="section">
    <div class="section-title">Line Items</div>
    <table>
      <thead>
        <tr>
          <th>Description</th>
          <th>Qty</th>
          <th>Unit Price</th>
          <th>Amount</th>
        </tr>
      </thead>
      <tbody>
        {{lineItems}}
      </tbody>
    </table>
  </div>

  <div class="total-box">
    <div class="total-row"><span>Subtotal</span><span>{{subtotal}} USDC</span></div>
    {{#taxAmount}}<div class="total-row"><span>Tax ({{taxRate}}%)</span><span>{{taxAmount}} USDC</span></div>{{/taxAmount}}
    <div class="total-row grand"><span>Total Due</span><span>{{total}} USDC</span></div>
  </div>

  {{#paymentTerms}}<div class="payment-terms"><strong>Payment Terms:</strong> {{paymentTerms}}</div>{{/paymentTerms}}
  {{#notes}}<div class="notes"><strong>Notes:</strong> {{notes}}</div>{{/notes}}

  <div class="footer">
    Transaction: {{txHash}}<br>
    Generated by Goji P2P Workspace
  </div>
</div>
</body></html>`
  },
  {
    id: 'agreement',
    name: 'Service Agreement',
    docName: 'Service Agreement',
    html: `<html><head><style>${CSS_RESET}
body{font-family:'Segoe UI',system-ui,sans-serif;padding:32px;max-width:640px;margin:0 auto;color:#1a1a2e;background:#fafafa;line-height:1.6}
.container{background:#fff;border-radius:12px;padding:32px;box-shadow:0 2px 12px rgba(0,0,0,0.08)}
.header{text-align:center;margin-bottom:24px;padding-bottom:16px;border-bottom:2px solid #ddd}
.header h1{font-size:22px;color:#1a1a2e;margin:0 0 4px}
.header .company{font-size:13px;color:#666}
.section{margin:24px 0}
.section-title{font-size:11px;text-transform:uppercase;letter-spacing:1px;color:#999;margin-bottom:12px;border-bottom:1px solid #eee;padding-bottom:6px}
.party{display:flex;gap:24px;margin-bottom:16px}
.party-box{flex:1;background:#f8f9fa;border-radius:8px;padding:16px}
.party-box .role{font-size:10px;text-transform:uppercase;color:#999;margin-bottom:4px}
.party-box .name{font-weight:600;color:#1a1a2e;font-size:14px}
.party-box .address{font-size:12px;color:#666;margin-top:4px}
.row{display:flex;justify-content:space-between;padding:8px 0;border-bottom:1px solid #f0f0f0}
.row:last-child{border-bottom:none}
.label{color:#666;font-size:13px}
.value{font-weight:600;color:#1a1a2e;font-size:13px}
.highlight{background:#f0f0f0;border-radius:8px;padding:16px;margin:16px 0}
.highlight .label{font-size:12px;color:#666;margin-bottom:4px}
.highlight .value{font-size:18px;font-weight:700;color:#1a1a1a}
.scope{background:#f8f9fa;border-radius:8px;padding:16px;margin:16px 0;font-size:13px;color:#444}
.terms{background:#f8f9fa;border-radius:8px;padding:16px;margin:16px 0}
.terms .term{margin-bottom:8px}
.terms .term:last-child{margin-bottom:0}
.terms .term strong{color:#1a1a2e}
.footer{margin-top:32px;padding-top:16px;border-top:1px solid #eee;font-size:11px;color:#999;text-align:center}
.signature{margin-top:40px;display:flex;justify-content:space-between}
.signature-box{width:45%}
.signature-box .line{border-bottom:1px solid #333;margin-top:40px;margin-bottom:4px}
.signature-box .label{font-size:11px;color:#666}
</style></head><body>
<div class="container">
  <div class="header">
    <h1>SERVICE AGREEMENT</h1>
    <div class="company">{{companyName}}</div>
  </div>

  <div class="section">
    <div class="section-title">Effective Date</div>
    <p>{{effectiveDate}}</p>
  </div>

  <div class="section">
    <div class="section-title">Parties</div>
    <div class="party">
      <div class="party-box">
        <div class="role">Company (Service Provider)</div>
        <div class="name">{{sender}}</div>
        {{#companyAddress}}<div class="address">{{companyAddress}}</div>{{/companyAddress}}
      </div>
      <div class="party-box">
        <div class="role">Client</div>
        <div class="name">{{recipient}}</div>
        {{#clientAddress}}<div class="address">{{clientAddress}}</div>{{/clientAddress}}
      </div>
    </div>
  </div>

  <div class="section">
    <div class="section-title">Duration</div>
    <p>{{duration}}</p>
  </div>

  <div class="section">
    <div class="section-title">Scope of Work</div>
    <div class="scope">{{scope}}</div>
  </div>

  <div class="section">
    <div class="section-title">Compensation</div>
    <div class="highlight">
      <div class="label">Total Compensation</div>
      <div class="value">{{amount}} USDC</div>
    </div>
    {{#paymentSchedule}}<div class="terms"><div class="term"><strong>Payment Schedule:</strong> {{paymentSchedule}}</div></div>{{/paymentSchedule}}
  </div>

  {{#terminationClause}}<div class="section"><div class="section-title">Termination</div><p>{{terminationClause}}</p></div>{{/terminationClause}}

  <div class="signature">
    <div class="signature-box">
      <div class="line"></div>
      <div class="label">{{sender}} (Authorized Signatory)</div>
    </div>
    <div class="signature-box">
      <div class="line"></div>
      <div class="label">{{recipient}} (Client)</div>
    </div>
  </div>

  <div class="footer">
    Transaction: {{txHash}}<br>
    Generated by Goji P2P Workspace
  </div>
</div>
</body></html>`
  }
]

export function renderTemplate(html: string, vars: Record<string, string>): string {
  let result = html || ''
  for (const [key, value] of Object.entries(vars)) {
    result = result.replace(new RegExp(`{{${key}}}`, 'g'), value)
  }
  return result
}
