export interface PayslipTemplate {
  id: string
  name: string
  docName: string
  html: string
}

const CSS_RESET = `*{margin:0;padding:0;box-sizing:border-box}`

export const DEFAULT_TEMPLATES: PayslipTemplate[] = [
  {
    id: 'standard',
    name: 'Standard Receipt',
    docName: 'Payment Receipt',
    html: `<html><head><style>${CSS_RESET}body{font-family:system-ui,sans-serif;padding:24px;max-width:600px;margin:0 auto;color:#333}h1{font-size:20px;border-bottom:2px solid #7FD9B0;padding-bottom:8px;margin-bottom:16px}.row{display:flex;justify-content:space-between;padding:6px 0;border-bottom:1px solid #eee}.label{color:#666}.value{font-weight:500}.footer{margin-top:32px;font-size:12px;color:#999;text-align:center}</style></head><body>
<h1>Payment Receipt</h1>
<div class="row"><span class="label">Date</span><span class="value">{{date}}</span></div>
<div class="row"><span class="label">From</span><span class="value">{{sender}}</span></div>
<div class="row"><span class="label">To</span><span class="value">{{recipient}}</span></div>
<div class="row"><span class="label">Amount</span><span class="value">{{amount}} USDC</span></div>
<div class="row"><span class="label">Transaction</span><span class="value" style="font-family:monospace;font-size:12px">{{txHash}}</span></div>
<div class="footer">This receipt was generated automatically by Goji.</div>
</body></html>`
  },
  {
    id: 'invoice',
    name: 'Invoice',
    docName: 'Invoice',
    html: `<html><head><style>${CSS_RESET}body{font-family:system-ui,sans-serif;padding:24px;max-width:600px;margin:0 auto;color:#333}h1{font-size:20px;color:#5A4FB8;border-bottom:2px solid #8B7FD6;padding-bottom:8px;margin-bottom:16px}.row{display:flex;justify-content:space-between;padding:6px 0;border-bottom:1px solid #eee}.label{color:#666}.value{font-weight:500}.total{font-size:18px;font-weight:700;margin:16px 0;padding:8px 0;border-top:2px solid #8B7FD6;display:flex;justify-content:space-between}.footer{margin-top:32px;font-size:12px;color:#999;text-align:center}</style></head><body>
<h1>Invoice</h1>
<div class="row"><span class="label">Invoice Date</span><span class="value">{{date}}</span></div>
<div class="row"><span class="label">Bill To</span><span class="value">{{recipient}}</span></div>
<div class="row"><span class="label">From</span><span class="value">{{sender}}</span></div>
<div class="total"><span>Total Due</span><span>{{amount}} USDC</span></div>
<div class="row"><span class="label">Transaction</span><span class="value" style="font-family:monospace;font-size:12px">{{txHash}}</span></div>
<div class="footer">Generated by Goji</div>
</body></html>`
  },
  {
    id: 'agreement',
    name: 'Service Agreement',
    docName: 'Job Agreement',
    html: `<html><head><style>${CSS_RESET}body{font-family:system-ui,sans-serif;padding:24px;max-width:600px;margin:0 auto;color:#333;line-height:1.6}h1{font-size:20px;border-bottom:2px solid #ccc;padding-bottom:8px;margin-bottom:16px}.section{margin:16px 0}.row{display:flex;justify-content:space-between;padding:6px 0;border-bottom:1px solid #eee}.label{color:#666}.value{font-weight:500}.footer{margin-top:32px;font-size:12px;color:#999;text-align:center}</style></head><body>
<h1>Service Agreement</h1>
<div class="section">
<p>This agreement is made between:</p>
<div class="row"><span class="label">Client</span><span class="value">{{sender}}</span></div>
<div class="row"><span class="label">Service Provider</span><span class="value">{{recipient}}</span></div>
<div class="row"><span class="label">Date</span><span class="value">{{date}}</span></div>
</div>
<div class="section">
<p><strong>Compensation:</strong> {{amount}} USDC payable upon completion.</p>
</div>
<div class="section">
<p><strong>Transaction Reference:</strong> <span style="font-family:monospace;font-size:12px">{{txHash}}</span></p>
</div>
<div class="footer">Generated by Goji</div>
</body></html>`
  }
]

export function renderTemplate(html: string, vars: Record<string, string>): string {
  let result = html || ''
  for (const [key, value] of Object.entries(vars)) {
    result = result.replace(new RegExp(`{{${key}}}`, 'g'), value)
  }
  return result
}
