export interface PayslipTemplate {
  id: string
  name: string
  docName: string
  html: string
}

const CSS_RESET = `*{margin:0;padding:0;box-sizing:border-box}`

export const DEFAULT_TEMPLATES: PayslipTemplate[] = [
  {
    id: 'standard',
    name: 'Payment Receipt',
    docName: 'Payment Receipt',
    html: `<html><head><style>${CSS_RESET}
body{font-family:'Segoe UI',system-ui,sans-serif;padding:32px;max-width:640px;margin:0 auto;color:#1a1a2e;background:#fafafa}
.container{background:#fff;border-radius:12px;padding:32px;box-shadow:0 2px 12px rgba(0,0,0,0.08)}
.header{display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:24px;padding-bottom:16px;border-bottom:2px solid #7FD9B0}
.header h1{font-size:22px;color:#1a1a2e;margin:0}
.badge{padding:4px 12px;border-radius:20px;font-size:11px;font-weight:600}
.badge-paid{background:#7FD9B0;color:#fff}
.badge-unpaid{background:#f0f0f0;color:#666}
.section{margin:20px 0}
.section-title{font-size:11px;text-transform:uppercase;letter-spacing:1px;color:#999;margin-bottom:12px;border-bottom:1px solid #eee;padding-bottom:6px}
.row{display:flex;justify-content:space-between;padding:8px 0;border-bottom:1px solid #f0f0f0}
.row:last-child{border-bottom:none}
.label{color:#666;font-size:13px}
.value{font-weight:600;color:#1a1a2e;font-size:13px}
.amount-box{background:#f8f9fa;border-radius:8px;padding:16px;margin:16px 0;text-align:center}
.amount-box .label{font-size:12px;color:#999;margin-bottom:4px}
.amount-box .value{font-size:28px;font-weight:700;color:#1a1a1a}
.footer{margin-top:32px;padding-top:16px;border-top:1px solid #eee;font-size:11px;color:#999;text-align:center}
.footer a{color:#7FD9B0;text-decoration:none}
</style></head><body>
<div class="container">
  <div class="header">
    <h1>Payment Receipt</h1>
    <span class="badge {{statusClass}}">{{status}}</span>
  </div>
  <div class="section">
    <div class="section-title">Payment Details</div>
    <div class="row"><span class="label">Date</span><span class="value">{{date}}</span></div>
    <div class="row"><span class="label">From</span><span class="value">{{sender}}</span></div>
    <div class="row"><span class="label">To</span><span class="value">{{recipient}}</span></div>
    <div class="row"><span class="label">Reference</span><span class="value">{{txHash}}</span></div>
  </div>
  <div class="amount-box">
    <div class="label">Amount Paid</div>
    <div class="value">{{amount}} USDC</div>
  </div>
  <div class="footer">
    This receipt was generated by Goji P2P Workspace<br>
    <a href="#">View on Arc Explorer</a>
  </div>
</div>
</body></html>`
  },
  {
    id: 'invoice',
    name: 'Invoice',
    docName: 'Invoice',
    html: `<html><head><style>${CSS_RESET}
body{font-family:'Segoe UI',system-ui,sans-serif;padding:32px;max-width:640px;margin:0 auto;color:#1a1a2e;background:#fafafa}
.container{background:#fff;border-radius:12px;padding:32px;box-shadow:0 2px 12px rgba(0,0,0,0.08)}
.header{display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:24px;padding-bottom:16px;border-bottom:2px solid #8B7FD6}
.header h1{font-size:22px;color:#5A4FB8;margin:0}
.badge{padding:4px 12px;border-radius:20px;font-size:11px;font-weight:600}
.badge-paid{background:#7FD9B0;color:#fff}
.badge-unpaid{background:#f0f0f0;color:#666}
.meta{display:flex;gap:24px;margin-bottom:24px}
.meta-item{font-size:12px;color:#666}
.meta-item strong{display:block;color:#1a1a2e;font-size:13px}
.section{margin:20px 0}
.section-title{font-size:11px;text-transform:uppercase;letter-spacing:1px;color:#999;margin-bottom:12px;border-bottom:1px solid #eee;padding-bottom:6px}
.row{display:flex;justify-content:space-between;padding:8px 0;border-bottom:1px solid #f0f0f0}
.row:last-child{border-bottom:none}
.label{color:#666;font-size:13px}
.value{font-weight:600;color:#1a1a2e;font-size:13px}
.total-box{background:#f0eeff;border-radius:8px;padding:16px;margin:20px 0}
.total-box .row{border-bottom:none;padding:4px 0}
.total-box .label{color:#5A4FB8}
.total-box .value{font-size:20px;font-weight:700;color:#5A4FB8}
.footer{margin-top:32px;padding-top:16px;border-top:1px solid #eee;font-size:11px;color:#999;text-align:center}
</style></head><body>
<div class="container">
  <div class="header">
    <h1>INVOICE</h1>
    <span class="badge {{statusClass}}">{{status}}</span>
  </div>
  <div class="meta">
    <div class="meta-item"><strong>Invoice #</strong>{{invoiceNumber}}</div>
    <div class="meta-item"><strong>Date</strong>{{date}}</div>
    <div class="meta-item"><strong>Due Date</strong>{{dueDate}}</div>
  </div>
  <div class="section">
    <div class="section-title">Bill To</div>
    <div class="row"><span class="label">Company</span><span class="value">{{recipient}}</span></div>
  </div>
  <div class="section">
    <div class="section-title">From</div>
    <div class="row"><span class="label">Company</span><span class="value">{{sender}}</span></div>
  </div>
  <div class="section">
    <div class="section-title">Description</div>
    <div class="row"><span class="label">Service</span><span class="value">{{description}}</span></div>
    <div class="row"><span class="label">Quantity</span><span class="value">{{quantity}}</span></div>
    <div class="row"><span class="label">Unit Price</span><span class="value">{{unitPrice}} USDC</span></div>
  </div>
  <div class="total-box">
    <div class="row"><span class="label">Subtotal</span><span class="value">{{amount}} USDC</span></div>
    <div class="row"><span class="label">Tax (7%)</span><span class="value">{{tax}} USDC</span></div>
    <div class="row"><span class="label">Total Due</span><span class="value">{{totalDue}} USDC</span></div>
  </div>
  <div class="footer">
    Payment due within 30 days<br>
    Transaction: {{txHash}}
  </div>
</div>
</body></html>`
  },
  {
    id: 'agreement',
    name: 'Service Agreement',
    docName: 'Service Agreement',
    html: `<html><head><style>${CSS_RESET}
body{font-family:'Segoe UI',system-ui,sans-serif;padding:32px;max-width:640px;margin:0 auto;color:#1a1a2e;background:#fafafa;line-height:1.6}
.container{background:#fff;border-radius:12px;padding:32px;box-shadow:0 2px 12px rgba(0,0,0,0.08)}
.header{text-align:center;margin-bottom:24px;padding-bottom:16px;border-bottom:2px solid #ddd}
.header h1{font-size:22px;color:#1a1a2e;margin:0 0 8px}
.header .subtitle{color:#666;font-size:13px}
.section{margin:24px 0}
.section-title{font-size:11px;text-transform:uppercase;letter-spacing:1px;color:#999;margin-bottom:12px;border-bottom:1px solid #eee;padding-bottom:6px}
.party{background:#f8f9fa;border-radius:8px;padding:16px;margin:12px 0}
.party .role{font-size:11px;text-transform:uppercase;color:#999;margin-bottom:4px}
.party .name{font-weight:600;color:#1a1a2e;font-size:14px}
.term-row{display:flex;justify-content:space-between;padding:8px 0;border-bottom:1px solid #f0f0f0}
.term-row:last-child{border-bottom:none}
.term-label{color:#666;font-size:13px}
.term-value{font-weight:600;color:#1a1a2e;font-size:13px}
.highlight{background:#f0f0f0;border-radius:8px;padding:16px;margin:16px 0}
.highlight .label{font-size:12px;color:#666;margin-bottom:4px}
.highlight .value{font-size:18px;font-weight:700;color:#1a1a1a}
.footer{margin-top:32px;padding-top:16px;border-top:1px solid #eee;font-size:11px;color:#999;text-align:center}
</style></head><body>
<div class="container">
  <div class="header">
    <h1>SERVICE AGREEMENT</h1>
    <div class="subtitle">Terms and Conditions</div>
  </div>
  <div class="section">
    <div class="section-title">Parties</div>
    <div class="party">
      <div class="role">Client</div>
      <div class="name">{{sender}}</div>
    </div>
    <div class="party">
      <div class="role">Service Provider</div>
      <div class="name">{{recipient}}</div>
    </div>
  </div>
  <div class="section">
    <div class="section-title">Terms</div>
    <div class="term-row"><span class="term-label">Effective Date</span><span class="term-value">{{date}}</span></div>
    <div class="term-row"><span class="term-label">Duration</span><span class="term-value">{{duration}}</span></div>
    <div class="term-row"><span class="term-label">Payment Terms</span><span class="term-value">{{paymentTerms}}</span></div>
  </div>
  <div class="highlight">
    <div class="label">Total Compensation</div>
    <div class="value">{{amount}} USDC</div>
  </div>
  <div class="section">
    <div class="section-title">Scope of Work</div>
    <p style="font-size:13px;color:#444">{{scope}}</p>
  </div>
  <div class="footer">
    Transaction: {{txHash}}<br>
    This agreement was generated by Goji P2P Workspace
  </div>
</div>
</body></html>`
  }
]

export function renderTemplate(html: string, vars: Record<string, string>): string {
  let result = html || ''
  for (const [key, value] of Object.entries(vars)) {
    result = result.replace(new RegExp(`{{${key}}}`, 'g'), value)
  }
  return result
}
